### ISSUE TITLE
突然想到，或许可以继续整合？

### ISSUE THREAD

**Issue by jogGUY** [wgh136/PicaComic#10]
现在把Eh整合进去了，那么或许也可以继续整合Pixiv、禁漫？不过这样总感觉会变得乱七八糟。🤣

**Comment by wgh136** [comment]
禁漫可以考虑, 有时间了整
Pixiv感觉没什么必要, 毕竟它是一个插画为主的网站, 上面的漫画也都是日语
不管怎么整合, 本项目永远是一个漫画APP

**Comment by jogGUY** [comment]
Pixiv的话倒也是，主要就是奔着下图去的。不过我感觉本项目现在是PicaComic→Tachiyomi/异次元了......🤣
