### ISSUE TITLE
哔咔漫画详情问题

### ISSUE THREAD

**Issue by scp23328** [wgh136/PicaComic#100]
在用手机访问哔咔漫画时，漫画的略缩图等信息能够加载，但点进漫画详情时会产生如下错误，访问时已使用梯子
![Screenshot_20230725_024033_com github wgh136 pica_comic](https://github.com/wgh136/PicaComic/assets/55753366/f9fe488e-dbc8-4df3-8edb-37a7f7ba6f65)

**Comment by wgh136** [comment]
看了一下，哔咔的相关推荐无法加载，是官方的服务器问题，等官方修复吧。如果长时间没修复，我会将相关推荐去掉



________________________________
From: scp23328 ***@***.***>
Sent: Tuesday, July 25, 2023 2:50:08 AM
To: wgh136/PicaComic ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [wgh136/PicaComic] 哔咔漫画详情问题 (Issue #100)


在用手机访问哔咔漫画时，漫画的略缩图等信息能够加载，但点进漫画详情时会产生如下错误，访问时已使用梯子
[Screenshot_20230725_024033_com github wgh136 pica_comic]<https://user-images.githubusercontent.com/55753366/255685556-f9fe488e-dbc8-4df3-8edb-37a7f7ba6f65.jpg>

―

**Comment by wgh136** [comment]
我在我的服务器上做了调整, 当尝试访问相关推荐时返回空数据, 现在你使用转发服务器可以查看漫画详情页了

**Comment by wgh136** [comment]
更新至2.0.4版本
