### ISSUE TITLE
bug反馈：pc端观看一些短篇漫画时，在最后一页继续向后滑动会进入无限加载

### ISSUE THREAD

**Issue by tikko-now** [wgh136/PicaComic#101]
pc端观看一些短篇漫画时，在最后一页继续向后滑动（横向翻页）会进入无限加载，长篇则会提示已是最后一章，且进入无限加载后也不能进行任何操作，只能关闭重开，目前是在pica的本本上发现了这个情况，其他源的本本没有试，安卓端也没试

**Comment by tikko-now** [comment]
版本：2.0.4

**Comment by wgh136** [comment]
已修复
