### ISSUE TITLE
搜索是不支持用空格吗？

### ISSUE THREAD

**Issue by FoolShadowMan** [wgh136/PicaComic#104]
搜索时打空格会显示一片空白

**Comment by wgh136** [comment]
![image](https://github.com/wgh136/PicaComic/assets/67669799/2b5d1f44-c139-4f30-939d-a975b38fb839)
有什么问题?

**Comment by wgh136** [comment]
使用官方app搜索`he r`同样没有结果, 因此这不是app的问题

**Comment by FoolShadowMan** [comment]
hitomi.la的搜索

![Screenshot_2023-08-03-22-45-53-11_ac34e1ea2cb6328eff9323b065294cd0](https://github.com/wgh136/PicaComic/assets/121077153/61920fe1-17bf-4e8a-9e91-0b3f5252dbf5)
![Snipaste_2023-08-03_22-47-12](https://github.com/wgh136/PicaComic/assets/121077153/793caf37-989f-4bc3-9258-e1b8b81d45bb)
