### ISSUE TITLE
绅士漫画有些看不了

### ISSUE THREAD

**Issue by dxy0427** [wgh136/PicaComic#105]
![Screenshot_2023-08-04-15-45-40.png](https://github.com/wgh136/PicaComic/assets/137971972/736efb80-5d35-4b8d-bf0a-90f99fb6cb13)

**Comment by wgh136** [comment]
给个漫画名, 我看看是什么情况

**Comment by dxy0427** [comment]
图片里面的差不多全部都看不了![Screenshot_2023-08-04-18-25-44.png](https://github.com/wgh136/PicaComic/assets/137971972/68ef4352-5344-4246-b839-9138e2c4cb12)

![Screenshot_2023-08-04-18-26-00.png](https://github.com/wgh136/PicaComic/assets/137971972/a625ba15-8fe8-498d-b62e-6c6f697a4722)

**Comment by wgh136** [comment]
正则写错了, 这些漫画的图片链接和其他的不太一样
将在下个版本修复
