### ISSUE TITLE
禁漫天堂的漫画无法下载

### ISSUE THREAD

**Issue by colaKot23** [wgh136/PicaComic#106]
手机是荣耀70Pro 已经打开了链接网络的权限,但是下载任意漫画,都很快就下载了一个 0.04m.然后就说下载完成了,实际上点击去就会,显示数据丢失,然后重新在网络上加载显示.  安装了最新的版本依然是这样 2.0.5

**Comment by wgh136** [comment]
将在下个版本中修复
