### ISSUE TITLE
bug 禁漫天堂的漫画下载问题

### ISSUE THREAD

**Issue by preBall** [wgh136/PicaComic#108]
禁漫天堂的漫画点击下载后一直没反应，不过点击暂停后点击继续就会下载，如果一直点击暂停和继续下载速度飞快，最快能到4m/s，不过下载的漫画会间隔几页出现缺页的情况
![Screenshot_2023-08-06-08-45-04-027_com github wgh136 pica_comic](https://github.com/wgh136/PicaComic/assets/87239510/48ecea0f-c590-4cb3-b67f-73fd0dd32198)

**Comment by wgh136** [comment]
感觉是禁漫服务器问题导致在某张图片下载时卡住, 一直点暂停下载可能导致多个异步函数同时进行下载漫画, 从而导致下载进度管理混乱
以上均为猜测, 因为目前的下载相关代码很乱, 是时候该重写了

**Comment by wgh136** [comment]
完成

我认为限制禁漫下载速度的多数情况下并非是用户端网络情况, 而是以下三点
1. 禁漫服务器负载: 禁漫的服务器一直都很烂
2. 用户设备性能: 因为需要进行解密
3. 多线程限制: 我限制了允许的多线程数量, 以减少性能消耗, 毕竟对图片进行解密处理对性能要求较高, 并且会占用大量内存

因此禁漫下载将会远慢于其它漫画源
