### ISSUE TITLE
能否提供对于Linux平台的支持

### ISSUE THREAD

**Issue by JinHaoliag** [wgh136/PicaComic#110]
能否提供对于Linux平台的支持

**Comment by wgh136** [comment]
之前尝试过，直接使用现在的代码效果不是很好，需要时间进行优化

________________________________
From: JinHaoliag ***@***.***>
Sent: Sunday, August 6, 2023 4:45:27 PM
To: wgh136/PicaComic ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [wgh136/PicaComic] 能否提供对于Linux平台的支持 (Issue #110)


能否提供对于Linux平台的支持

―
