### ISSUE TITLE
绅士动漫搜索结果显示不完整

### ISSUE THREAD

**Issue by walltes** [wgh136/PicaComic#111]
<img width="364" alt="Snipaste_2023-08-07_01-16-57" src="https://github.com/wgh136/PicaComic/assets/129079223/b2e4dd44-a51a-44fe-b780-810959515c12">

<img width="401" alt="Snipaste_2023-08-07_01-17-19" src="https://github.com/wgh136/PicaComic/assets/129079223/32c64ee7-2183-4d59-a696-d84d5172c074">

搜索结果仅显示一页

**Comment by wgh136** [comment]
拿到的数据多了个换行符, 导致解析失败
将在下个版本修复
