### ISSUE TITLE
不清楚是不是网络问题，但反馈下

### ISSUE THREAD

**Issue by guest-zero** [wgh136/PicaComic#114]
用的是移动网络，每次下载都没法正常下载，经常出现下载出错的情况，偶尔能完整下载
除此之外，关于下载我想补充下，不知道是不是这个版本开始的。
1、如果在漫画页面，选择全部下载，本来目的是补充新下载的章节，然后删除下载的话，会导致原来下载的漫画一并被删除
2、下载时只能从上往下删，没法先删除下面的
以上，希望能优化下

**Comment by wgh136** [comment]
使用梯子了吗? 不使用的话或多或少会被GFW干扰

关于:
1. 在下载管理器内删除下载, 这里的代码是在有补充下载章节功能之前写的, 那时候当然没考虑到这个问题
2. 是bug

将会进行修复

**Comment by guest-zero** [comment]
没有，直连的，软件除了连接e站，其他情况下看起来不需要梯子

**Comment by wgh136** [comment]
bug已修复, 至于下载出错, 暂时没有方法解决, 提高网络稳定性是唯一方式
