### ISSUE TITLE
订阅系统

### ISSUE THREAD

**Issue by Arlene947** [wgh136/PicaComic#117]
订阅作者/长篇 后续新作 更新显示

**Comment by NidehogeFool** [comment]
这个很重要，很多作者出新作了但是无法及时获取更新，订阅可以解决这一点。

**Comment by wgh136** [comment]
似乎只有eh有官方的订阅功能, 而且只有订阅tag
要实现订阅的话, 在更新数据时必须对每个订阅项目进行一次网络请求, 如果订阅项目很多的话, 更新一次要花很长时间
代码方面不会很复杂, 可以尝试一下

**Comment by Spark-Plug** [comment]
eh的这个订阅功能确实不错，臣附议

**Comment by sf467** [comment]
> 似乎只有eh有官方的订阅功能, 而且只有订阅tag 要实现订阅的话, 在更新数据时必须对每个订阅项目进行一次网络请求, 如果订阅项目很多的话, 更新一次要花很长时间 代码方面不会很复杂, 可以尝试一下

从代码上能否同时请求多个订阅项目，然后就是能否在每天第一次打开软件时后台自动开始发起请求

**Comment by wgh136** [comment]
> > 似乎只有eh有官方的订阅功能, 而且只有订阅tag 要实现订阅的话, 在更新数据时必须对每个订阅项目进行一次网络请求, 如果订阅项目很多的话, 更新一次要花很长时间 代码方面不会很复杂, 可以尝试一下
> 
> 从代码上能否同时请求多个订阅项目，然后就是能否在每天第一次打开软件时后台自动开始发起请求

可以同时发起多个网络请求, 但单个网络请求只能获取一个漫画的信息

**Comment by sf467** [comment]
> > > 似乎只有eh有官方的订阅功能, 而且只有订阅tag 要实现订阅的话, 在更新数据时必须对每个订阅项目进行一次网络请求, 如果订阅项目很多的话, 更新一次要花很长时间 代码方面不会很复杂, 可以尝试一下
> > 
> > 
> > 从代码上能否同时请求多个订阅项目，然后就是能否在每天第一次打开软件时后台自动开始发起请求
> 
> 可以同时发起多个网络请求, 但单个网络请求只能获取一个漫画的信息

能不能由用户来选择同时发起的网络请求数，就像阅读的那个同时发起的搜索数一样
![0519ce16e0b7ca904548ea0564bd2c2d](https://github.com/wgh136/PicaComic/assets/121373973/26ed7058-f72b-4a1a-ac37-9e31af4d275f)

**Comment by wgh136** [comment]
实际实现起来较为困难, 不做了
