### ISSUE TITLE
🎉整合禁漫天堂

### ISSUE THREAD

**Issue by wgh136** [wgh136/PicaComic#12]
## 计划实现禁漫天堂的主要功能
- [x] 主页
- [x] 最新
- [x] 搜索
- [x] 排行榜
- [x] 分类
- [x] 漫画详情
- [x] 登录
- [x] 喜欢漫画
- [x] 漫画收藏
- [x] 漫画阅读
- [x] 查看评论
- [x] 下载
- [x] 发送评论
- [ ] 排行榜筛选

虽然禁漫天堂的排行榜和分类合并在一起, 但为了ui的统一, 将其分离为两个功能

**Comment by wgh136** [comment]
![image](https://user-images.githubusercontent.com/67669799/233836980-d4486b91-62bb-466f-8193-074bed04f811.png)
有点离谱

**Comment by jogGUY** [comment]
![Screenshot_2023-04-30-12-02-29](https://user-images.githubusercontent.com/108516858/235334973-6d1f3f77-4dc6-4906-8773-cab76778de27.png)
有点离谱🤷‍♂️

**Comment by wgh136** [comment]
@jogGUY 禁漫的搜索api, 当提供的页面序号大于总共的页面数量时返回最后一页, 这里没有判断是否加载到最后一页, 所以会重复
名字无所谓了

**Comment by jogGUY** [comment]
@wgh136 这样子啊，好像“最新”这一栏划到最下面也是这样的重复现象，也是一样的原理吗？🤔

**Comment by wgh136** [comment]
> @wgh136 这样子啊，好像“最新”这一栏划到最下面也是这样的重复现象，也是一样的原理吗？🤔

是这样的

**Comment by kongmingtang** [comment]
章节能增加定位，还有正序和倒序

**Comment by wgh136** [comment]
> 章节能增加定位，还有正序和倒序

可以有, 下次更新时加上

**Comment by jogGUY** [comment]
好像禁漫收藏夹中的本子只要超过了一定的数量，那个收藏夹直接就是一片灰什么都不显示了......

话说作者能不能考虑下：

1. 下载可按章节下载，比如有些本子同时提供了熟肉和生肉，但我只想下载生肉，然后不按章节下载的话就是全部打包下载，这就有点蛋疼了
2. 当前有下载任务时，如果退出软件了，直接记录当前的下载进度然后暂停，等下次重新进入时询问是否继续下载
3. 每个本子的标题后依然打个括号标明有多少多少P，因为有时候就想找些快餐冲🤦‍♂️

**Comment by wgh136** [comment]
> 好像禁漫收藏夹中的本子只要超过了一定的数量，那个收藏夹直接就是一片灰什么都不显示了......
> 
> 话说作者能不能考虑下：
> 
> 1. 下载可按章节下载，比如有些本子同时提供了熟肉和生肉，但我只想下载生肉，然后不按章节下载的话就是全部打包下载，这就有点蛋疼了
> 2. 当前有下载任务时，如果退出软件了，直接记录当前的下载进度然后暂停，等下次重新进入时询问是否继续下载
> 3. 每个本子的标题后依然打个括号标明有多少多少P，因为有时候就想找些快餐冲🤦‍♂️

Loading组件写错了, 当要加载下一页时会渲染Loading组件, 所以它挂了
1. 有点麻烦, 有时间了再整
2. 目前是每完成一张图片的下载就会记录一次, app启动时会检查是否有未完成的下载并且询问
3. 哔咔和e-hentai可以, 因为在获取漫画信息时提供了页面数量. 但禁漫没有, 必须完整获取所有章节内容才能得知, 这个工作是在进入阅读器时进行的

**Comment by jogGUY** [comment]
> 目前是每完成一张图片的下载就会记录一次, app启动时会检查是否有未完成的下载并且询问

呃，目前貌似没有这个，我刚刚测试了一下，禁漫点开一个本子先下载，然后直接退出APP，下载任务直接就无了😂

提到loading，我突然想起来，禁漫貌似只要短时间内操作频繁直接就报错，这个也是没法解决的吧？🤔

**Comment by wgh136** [comment]
> 呃，目前貌似没有这个，我刚刚测试了一下，禁漫点开一个本子先下载，然后直接退出APP，下载任务直接就无了😂

禁漫的数据加载有个地方写错了, 读取数据有问题, 哔咔和eh是正常的

>操作频繁直接就报错

这个我没遇到过, 刚才为了测试那个收藏夹问题, 短时间内收藏了很多漫画, 并没有报错

**Comment by jogGUY** [comment]
> 这个我没遇到过, 刚才为了测试那个收藏夹问题, 短时间内收藏了很多漫画, 并没有报错

那是我昨天测试的结果，可能今天的更新无意间修复了？当时我在测试时那个报错也是概率触发的。感觉禁漫的排序选择可以放进搜索那里🤔

**Comment by wgh136** [comment]
> 那是我昨天测试的结果，可能今天的更新无意间修复了？当时我在测试时那个报错也是概率触发的。感觉禁漫的排序选择可以放进搜索那里🤔

可以, 还有什么问题, 建议一并提出, 我在明天的更新解决, 要简单一点的, 毕竟是假期

**Comment by jogGUY** [comment]
呃，禁漫网页的那个挺详细的“类别”做起来简单么？简单的话最近就更？要是麻烦的话就先搁置吧，还是放假要紧🤣

**Comment by wgh136** [comment]
> 呃，禁漫网页的那个挺详细的“类别”做起来简单么？简单的话最近就更？要是麻烦的话就先搁置吧，还是放假要紧🤣

那就是一个关键词搜索, 点击后直接转到搜索页面了, 不知道那些关键词会不会变. 如果会变, 需要写一个爬虫, 不变就直接在app里写个静态的页面就行了

**Comment by jogGUY** [comment]
那个关键词应该是不变的吧？这个似乎更像是它提供了一份Tag列表🤔
另外的话，中长期计划表上建议加一个实现禁漫的排行榜筛选功能🌹

**Comment by wgh136** [comment]
>那个关键词应该是不变的吧？这个似乎更像是它提供了一份Tag列表🤔

那就很简单了, 工作量很小

>另外的话，中长期计划表上建议加一个实现禁漫的排行榜筛选功能🌹

筛选指的是什么?Web端那个`包含顯示`吗, 还是每个分类的排行榜
对于Web端那个`包含顯示`, 由于禁漫app没有, 找不到api, 只能通过爬虫方式解决
每个分类的排行榜目前就有, 在分类里面选择排序模式就行了

**Comment by jogGUY** [comment]
> 筛选指的是什么?Web端那个`包含顯示`吗

对的，就是想到可能会很麻烦，所以我是建议这个作为一个中长期可能实现的功能（突然想到哔咔的能作用于排行榜的关键词屏蔽）。每个分类的排行榜这个，直接叫排序功能就行了233

**Comment by wgh136** [comment]
> > 筛选指的是什么?Web端那个`包含顯示`吗
> 
> 对的，就是想到可能会很麻烦，所以我是建议这个作为一个中长期可能实现的功能（突然想到哔咔的能作用于排行榜的关键词屏蔽）。每个分类的排行榜这个，直接叫排序功能就行了233

ok, 已加入计划

**Comment by jogGUY** [comment]
> > 呃，目前貌似没有这个，我刚刚测试了一下，禁漫点开一个本子先下载，然后直接退出APP，下载任务直接就无了😂
> 
> 禁漫的数据加载有个地方写错了, 读取数据有问题, 哔咔和eh是正常的
> 
> > 操作频繁直接就报错
> 
> 这个我没遇到过, 刚才为了测试那个收藏夹问题, 短时间内收藏了很多漫画, 并没有报错

很不幸，今早我一下就遇到了🤦
![IMG_20230502_095355](https://user-images.githubusercontent.com/108516858/235565545-10e1f8a2-9fb5-486e-b626-c7d80744752a.jpg)

**Comment by wgh136** [comment]
>很不幸，今早我一下就遇到了🤦
这个是连接超时, 具体为什么会连接超时不好说, 可能是禁漫服务器的限制, 这样的话我无法解决

**Comment by jogGUY** [comment]
应该是禁漫本身的限制，然而它这个限制到底怎么判断的我现在还蒙在鼓里，Tachiyomi上的JM插件的设置那里给了一点提示，但不是很清晰🤔

**Comment by singlewalke** [comment]
更新至1.5.5后，出现了已下载界面无法打开的问题。![Screenshot_2023-05-05-09-51-39-668_com.kokoiro.xyz.pica_comic.jpg](https://user-images.githubusercontent.com/129044377/236362946-ead3277a-cde1-4382-8128-aba8bcce0ea0.jpg)

**Comment by singlewalke** [comment]
更新至1.5.5后，出现了已下载无法打开的问题。

**Comment by wgh136** [comment]
> 更新至1.5.5后，出现了已下载无法打开的问题。

解析旧版本的数据出现了问题, 将会在下个版本修复

**Comment by wgh136** [comment]
如果有bug反馈, 功能建议, 请单独开一个issue, 这个issue太长了

**Comment by 1635338327** [comment]
怎么下载，哭了

**Comment by wgh136** [comment]
> 怎么下载，哭了

不能下载吗? 点击下载按钮就会加入下载队列, 下载管理器在已下载页面的右上角
如果进度为0/0表示正在获取漫画信息

**Comment by 1635338327** [comment]
我知道了，点击这个 release v1.5.8    没上过学的人是这样的

**Comment by 1635338327** [comment]
才10M  太神奇了

**Comment by 1635338327** [comment]
为什么我点你的follow没有反应。。

**Comment by 1635338327** [comment]
> 为什么我点你的follow没有反应。。

刷新好了

**Comment by kongmingtang** [comment]
E-hentai，图片太多，是不是会崩？

**Comment by wgh136** [comment]
> E-hentai，图片太多，是不是会崩？

我打开了一个有812页的画廊, 没有发现问题
请详细描述情况
另外, 这个issue回复数量太多了, 如果有问题或者功能建议请单独开一个issue

**Comment by wgh136** [comment]
排行榜筛选作用不大, 等以后有时间再做
标记为完成
