### ISSUE TITLE
删除任务加上确认操作

### ISSUE THREAD

**Issue by preBall** [wgh136/PicaComic#120]
能不能把删除之类的操作加上一个确认页面，比如删除缓存，删除下载任务，还有日志页面的删除按钮可以换个图标吗，第一眼看上去以为是对日志进行排序
![Screenshot_2023-08-15-06-58-54-595_com github wgh136 pica_comic-edit](https://github.com/wgh136/PicaComic/assets/87239510/0f846f32-af41-42bf-8217-03cea7816891)

**Comment by wgh136** [comment]
完成
