### ISSUE TITLE
iOS如何使用

### ISSUE THREAD

**Issue by edifier1666** [wgh136/PicaComic#121]
苹果的ipa文件必须要用电脑吗，不知道怎么下载ipa文件，能否用手机直接下载到，求告知怎样操作

**Comment by wgh136** [comment]
手机端在本项目的最底部可以找到releases, 在releases页面，每个版本我都放上了iOS的Action链接，打开后，在页面底部有app-ios.ipa, 点击即可下载

**Comment by edifier1666** [comment]
谢谢问题解决了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月16日(周三) 上午7:08
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [wgh136/PicaComic] iOS如何使用 (Issue #121)




 
手机端在本项目的最底部可以找到releases, 在releases页面，每个版本我都放上了iOS的Action链接，打开后，在页面底部有app-ios.ipa, 点击即可下载
