### ISSUE TITLE
e站cookie登录异常

### ISSUE THREAD

**Issue by edifier1666** [wgh136/PicaComic#122]
e站软件版登录成功的cookie不能用在本软件登录望处理![mmexport1692166827605.jpg](https://github.com/wgh136/PicaComic/assets/122567977/375f9cdd-1265-4043-ba27-e7eb8e103bbc)

![Screenshot_2023-08-16-14-19-46-84_f2f1746601bf3b868d00d5efaf12e601.jpg](https://github.com/wgh136/PicaComic/assets/122567977/a7aff30f-acd1-4ad0-aecb-ab3d50aa4085)

**Comment by wgh136** [comment]
无法复现, 我这里一切正常
App确认Cookie是否有效的方式是访问 https://forums.e-hentai.org/ 获取用户名, 成功获取到了用户名即认为Cookie有效, 并提示登录成功, 否则提示登录失败
你可以在登录失败后打开设置-logs看看具体情况, 如下图, 应当有个`Network`的日志且首行是
`Response https://forums.e-hentai.org/`
![image](https://github.com/wgh136/PicaComic/assets/67669799/e47dd79d-cac4-467f-88ee-4e54abb5c595)

**Comment by edifier1666** [comment]
又一个问题我的e站账号是里站，在app内登录是可以直联的，但本软件需要科学上网才能加载出来是什么原因



发自我的iPad


------------------ 原始邮件 ------------------
发件人: wgh136 ***@***.***&gt;
发送时间: 2023年8月16日 16:53
收件人: wgh136/PicaComic ***@***.***&gt;
抄送: edifier1666 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [wgh136/PicaComic] e站cookie登录异常 (Issue #122)





 
无法复现, 我这里一切正常
 App确认Cookie是否有效的方式是访问 https://forums.e-hentai.org/ 获取用户名, 成功获取到了用户名即认为Cookie有效, 并提示登录成功, 否则提示登录失败
 你可以在登录失败后打开设置-logs看看具体情况, 如下图, 应当有个Network的日志且首行是
 Response https://forums.e-hentai.org/

**Comment by wgh136** [comment]
可能是你使用的app内置了反封锁的措施？目前支持查看eh的app相当多，我也不知道你用的哪一个

________________________________

**Comment by edifier1666** [comment]
app是彩色的e站，好像没有反封锁措施，应该不是软件的问题，里站应该只能直连的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月16日(周三) 下午5:10
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [wgh136/PicaComic] e站cookie登录异常 (Issue #122)




 可能是你使用的app内置了反封锁的措施？目前支持查看eh的app相当多，我也不知道你用的哪一个 
 
 ________________________________

**Comment by wgh136** [comment]
里站是需要较为干净的IP, 而且对所在地区有一定限制, 不是一定要直连
我从来没成功直连过Eh, 无论是用什么软件
看了一下, 彩E有内置hosts.txt和域名前置功能, 且默认开启, 可能在某些地区有效. 我这里是不行的

**Comment by edifier1666** [comment]
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月16日(周三) 下午5:50
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [wgh136/PicaComic] e站cookie登录异常 (Issue #122)




 
里站是需要较为干净的IP, 而且对所在地区有一定限制, 不是一定要直连
 我从来没成功直连过Eh, 无论是用什么软件
 看了一下, 彩E有内置hosts.txt和域名前置功能, 且默认开启, 可能在某些地区有效. 我这里是不行的
