### ISSUE TITLE
本地收藏夹功能扩展

### ISSUE THREAD

**Issue by adadsws** [wgh136/PicaComic#123]
首先非常感谢您制作的app

提几个小建议：
增加“单击本地收藏夹中漫画，直接阅读，而不必跳转详情页”的功能
长按本地收藏夹中漫画，增加下载，阅读选项
收藏夹内漫画的批量操作：下载，移动，删除等
收藏夹及其内容的拖动排序功能

望采纳，谢谢

**Comment by wgh136** [comment]
了解了

**Comment by wgh136** [comment]
关于直接阅读: 请使用长按菜单或者右键菜单
关于下载选项: 对于目前代码结构来说有点困难
暂时就这样
