### ISSUE TITLE
下载问题

### ISSUE THREAD

**Issue by mahoon777** [wgh136/PicaComic#131]
你们下载都正常么？从更新2.0.7开始，下载就下不动了呢？

**Comment by wgh136** [comment]
2.0.7版本重构了下载相关的代码
测试了一下, EH的下载存在问题, 服务器返回了403响应

**Comment by mahoon777** [comment]
漫画源是哔咔，在线阅读没问题，点下载就没反应，移动、联通、电信三网我都有，没一个能正常下载的，大佬辛苦，谢谢~

**Comment by wgh136** [comment]
我这里哔咔下载是正常的.
在线阅读和下载获取图片的方式是一样的, 所以我认为出现问题的不是网络
能否打开设置-logs看看有没有错误日志, 注意APP运行结束后日志会被清除, 你需要先尝试下载再去看日志

**Comment by mahoon777** [comment]
GET https://storage-b.picacomic.com/static/tobeimg/p5v1E7nDBmT7ZUXIj8W4BPXBVU2a25mPkI7rE6HoA40/rs:fill:300:400:0/g:sm/aHR0cHM6Ly9zdG9yYWdlLWIucGljYWNvbWljLmNvbS9zdGF0aWMvOGJiOWExMTQtZTg3Ny00MzE2LWJlMDItNjg4ODMwZmRmNjU3LmpwZw.jpg
headers:
{}
data:null

**Comment by mahoon777** [comment]
DioException [unknown]: null
Error: SocketException: Connection failed (OS Error: Network is unreachable, errno = 101), address = storage-b.picacomic.com, port = 443
#0      DioMixin.fetch.<anonymous closure> (package:dio/src/dio_mixin.dart:533)
#1      _rootRunUnary (dart:async/zone.dart:1407)
#2      _CustomZone.runUnary (dart:async/zone.dart:1308)
#3      _FutureListener.handleError (dart:async/future_impl.dart:165)
#4      Future._propagateToListeners.handleError (dart:async/future_impl.dart:796)
#5      Future._propagateToListeners (dart:async/future_impl.dart:817)
#6      Future._completeError (dart:async/future_impl.dart:592)
#7      _SyncCompleter._completeError (dart:async/future_impl.dart:51)
#8      _Completer.completeError (dart:async/future_impl.dart:23)
#9      Future.any.onError (dart:async/future.dart:620)
#10     _rootRunBinary (dart:async/zone.dart:1423)
#11     _CustomZone.runBinary (dart:async/zone.dart:1315)
#12     _FutureListener.handleError (dart:async/future_impl.dart:162)
#13     Future._propagateToListeners.handleError (dart:async/future_impl.dart:796)
#14     Future._propagateToListeners (dart:async/future_impl.dart:817)
#15     Future._completeError (dart:async/future_impl.dart:592)
#16     Future._chainForeignFuture.<anonymous closure> (dart:async/future_impl.dart:537)
#17     _rootRun (dart:async/zone.dart:1399)
#18     _CustomZone.run (dart:async/zone.dart:1301)
#19     _CustomZone.runGuarded (dart:async/zone.dart:1209)
#20     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249)
#21     _microtaskLoop (dart:async/schedule_microtask.dart:40)
#22     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49)

**Comment by mahoon777** [comment]
ClientException with SocketException: HTTP connection timed out after 0:00:05.000000, host: storage1.picacomic.com, port: 443, uri=https://storage1.picacomic.com/static/tobeimg/Fd19HfWuAFq2mH0Hm9IK5lOY6Hs4MnP4no8ve5ONEpU/rs:fill:300:400:0/g:sm/aHR0cHM6Ly9zdG9yYWdlMS5waWNhY29taWMuY29tL3N0YXRpYy9lNWNkZjVmYi1mYWExLTRlMzUtYjg4My02ZDRhM2I0NGQzNTAuanBn.jpg

**Comment by mahoon777** [comment]
对了大佬，我这里必须勾选“使用转发服务器”才能浏览哔咔，否则链接哔咔超时

**Comment by wgh136** [comment]
重构下载代码的时候忘了有转发服务器这回事了, 将会进行修复

**Comment by mahoon777** [comment]
好的，大佬辛苦，但我用官方原版登陆，分流2、分流3都可以直接正常登陆，用咱的app，不勾选“转发服务器”，分流1、2、3选哪个都无法直接登陆，都超时

**Comment by wgh136** [comment]
官方APP有使用cloudflare ip访问. 
本项目中, 由于dart的限制, 使用这种方式存在安全问题.
转发服务器能够使用就暂时不考虑这些东西

**Comment by mahoon777** [comment]
收到，再次感谢大佬回复，辛苦啦，不着急，等你有空再修复就行~

**Comment by wgh136** [comment]
完成
