### ISSUE TITLE
图片适应宽度功能

### ISSUE THREAD

**Issue by mx41shy** [wgh136/PicaComic#134]
首先非常感谢您制作的app

提个小建议：
希望可以增加图片适应宽度的功能。

望采纳，谢谢

**Comment by wgh136** [comment]
了解了

**Comment by mx41shy** [comment]
> 了解了


作者你好，目前的阅读器似乎是每一页图片以外的部分以黑色进行填充，图片和黑色填充在同一层，形成了一个整体，所以缩放后拖动图片可以看到大片的黑边（拖动后不方便归中）。
![image](https://github.com/wgh136/PicaComic/assets/16437280/0e8b73c0-ebdc-42f2-b26f-f61441c70bc2)

这种这种模式下还方便获取图片宽度吗？可不可以让图片和背景在两个图层，图片居中放置，缩放针对图片动作，黑色背景宽度适应对话框宽度和图片宽度较大一方的宽度，高度适应图片高度。

**Comment by wgh136** [comment]
背景和图片并不是同一层, 但缩放区域是整个页面, 即背景和图片组成的整体, 这是目前的情况下唯一的实现方式
要解决这个问题, 只能通过限制移动区域和限制缩放锚点的方式解决. 即在移动时, 阻止超出范围的图片移动操作, 在缩放时, 确保锚点在图片上

**Comment by wgh136** [comment]
现在当超出范围时将会自动调整图片位置
