### ISSUE TITLE
建议：已收藏的本子还有已经看过的本子能有个显眼的标记

### ISSUE THREAD

**Issue by A99011** [wgh136/PicaComic#135]
以及本地收藏能做出和网络收藏一样的逻辑，如果收藏了希望在被收藏的文件夹有个标记并且可以在收藏界面取消

**Comment by wgh136** [comment]
关于"已收藏的本子有个显眼的标记": 你指的是在漫画详情页面吗, 如果是的话, 绅士漫画无法做到(因为其没有提供接口, 要判断一个绅士漫画是否被收藏, 最坏的情况下需要获取每一个收藏夹的每一页), 其它的可以;
关于"被收藏的文件夹有个标记并且可以在收藏界面取消": 可以

**Comment by wgh136** [comment]
完成
