### ISSUE TITLE
禁漫下载性能问题和页面跳转问题

### ISSUE THREAD

**Issue by preBall** [wgh136/PicaComic#137]
下载禁漫的漫画时，app会变得很卡，而且在禁漫任一漫画详情界面点击其它漫画不会跳转，但是如果使用安卓手势返回上一界面就会进入点击的漫画界面。还有就是下载漫画时不在下载管理器界面就不会下载。

**Comment by wgh136** [comment]
关于变卡: 禁漫图片进行了加密处理, app需要进行解密, 此步骤对CPU压力较大, 下载时同时允许5张图片的下载, 如果同时5张图片进行解密, 移动端处理器可能性能不太够

关于不会跳转: 此问题是在v2.0.7版本出现的, 并在v2.0.8版本得到解决, 请更新APP

关于不在下载管理器界面不会下载: 我这里测试未发现

**Comment by wgh136** [comment]
你的图片上传失败了
我发现在探索页面的查看更多里面的漫画存在不能跳转的问题, 禁漫的漫画详情页并没有问题

**Comment by wgh136** [comment]
了解了, 已下载的漫画里面存在问题, 此问题会在下个版本(v2.1.0)修复

**Comment by wgh136** [comment]
要么修改目录前确保下载完成, 要么修改目录后再进行下载
对于一个下载任务, 储存位置会在下载前读取设置确定, 并在下载时不会发生变化, 否则由于多张图片的并行下载会导致一些奇怪的问题
我应当在修改目录那里加一个限制, 阻止在有下载任务时修改下载目录

**Comment by wgh136** [comment]
完成
