### ISSUE TITLE
可以多标签搜索吗 

### ISSUE THREAD

**Issue by 1275688416** [wgh136/PicaComic#138]
收到更新第一时间就更新使用了一下 标签自动匹配很nice 但是点一下就直接搜索了 多标签搜索这个功能可能实现吗 比如全彩+NTR 这种

**Comment by wgh136** [comment]
那就改成点击后补充到搜索框中，不难实现

________________________________
From: 1275688416 ***@***.***>
Sent: Tuesday, August 22, 2023 5:54:54 PM
To: wgh136/PicaComic ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [wgh136/PicaComic] 可以多标签搜索吗 (Issue #138)


收到更新第一时间就更新使用了一下 标签自动匹配很nice 但是点一下就直接搜索了 多标签搜索这个功能可能实现吗 比如全彩+NTR 这种

―

**Comment by 1275688416** [comment]
这个搜索功能能不能实现 是不是要看漫画源本身的搜索是否支持 e站的搜索关键字分割好像是空格 但哔卡好像就不是

**Comment by wgh136** [comment]
是这样的，我也没搞懂哔咔的搜索逻辑

________________________________

**Comment by wgh136** [comment]
现在会补充在搜索栏上, 可以添加多个标签
