### ISSUE TITLE
目前使用遇到的问题

### ISSUE THREAD

**Issue by ewwwda** [wgh136/PicaComic#14]
你好，我最近发现了这个项目，用了几天，感觉很实用。同时，我也想提一些建议，希望能对项目有所帮助。
1.
**我注意到项目没有适配导航栏，可能是因为大家都习惯用手势**
![Screenshot_20230425_184017_com.kokoiro.xyz.pica_comic.jpg](https://user-images.githubusercontent.com/29039907/234485509-098e16f3-651d-4ef6-8d6c-2da2cc0793ac.jpg)

2.
**当我更改阅读模式为从右到左后，拖动翻页的方向是正确的，但是如果我点击屏幕左侧或右侧，翻页的方向还是从左到右，这样就不太符合阅读习惯了**
　　
这两个问题比较重要，影响了使用体验。
　　
下面是我的一些关于界面上的小建议，希望能采纳
1.
**在漫画信息界面，有时要下拉才能看到阅读按钮，这样不太方便。而且标签的气泡太小，显得文字很挤，可以放大一点，一行只显示三四个左右比较合适。
我觉得可以参考EhViewer的界面布局，把封面图和作者信息并列放在上方，然后底下直接显示下载和阅读按钮，下面再是标签。这样看起来更清晰和美观。**
![Screenshot_20230426_143428_moe.tarsin.ehviewer.jpg](https://user-images.githubusercontent.com/29039907/234492838-d5629772-3e3a-4c2a-8d2a-bee934bc5c4a.jpg)

2.
**我觉得动画的速度有点太快了，我觉得可以试着改慢一点更自然**

如果你采纳了我的建议，非常感激。软件很棒，我会继续支持和关注的。

**Comment by wgh136** [comment]
1. 导航栏和点按翻页问题已解决
2. 关于ui, 调大了标签气泡, 将阅读,下载按钮放到了前面
3. 参考EhViewer的界面布局似乎不可行, 因为我希望三个漫画源以及不同的设备尺寸均拥有统一的ui, EhViewer的这套ui无法做到这一点
4. 关于动画, 不清楚你具体指的是哪里的动画, 调整了一些我认为不太好的动画

**Comment by wgh136** [comment]
由于没有回复, 暂时认为已经解决, 关闭此issue, 如有问题可以再打开issue
