### ISSUE TITLE
希望增加显示日语标题的功能

### ISSUE THREAD

**Issue by jwy090815** [wgh136/PicaComic#140]
如题

**Comment by wgh136** [comment]
EH吗, 了解了

**Comment by jwy090815** [comment]
> EH吗, 了解了

ehentai和nhentai都需要，拜托了

**Comment by wgh136** [comment]
nhentai不是有吗

**Comment by jwy090815** [comment]
![搜狗截图20230824194438](https://github.com/wgh136/PicaComic/assets/17699605/94fa5fd5-c070-403e-93a5-1c7ea39305fb)
哦，我不是指点进去的界面，而是漫画列表希望提供日文英文切换显示的功能

**Comment by jwy090815** [comment]
> nhentai不是有吗

![搜狗截图20230824194438](https://github.com/wgh136/PicaComic/assets/17699605/215b8cfe-316a-43fe-92b3-180718a03309)
哦，我不是指点进去的界面，而是漫画列表希望提供日文英文切换显示的功能

**Comment by wgh136** [comment]
nhentai没有提供, 这我无能为力
EH的话可以去官方网站的设置中调整为优先显示日语标题
![image](https://github.com/wgh136/PicaComic/assets/67669799/ddaca262-baf0-491b-b716-cecd98567e3f)

**Comment by jwy090815** [comment]
> nhentai没有提供, 这我无能为力
> EH的话可以去官方网站的设置中调整为优先显示日语标题
> ![image](https://github.com/wgh136/PicaComic/assets/67669799/ddaca262-baf0-491b-b716-cecd98567e3f)
> 

哦原来ehentai能直接设置，有一个就可以了，谢谢提醒
