### ISSUE TITLE
[BUG]滚轮动作异常

### ISSUE THREAD

**Issue by mx41shy** [wgh136/PicaComic#143]
WIN10环境上下滚动（连续）模式下
1、图片放大后，在首页无法通过滚轮到达首页图片顶部，在尾页无法通过滚轮到达首页图片底部。
2、图片放大后，关闭工具栏再打开工具栏后，滚轮连续滚动时滚动距离变短，单次滚动时距离不变。

**Comment by wgh136** [comment]
了解了

**Comment by wgh136** [comment]
已修复, 同时增加了使用CRTL+鼠标滚轮缩放
