### ISSUE TITLE
[BUG]滚轮动作异常

### ISSUE THREAD

**Issue by mx41shy** [wgh136/PicaComic#145]
已修复, 同时增加了使用CRTL+鼠标滚轮缩放

_Originally posted by @wgh136 in https://github.com/wgh136/PicaComic/issues/143#issuecomment-1694618076_

作者您好，经测试目前是这样的状态：
WIN10环境上下滚动（连续）模式下
1、图片放大后，关闭工具栏再打开工具栏后：如果首页顶部与上边界对齐后，则滚轮连续滚动到达尾页或者滚轮单次首次到达尾页时无法到达尾页底部；如果尾页底部与下边界对齐后，则滚轮连续滚动到达首页或者滚轮单次首次到达尾页时无法到达首页顶部。
2、滚轮连续滚动时滚动距离随缩放变化，放大时滚动距离变大，缩小后滚动距离变小，而且目前滚动距离相较2.10版本似乎变大了，约为之前的两倍（一张图片在2.10时需要滚动11次目前只需要滚动6次），使用CRTL+鼠标滚轮缩放至最小后继续向下滚动（需按住CRTL）时滚轮间距仍为2.10时的状态。

**Comment by mx41shy** [comment]
作者你好，经测试目前是这样的状态：
WIN10环境上下滚动（连续）模式下
1、图片放大后，关闭工具栏再打开工具栏后：如果首页顶部与上边界对齐后，则滚轮连续滚动到达尾页或者滚轮单次首次到达尾页时无法到达尾页底部；如果尾页底部与下边界对齐后，则滚轮连续滚动到达首页或者滚轮单次首次到达尾页时无法到达首页顶部。
2、滚轮连续滚动时滚动距离随缩放变化，放大时滚动距离变大，缩小后滚动距离变小，而且目前滚动距离相较2.10版本似乎变大了，约为之前的两倍（一张图片在2.10时需要滚动11次目前只需要滚动6次），使用CRTL+鼠标滚轮缩放至最小后继续向下滚动（需按住CRTL）时滚轮间距仍为2.10时的状态。

**Comment by wgh136** [comment]
1. 有点怪, 不清楚是什么原因, 有时间了看看
2. 不随缩放变化会更好吗; 滚动距离确实太大了, 下个版本会调小到1/2

**Comment by mx41shy** [comment]
> 1. 有点怪, 不清楚是什么原因, 有时间了看看
> 2. 不随缩放变化会更好吗; 滚动距离确实太大了, 下个版本会调小到1/2

使用滚轮滚动浏览漫画有点像浏览网页，浏览内容的时候我们会把在浏览的内容尽可能的调整至一个屏幕中，比如说一张图片，一段文字，在漫画的情况下就是分镜，如果说滚动距离大，就很难单独通过滚轮调整浏览内容到屏幕中的合适位置了。
我认为有两种方案较为合理：
1、滚动距离绝对值不变，即如果放大，每张图片则需要滚动更多的次数，但放大后也更容易调整分镜位置。这是我参考了edge浏览器缩放后滚轮动作。
2、滚动距离相对值不变（前提是滚动距离需要比较短），即如果放大，每张图片需要滚动和缩放之前一样的次数，2.10版本时似乎就是这样的。当时滚动距离比较短，放大后滚动时仍然比较好调整位置。

**Comment by mx41shy** [comment]
> 已进行调整, 现在(v2.1.2)效果怎样

效果非常好
