### ISSUE TITLE
禁漫章节阅读以及下载和管理问题

### ISSUE THREAD

**Issue by preBall** [wgh136/PicaComic#147]
在阅读有多章节的漫画时，章节之间的跳转会继承之前阅读章节的页数，例如在第一章的最后一页第20页翻到下一章，就会直接跳到第二章的第21页，如果第二章没有21页会默认显示第1页，这还只是其中一种情况，有时候还会出现其它情况，感觉多章节阅读的问题有点多。还有下载时和下载完成后只有对整本漫画的操作，不能单独删除某个下载好的章节和创建的下载任务。还有下载漫画时可能有某一页有问题，能不能直接跳过这一页，继续下载，这样就不会出现一张漫画出现问题导致整本漫画无法下载的情况出现。

**Comment by wgh136** [comment]
测试了一下，并没有出现这种情况，只是章节跳转后没有更新左下角页数的显示，实际上加载的是第一页，切换页面后左下角的页数显示就会更新。
关于下载相关的建议，将会视情况采纳，有些可能有点麻烦

**Comment by wgh136** [comment]
了解了

**Comment by wgh136** [comment]
v2.1.2章节阅读是否正常
