### ISSUE TITLE
ipa 用xcode 安装的时候一直提示 'unable to install app-ios'

### ISSUE THREAD

**Issue by sevenmine** [wgh136/PicaComic#148]

**Comment by wgh136** [comment]
release里面发布的是未签名的ipa文件, 你需要自己对其签名
另外, 你都用xcode了, 应该是一个开发者吧, 你可以直接从源代码构建, 可以参考[flutter文档](https://docs.flutter.dev/get-started/install/macos)

**Comment by sevenmine** [comment]
嗯，重新签名就好了。感谢，hero!!
