### ISSUE TITLE
有可能整个docker部署吗

### ISSUE THREAD

**Issue by qcqs** [wgh136/PicaComic#149]
服务器上部署个，这样多端同步使用就很方便了。

**Comment by wgh136** [comment]
等我把dart server整明白再说, 目前看到有这个库[shelf](https://pub.dev/packages/shelf)
没多少人用dart写server, 文档有点少

**Comment by wgh136** [comment]
暂时关闭，本项目无法扩展至此功能，等到有时间后单独开一个项目并进行此工作
