### ISSUE TITLE
bug吗

### ISSUE THREAD

**Issue by SoupBagY** [wgh136/PicaComic#15]
禁漫主页
查看更多
往下滑到底会重新刷新页面

**Comment by SoupBagY** [comment]
禁漫汉化组开始
点查看更多
后的页面都是空白的

**Comment by wgh136** [comment]
是bug, 这里忘记测试了所以没发现
禁漫汉化组之后的内容使用的api接口和之前的不一样, 所以出现了空白
感谢告知

**Comment by wgh136** [comment]
已修复
