### ISSUE TITLE
关于nhentai探索和排行榜建议

### ISSUE THREAD

**Issue by wordly123** [wgh136/PicaComic#150]
nhentai可以用语言进行筛选希望添加上语言筛选，以及可以默认进行日榜等等排序，在某个语言或者某个tag筛选下也可以进行日榜，周榜，月榜的排序，可参考NClientV2该APP设计。

**Comment by wgh136** [comment]
了解了

**Comment by wgh136** [comment]
看了一下, 访问 https://nhentai.net/language/chinese/ 和搜索`language:chinese`结果上没有区别, 因此语言筛选功能只需要做一个进行搜索的按钮就好了

**Comment by wordly123** [comment]
> 看了一下, 访问 https://nhentai.net/language/chinese/ 和搜索`language:chinese`结果上没有区别, 因此语言筛选功能只需要做一个进行搜索的按钮就好了

嗯嗯语言筛选之后还能支持日榜周榜月榜就行了

**Comment by wgh136** [comment]
搜索页面有最新日榜周榜月榜的切换, v2.1.1版本中添加的

**Comment by wgh136** [comment]
等下, 没有月榜, nhentai有月榜吗

**Comment by wordly123** [comment]
> 等下, 没有月榜, nhentai有月榜吗

有的 具体参考下我发的图 
![Screenshot_20230903_195718](https://github.com/wgh136/PicaComic/assets/21117763/53dc8b3a-3bbf-49ff-9e55-bd0082de2975)

**Comment by wgh136** [comment]
nhentai官网上没有显示, 似乎被隐藏了, 但可以通过直接输入地址的方式访问
将会在APP中添加

**Comment by wgh136** [comment]
完成
