### ISSUE TITLE
pc登录eh时报错

### ISSUE THREAD

**Issue by Wei-Jian-Xian** [wgh136/PicaComic#152]
---------------------------
无法创建数据目录
---------------------------
Microsoft Edge 无法读取和写入其数据目录:

        C:\Program Files (x86)\PicaComic\webview\EBWebView
---------------------------
确定   
---------------------------

用的ms edge浏览器，

**Comment by wgh136** [comment]
webview的数据目录选择存在问题, 在某些环境下edge没权限写入数据, 下个版本修复

**Comment by wgh136** [comment]
已修复
