### ISSUE TITLE
安卓版无法自定义下载路径吗

### ISSUE THREAD

**Issue by Z-SHUO6260** [wgh136/PicaComic#154]
如题，在下载设置那里好像只能选择下载到app内部空间或者固定路径，能否自定义下载路径？

**Comment by wgh136** [comment]
可以

**Comment by xr1234n** [comment]
> 可以
app的使用目前体验很不错，感谢作者的制作。
但我也有同样的问题，请问如何自定义下载路径，软件设置里并没有看到自定义选项。
![Screenshot_20230908_104051](https://github.com/wgh136/PicaComic/assets/61616196/6c4e376e-e14e-4f9c-b91c-287101ab7994)

希望作者能提供在外部存储设置下载路径的功能，Android 5.0(Lollipop)已经提供了相关API，可以实现此功能为手机节省空间，
这篇文章有相关使用案例https://blog.csdn.net/weixin_35521315/article/details/117547700

**Comment by wgh136** [comment]
@xr1234n 
我的意思是可以实现，并不是现在就有
现在可以将下载目录设置在外部储存，但只能在一个固定的路径
目前安卓端设置中列出的选项是在不额外申请权限的前提下能够直接读写的目录，当你插入sd卡后，此处应当会多出一个选项，路径为sd卡的一个目录
如果想要设置其他目录，需要一个“所有文件访问权”的权限，我一直没有加入这个功能，因为此权限侵犯用户隐私且目前没有必要性

**Comment by Z-SHUO6260** [comment]
> 

了解了，多谢作者制作

**Comment by xr1234n** [comment]
@wgh136 谢谢作者解答，但我插入外置存储后并没有多出新的选项，估计移动硬盘与sd卡安卓识别上还是有区别，无法进行设置。

**Comment by wgh136** [comment]
> @wgh136 谢谢作者解答，但我插入外置存储后并没有多出新的选项，估计移动硬盘与sd卡安卓识别上还是有区别，无法进行设置。

安卓系统并不会自动在可移动储存设备上为App创建一个数据目录，读写可移动储存设备需要单独申请一个权限，且不是持久的，一旦可移动设备移除并重新连接，App需要再次申请权限
