### ISSUE TITLE
禁漫的部分功能建议以及添加新的漫画源支持

### ISSUE THREAD

**Issue by chen8945** [wgh136/PicaComic#155]
## 禁漫部分
- 目前禁漫的收藏夹默认是`按收藏时间排序`，希望能加入`按更新时间排序`并可以在收藏界面自由切换，下面这个图片是禁漫官方收藏夹的切换方式
![IMG_20230907_130550](https://github.com/wgh136/PicaComic/assets/44148812/d78ae069-46ee-4822-a429-ebda52ed70cc)
- 在漫画详情加入更新日期显示和总页数统计
- 禁漫除了总评论区外，还可以查看每个章节的单独评论区，希望也能加入这个功能，按钮大概可以加在下图这个区域
![IMG_20230907_124848](https://github.com/wgh136/PicaComic/assets/44148812/62550630-2e4c-4c92-a5f1-9356d50cc931)

## 一个大概能适用于所有漫画源中多章节漫画的优化建议
- 像下图这样，看过的章节和没看过的章节进行颜色区分，方便进行识别
![IMG_20230907_130623](https://github.com/wgh136/PicaComic/assets/44148812/85561404-ede3-4f81-8c8f-41325e176399)

## 新的漫画源添加请求
- 此站均为中文漫画源且可以直连访问，以下为该站的导航页
https://noy.icu/

**Comment by wgh136** [comment]
东西有点多，拆分为3个issue
