### ISSUE TITLE
安卓版无法点击翻页

### ISSUE THREAD

**Issue by lianyanjiajia** [wgh136/PicaComic#156]
点击翻页只能识别曲面屏边缘
手机是三星s10系统安卓12

**Comment by wgh136** [comment]
目前的点按翻页识别范围是两侧各25%的区域，中间50%为打开菜单
似乎没办法识别设备是否是曲面屏，加上自定义识别范围的选项应该会比较好

**Comment by lianyanjiajia** [comment]
三星s10设置百分之50之后按键翻页依旧不正常
![Screenshot_20231024-233404](https://github.com/wgh136/PicaComic/assets/30580881/becc1e75-2a80-43a8-8581-585750c6fd89)
[https://onedrive.live.com/embed?resid=5A99243C63542F3%21611&authkey=!AFSu6z3pNp7TlXg](url)

**Comment by lianyanjiajia** [comment]
在oppo a5上翻页正常
但在我的switch 安卓虽然也是直屏但也不正常
[https://onedrive.live.com/embed?resid=5A99243C63542F3%21612&authkey=!ANXJgIbM8Myhgtg](url)

**Comment by wgh136** [comment]
怪

**Comment by wgh136** [comment]
无法确定问题

**Comment by lianyanjiajia** [comment]
> 无法确定问题

没事，我现在换滚动翻页了
