### ISSUE TITLE
哔咔的搜索和标签页显示没有任何结果

### ISSUE THREAD

**Issue by SoupBagY** [wgh136/PicaComic#16]
![Screenshot_2023-05-01-07-21-57-28_89462f8338374031d5598bf02925a8f9.jpg](https://user-images.githubusercontent.com/75820074/235380702-c4e4e381-6d85-4576-9c54-fdd473d73bbb.jpg)

![Screenshot_2023-05-01-07-21-46-02_89462f8338374031d5598bf02925a8f9.jpg](https://user-images.githubusercontent.com/75820074/235380704-a55bda22-42b0-4c4a-94fd-2321b90626fb.jpg)

**Comment by wgh136** [comment]
哔咔的问题, 网络请求结果的状态码是500, 用官方app也无法加载

**Comment by SoupBagY** [comment]
> 哔咔的问题, 网络请求结果的状态码是500, 用官方app也无法加载

好的谢谢
