### ISSUE TITLE
交互逻辑相关

### ISSUE THREAD

**Issue by Spark-Plug** [wgh136/PicaComic#161]
1. 希望在漫画详情页（就是能看到封面，标签，预览图那页）可通过左滑返回上一菜单，现在必须要滑倒顶部然后点击左上角的箭头才能返回。
2. 希望能增加个页面跳转功能（比如每页100个）

**Comment by wgh136** [comment]
1. 什么平台，iOS的话应该是有返回手势的，从左侧边缘向右滑动触发
2. 在设置中更改为分页显示即可，每页的数量是由漫画源的后端决定的

**Comment by Spark-Plug** [comment]
1. ios iPad平台，试了很多次确实不能从左侧向右滑动返回
2. 对不起我的锅。抱歉😢

**Comment by wgh136** [comment]
等我看看哪出问题了
