### ISSUE TITLE
问题反馈2个和功能建议2个

### ISSUE THREAD

**Issue by mx41shy** [wgh136/PicaComic#164]
1、手势动作冲突，抛接手势与点击翻页&菜单呼出的冲突。
（这里我是想阐述抛接手势的便利性）
抛接手势分为抛手势和接手势（名字我自己瞎起的），抛手势是指单手握住手机，大拇指指节以较快速度向上或向下拨动，使页面翻动较长距离但是却不需要大拇指滑动较长距离；接手势是指，滑动过程中，在需要停止的时候通过轻点或者按住屏幕，停止正在进行的滑动动作，到达想要浏览内容的动作。
（这里是我发现的问题）
目前如果启用点击翻页功能，在接手势停止滑动的同时如果点击了翻页区域，两个手势的动作会先后触发，先停止滑动然后翻页，如果点击了翻页区域以外的区域则会停止然后打开菜单。所以之前我建议双击/长按打开菜单，目的是为了解决这个手势竞技场问题。
（这里是我觉得可行的方案）
方案来说有很多种。
第一种就是上面提到的让手势差异化避免重复触发（github的pikapika项目是这种处理方式，我觉得它好的地方在于浏览过程中双击菜单相对不容易呼出，而对我个人来说也不需要浏览过程中频繁呼出菜单）。
第二种可以用if滑动中点击{执行停止}elseif非滑动中点击{执行指定的动作}，但是这种我认为有风险，停止之后如何手指仍然在屏幕上短暂停留，可能还是会触发误动作（未测试，但是人的手指动作有模糊性，我觉得应该会有问题）。
第三种是划分手势区域，目前所见的同类型flutter项目中（ehviewer，tachiyomi等），大都预设了几种区域类型，当单击对应的区域后执行对应的动作，这和我过去使用的软件perfect viewer相似，有所不同的是，perfect viewer可以完全定制用户对应屏幕区域的单击/双击/长按功能（区域划分很细功能也很多），而目前的flutter项目中只能选择预设。而我对于现有的有划分【上一页、菜单、下一页】和【菜单（全屏幕）】（关闭点按区域后）有所不满，希望可以增加【无动作区域、菜单、无动作区域】的划分，即只有中间区域单击可以呼出菜单，原本的翻页区域做无动作处理。但是感觉需求又比较独特，泛用性不高。因此，我想到的蹩脚办法就是，划分九宫格区域（中间区域较小），在设置中可以对屏幕对应区域设置功能（无动作、上一页、下一页、菜单共四个功能，后续也有了扩充功能的可能），这样就基本满足了不同设备的区域功能要求，也可以根据用户自身需求进行定制操作。
2、上下滚动模式下保存图片功能存在问题，目前没办法保存最后一页，似乎只能保存倒数第二页，有时只能保存倒数第三页。
3、图片显示的适应宽度、适应高度，适应屏幕等功能，具体可以参考tachiyomi。（之前提了但是被关了，我当时没表达清楚被误会了555）。
4、希望鼠标滚轮翻页也可以像点击翻页一样有翻页动画，这样滚轮动作看起来会更顺畅一些。

敬待您的回复

**Comment by wgh136** [comment]
### 关于1
- 双击/长按的识别会导致单击事件出现延迟, 影响点按翻页的体验
- 进行判断是很好的解决方法, 不存在误触; 手势识别实际上是三个部分组成: 按下, 移动, 抬起; 目前点按翻页的逻辑是当按下时记录位置, 抬起时判断此时的位置与按下时是否一致, 一致时触发翻页; 因此只需要在按下时增加一个判断, 如果处于滑动状态, 停止滑动并忽略后续行为即可
- 对于划分手势区域: 有点麻烦, 有时间再说

因此进行这样的更改即可:
```dart
// src/views/reader/touch_control.dart
      onTapDown: (details){
        if(!logic.scrollController.position.isScrollingNotifier.value){
          tapOffset = details.globalPosition;
        }
      },
```
### 关于2
因为在这种阅读模式下, 没有较好的方式判断当前阅读的图片, 目前的判断是y=0位置(即屏幕上方边缘位置)对应的图片作为当前阅读的图片

### 关于3和4
将在之后的更新中修改
