### ISSUE TITLE
E-Hentai失效了？

### ISSUE THREAD

**Issue by gankumangcao** [wgh136/PicaComic#168]
重新登陆，清楚缓存没效果，能加载出东西就只有排行榜能看到本子，搜索功能空白页什么都没有，收藏页也是空白的
![Screenshot_2023-09-17-05-44-32-706_com.github.wgh136.pica_comic.jpg](https://github.com/wgh136/PicaComic/assets/85823141/ca4da59e-d08d-4958-82ab-2e57f1d701dd)

![Screenshot_2023-09-17-05-44-44-031_com.github.wgh136.pica_comic.jpg](https://github.com/wgh136/PicaComic/assets/85823141/0be22d6f-5ac3-4a0b-8ef3-25be60086971)

**Comment by gankumangcao** [comment]
代理没问题，用别的e-hentai能看

**Comment by gankumangcao** [comment]
折腾了会，e-hentai站里的设置把扩展改回紧凑后可以加载了（图里第三个选项），所以为什么改为扩展就不能加载东西出来呢。![Screenshot_2023-09-17-05-53-28-098_moe.tarsin.ehviewer.png](https://github.com/wgh136/PicaComic/assets/85823141/4844a8f1-7512-430a-8643-3281caf5b0be)

**Comment by wgh136** [comment]
是最新版本吗，我试了下没有问题

**Comment by gankumangcao** [comment]
> 是最新版本吗，我试了下没有问题

是最新版本 2.1.2，我刚试了下不行，更换为 Extended 除了排行榜能加载出东西来，别的都加载不出东西，手机版和电脑版都加加载不了，我说的那个设置是 E-Hentai网站里的设置哦
![图像002 2023-09-17](https://github.com/wgh136/PicaComic/assets/85823141/ebc314d8-e5a6-4330-9798-4d41bc91754b)
![图像003 2023-09-17](https://github.com/wgh136/PicaComic/assets/85823141/7f6a701e-9f98-4478-ba2f-12590f7a76e5)
![图像004 2023-09-17](https://github.com/wgh136/PicaComic/assets/85823141/b09631a6-ce74-4c76-9d00-2f3b96ecadef)

**Comment by wgh136** [comment]
但我这里确实没问题
之所以问你是否是最新版，是因为这是旧版本的问题
App在加载eh时会要求以Compact的方式显示，因为我只写了这一种情况下的解析数据代码。旧版本在加载时没有要求以Compact方式显示，存在这个问题，但最新版本应该是没有问题的。

**Comment by wgh136** [comment]
就是这行代码
https://github.com/wgh136/PicaComic/blob/92f5c75c6c3ca849178190e533dcb0045cacd5e3/lib/views/eh_views/eh_home_page.dart#L17

**Comment by wgh136** [comment]
找到问题了，eh的探索页面进行了处理，但是收藏夹和搜索页面没有，因此先访问探索页面的时候不会出现问题
