### ISSUE TITLE
主题图标的显示有问题

### ISSUE THREAD

**Issue by yen-soo** [wgh136/PicaComic#17]
![Screenshot_20230507_103211_One UI Home.png](https://user-images.githubusercontent.com/79788702/236654598-4359a838-6e91-484f-b3f3-56ee736c88f8.png)

如图，系统是One UI 5.1 Android13

**Comment by wgh136** [comment]
了解了, 会进行修复

**Comment by wgh136** [comment]
已修复, 请更新至最新版
