### ISSUE TITLE
在hitomi搜索卡死闪退

### ISSUE THREAD

**Issue by iiikunn** [wgh136/PicaComic#172]
在hitomi搜索 chinese uncensored full color之后整个应用直接卡死，如图中，加载中的条子卡住不动，此时已经无法操作软件。

手机为红米note12t，版本为miui14

我不知道如何把我刚才导出的log上传上来（哭

![Screenshot_2023-09-19-08-15-16-037_com github wgh136 pica_comic](https://github.com/wgh136/PicaComic/assets/144868657/90d9f6cb-4bb4-4d05-b3bc-e57b6acd8301)

**Comment by wgh136** [comment]
似乎是搜索失败后无限重试导致app卡死
将会进行修复
