### ISSUE TITLE
希望添加hitomi详情页里的团队和作者tag 和检索结果里的语言过滤

### ISSUE THREAD

**Issue by lianyanjiajia** [wgh136/PicaComic#175]
<img width="806" alt="image" src="https://github.com/wgh136/PicaComic/assets/30580881/bc631c7a-57fb-4982-a82b-350e451257af">
希望app的详情页能添加如图的团队和作者tag

另外检索结果里没法设定语言 希望添加检索结果里的语言过滤

**Comment by wgh136** [comment]
检索结果指的是搜索吗, 你直接在搜索的时候添加语言关键词就行了, 例如搜索`chinese loli`
但是呢, 目前发布的版本Hitomi搜索存在性能问题, 搜索时加上语言关键词会导致计算量过大, 导致程序卡死, 详见 #172 
将会在下个版本解决

**Comment by lianyanjiajia** [comment]
> 检索结果指的是搜索吗, 你直接在搜索的时候添加语言关键词就行了, 例如搜索`chinese loli` 但是呢, 目前发布的版本Hitomi搜索存在性能问题, 搜索时加上语言关键词会导致计算量过大, 导致程序卡死, 详见 #172 将会在下个版本解决

那作者tag和团队tag能加吗

**Comment by wgh136** [comment]
可以, 没什么难度

**Comment by lianyanjiajia** [comment]
> 可以, 没什么难度

感谢大佬
