### ISSUE TITLE
N站在ios设备上CF挑战无法通过 一直转圈重复验证

### ISSUE THREAD

**Issue by nekoreimu** [wgh136/PicaComic#177]
N站在ios设备上CF挑战无法通过 一直转圈重复验证
![Simulator Screenshot - iPhone 14 Pro - 2023-09-20 at 17 50 27](https://github.com/wgh136/PicaComic/assets/33898438/66c35c99-76a7-412b-9522-f2d9a6f5b409)
![Simulator Screenshot - iPhone 14 Pro - 2023-09-20 at 17 52 42](https://github.com/wgh136/PicaComic/assets/33898438/a16b8a0c-6b1d-484e-9285-572c50abd90c)
![Simulator Screenshot - iPhone 14 Pro - 2023-09-20 at 17 50 52](https://github.com/wgh136/PicaComic/assets/33898438/c36fcc66-7b85-44af-9359-8cc7fe04879e)
![Simulator Screenshot - iPhone 14 Pro - 2023-09-20 at 17 51 03](https://github.com/wgh136/PicaComic/assets/33898438/f5fcb588-e787-4859-8969-537ec208596e)

**Comment by wgh136** [comment]
webview的实现可能存在问题

**Comment by wgh136** [comment]
更换webview实现后在模拟器上测试通过
