### ISSUE TITLE
希望能够像Ehviewer那样，增加一个快速搜索的功能，既在搜索页面左滑一下打开选项卡，这个选项卡保存了快速搜索的标签。

### ISSUE THREAD

**Issue by haohaohaoadsad** [wgh136/PicaComic#178]

**Comment by wgh136** [comment]
如果你只是想保存搜索的关键词, 这很简单
如果你希望像EhViewer的快速搜索那样保存浏览的位置, 这依赖于ehentai本身的特点, 也就是说只有eh能够实现, 我不打算做这样的功能

**Comment by haohaohaoadsad** [comment]
> 如果你只是想保存搜索的关键词, 这很简单 如果你希望像EhViewer的快速搜索那样保存浏览的位置, 这依赖于ehentai本身的特点, 也就是说只有eh能够实现, 我不打算做这样的功能

前者 保存搜索的关键词
