### ISSUE TITLE
看exh的本子没看几本就被禁止浏览了

### ISSUE THREAD

**Issue by lianyanjiajia** [wgh136/PicaComic#179]
![Screenshot_20230921-010423](https://github.com/wgh136/PicaComic/assets/30580881/fdcc718b-2a7f-41c4-bf71-6038409beeb4)
每天都会这样
用ehviewer就没有这个问题

**Comment by Spark-Plug** [comment]
我也有同样的问题

**Comment by wgh136** [comment]
了解了
