### ISSUE TITLE
跪求添加模块

### ISSUE THREAD

**Issue by whghjyh** [wgh136/PicaComic#18]
很喜欢这个，大佬有没有兴趣把hitomi.la网站加入进去呢

**Comment by wgh136** [comment]
看了一眼，不难弄，比哔咔，eh，禁漫简单很多
有时间了做

**Comment by kongmingtang** [comment]
能加noyacg吗

**Comment by wgh136** [comment]
> 能加noyacg吗

我没账号, 进不去

**Comment by wgh136** [comment]
> 能加noyacg吗

似乎这个网站不希望太多的人知道和使用, 必须使用邀请码注册
因此不加入noyacg比较好

**Comment by wgh136** [comment]
#19
已加入计划

**Comment by whghjyh** [comment]
感谢您的工作🙏
