### ISSUE TITLE
手机版pica失效了

### ISSUE THREAD

**Issue by YingYeGui** [wgh136/PicaComic#181]

**Comment by wgh136** [comment]
没有问题

**Comment by YingYeGui** [comment]
> 没有问题
![2E193B89CE2FF69E1C848266E21D358D](https://github.com/wgh136/PicaComic/assets/110084144/d9df6d08-0b7d-4679-a1ba-e1ab9c7dea18)
这个怎么解决

**Comment by wgh136** [comment]
怪了, 发下log看看, 注意app彻底退出后log会被清除, 因此请在出现此错误后打开log页面

**Comment by wgh136** [comment]
在log页面点击右上角的三个点, 点击导出, 然后把完整的log文件发出来

**Comment by YingYeGui** [comment]
[logs.txt](https://github.com/wgh136/PicaComic/files/12698482/logs.txt)
它就是分类显示那张图，排行榜还可以看

**Comment by wgh136** [comment]
看了下日志, 获取分类页面数据的时候读取了缓存, 并没有进行网络请求, 由于没有把缓存数据写入日志, 我也不知道数据究竟是什么, 可能是某次失败的网络请求造成的问题
试试清除缓存, 看看能不能解决问题

**Comment by YingYeGui** [comment]
清除缓存不行，我重装了就ok了

**Comment by YingYeGui** [comment]
重装后短暂可以用，但是没多久就会重新变成那样，不过探索和排行榜还能用也能看

**Comment by YingYeGui** [comment]
先这样用着吧辛苦了
