### ISSUE TITLE
禁漫加载缓慢/加载不出

### ISSUE THREAD

**Issue by razilong** [wgh136/PicaComic#182]
浏览哔咔、e站等其他漫画源的漫画都是秒加载，
唯独禁漫，API分流和图片分流我怎么切换都是加载缓慢(十秒钟才出一张图)![Screenshot_2023-09-24-00-11-00-286_com.github.wgh136.pica_comic.jpg](https://github.com/wgh136/PicaComic/assets/97635957/c13ff84d-3efb-43c3-a5a1-5403253cd328)

或者中间的图加载不出![Screenshot_2023-09-24-00-12-00-293_com.github.wgh136.pica_comic.jpg](https://github.com/wgh136/PicaComic/assets/97635957/6c236389-e7ee-4df1-8aa3-dd392ee4d197)

不知是否个人问题，我用官方禁漫app或者[其他禁漫第三方](https://github.com/niuhuan/jasmine)则没有这种问题。

我重新导出了 ![logs.txt](https://github.com/wgh136/PicaComic/files/12706958/logs.txt)

**Comment by wgh136** [comment]
禁漫的图片加载, 进度条前3/4为从禁漫服务器获取图片数据, 后1/4为对图片进行重组
禁漫对图片进行了加密处理, 加密的方式是对图片拆分, 然后按一定规则进行组合; app需要将图片重新拆分组合, 此步骤对CPU的压力较大, 出于性能考虑, 我对其做出了一些限制, 避免过多占用CPU资源
将会进行一些改进

**Comment by wgh136** [comment]
以下为图片重组的时间测试结果, 一行为一张图片的处理用时信息, 斜线左侧为图片被拆分的数量, 右侧为时间(ms)
可以看出用时极长, 难以接受
我的代码完全没有优化空间, 使用的是[image](https://pub.dev/packages/image)库, 我认为是这个库的问题, 但并没有可以替代它的库
有时间了改用c/c++写这部分代码
```
I/flutter (24023): 2/2132
I/flutter (24023): 2/2106
I/flutter (24023): 8/4759
I/flutter (24023): 4/3433
I/flutter (24023): 8/5163
I/flutter (24023): 4/3446
I/flutter (24023): 12/6918
I/flutter (24023): 10/6123
I/flutter (24023): 10/5839
I/flutter (24023): 10/4884
I/flutter (24023): 12/6926
I/flutter (24023): 14/7515
I/flutter (24023): 8/5278
I/flutter (24023): 8/6056
I/flutter (24023): 6/5363
I/flutter (24023): 12/7492
I/flutter (24023): 10/5914
I/flutter (24023): 14/7718
I/flutter (24023): 6/4405
I/flutter (24023): 8/5387
I/flutter (24023): 12/7113
I/flutter (24023): 6/4478
I/flutter (24023): 2/2630
I/flutter (24023): 14/8392
I/flutter (24023): 14/8783
```

**Comment by wgh136** [comment]
经过更详细的测试后得出结论: [image](https://pub.dev/packages/image)库中的图片复制函数`copyCrop`存在问题
使用简单的遍历进行复制能够大幅提高速度
将下列代码
https://github.com/wgh136/PicaComic/blob/92f5c75c6c3ca849178190e533dcb0045cacd5e3/lib/views/jm_views/jm_image_provider/image_recombine.dart#L60-L68
替换为
```
  for (int i = blocks.length - 1; i >= 0; i--) {
    var block = blocks[i];
    int currBlockHeight = block['end']! - block['start']!;
    var range = srcImg.getRange(0, block['start']!, srcImg.width, currBlockHeight);
    var desRange = desImg.getRange(0, y, srcImg.width, currBlockHeight);
    while(range.moveNext() && desRange.moveNext()){
      desRange.current.r = range.current.r;
      desRange.current.g = range.current.g;
      desRange.current.b = range.current.b;
      desRange.current.a = range.current.a;
    }
    y += currBlockHeight;
  }
```
所用时间大幅缩减
以下输出结果, 一行为一张图片的处理用时, 与之前的测试使用同一设备
```
I/flutter (11371): 804
I/flutter (11371): 661
I/flutter (11371): 650
I/flutter (11371): 640
I/flutter (11371): 600
I/flutter (11371): 639
I/flutter (11371): 654
I/flutter (11371): 507
I/flutter (11371): 433
I/flutter (11371): 548
I/flutter (11371): 394
I/flutter (11371): 447
I/flutter (11371): 451
I/flutter (11371): 407
I/flutter (11371): 399
I/flutter (11371): 429
```
总之问题解决
