### ISSUE TITLE
增加新的漫画块显示方式

### ISSUE THREAD

**Issue by yanguiSV0** [wgh136/PicaComic#183]
求求把收藏界面添加一个9宫格排列方式吧

**Comment by yanguiSV0** [comment]
要是能添加一个看完一画默认加载下一话就更完美了

**Comment by wgh136** [comment]
> 求求把收藏界面添加一个9宫格排列方式吧

九宫格排列是什么意思，能具体一点吗

> 要是能添加一个看完一画默认加载下一话就更完美了

在使用从上至下（连续）模式时为了避免误触，滑动到边缘时给了一个按钮用于跳转章节，其他阅读模式下会自动跳转章节

**Comment by yanguiSV0** [comment]
> > 求求把收藏界面添加一个9宫格排列方式吧
> 
> 九宫格排列是什么意思，能具体一点吗
> 就是每一列能横着显示3部收藏的漫画或者更多，每一列都是这样，比如一列3部漫画，那么3列就显示9部漫画，当然每一部只需要显示封面和作品的名字就可以减少很多占的位置啦，还有，谢谢你的回复🌹

>
> 要是能添加一个看完一画默认加载下一话就更完美了
> 
> 在使用从上至下（连续）模式时为了避免误触，滑动到边缘时给了一个按钮用于跳转章节，其他阅读模式下会自动跳转章节
