### ISSUE TITLE
BUG_20230926

### ISSUE THREAD

**Issue by mx41shy** [wgh136/PicaComic#185]
关于1
- 双击/长按的识别会导致单击事件出现延迟, 影响点按翻页的体验
- 进行判断是很好的解决方法, 不存在误触; 手势识别实际上是三个部分组成: 按下, 移动, 抬起; 目前点按翻页的逻辑是当按下时记录位置, 抬起时判断此时的位置与按下时是否一致, 一致时触发翻页; 因此只需要在按下时增加一个判断, 如果处于滑动状态, 停止滑动并忽略后续行为即可
- 对于划分手势区域: 有点麻烦, 有时间再说

因此进行这样的更改即可:
```dart
// lib/views/reader/touch_control.dart
      onTapDown: (details){
        if(!logic.scrollController.position.isScrollingNotifier.value){
          tapOffset = details.globalPosition;
        }
      },
```
### 关于2
因为在这种阅读模式下, 没有较好的方式判断当前阅读的图片, 目前的判断是y=0位置(即屏幕上方边缘位置)对应的图片作为当前阅读的图片

### 关于3和4
将在之后的更新中修改

_Originally posted by @wgh136 in https://github.com/wgh136/PicaComic/issues/164#issuecomment-1716771898_

1.因此只需要在按下时增加一个判断, 如果处于滑动状态, 停止滑动并忽略后续行为即可
经测试这种判断并不能解决滑动停止时打开菜单，滑动停止时菜单仍然经常被打开。

2.目前的判断是y=0位置(即屏幕上方边缘位置)对应的图片作为当前阅读的图片
可不可以读取当前漫画的图片总数N，第P页就判断P*(Y最大值)/N的位置作为当前阅读的图片。

3.从上到下（连续模式）下，适应长宽和容纳都无效，由于是从上到下，希望可以至少让适应宽度生效。

4.希望可以把下载的文件导出到指定目录

5.不太明白点按识别范围数字对应具体的区域

**Comment by wgh136** [comment]
1. 测试的时候应该是没问题的, 我再看看是什么情况
2. 是个不错的想法
3. 了解了, 目前从上到下（连续模式）不受该设置影响
4. 现在有导出压缩文件, 如果希望导出不压缩的文件, PC上很简单, 安卓上有个系统api可以让app获得一个目录的临时访问权限, iOS不太了解
5. 该数字指的是点按翻页一侧的识别范围占屏幕的比例, 例如设置为25%时, 屏幕将依照当前阅读模式的方向分割为25%, 50% 25%三个区域, 中间区域为菜单, 两侧为翻页

**Comment by wgh136** [comment]
关于1:
问题出于当点击时, 先触发了停止滚动, 后触发了点按翻页
关于2:
我认为让用户进行选择会更好, 因此改成这样
![image](https://github.com/wgh136/PicaComic/assets/67669799/92b220d5-8347-4e00-a4d5-103c9578ee9e)
