### ISSUE TITLE
使用禁漫ID查看漫画功能位置已移动

### ISSUE THREAD

**Issue by LMKSHINE** [wgh136/PicaComic#187]
禁漫的ID搜索功能怎么没了呀，挺好用的一个功能，评论区复制的内容粘贴进去还只会识别数字，不用再单独扣词，现在只剩下关键词搜索的功能了，无法搜索ID,希望作者能加回来

**Comment by wgh136** [comment]
在工具里面

**Comment by wgh136** [comment]
这东西与搜索无关，放搜索页面不太好
