### ISSUE TITLE
建议添加收藏夹内搜索和历史记录内搜索及其他

### ISSUE THREAD

**Issue by Chilianxin** [wgh136/PicaComic#188]
另外jm+id这个个人感觉还是在搜索页面更方便一点

在搜索无结果时建议返回一下，不然很容易误认为网络问题

还有是nh的漫画在详情页点击作者的搜索结果有点问题，比如我直接搜索mm和在mm的本里点作者搜索结果一致

**Comment by wgh136** [comment]
> 添加收藏夹内搜索和历史记录内搜索

本地收藏夹和历史记录可以实现, 网络收藏难以实现, 因为那不受我控制


> jm+id这个个人感觉还是在搜索页面更方便一点

那还是改回去吧


> 搜索无结果时建议返回一下，不然很容易误认为网络问题

搜索无结果时会显示空的漫画列表, 网络问题会有明显的错误提示, 这应该是很好区别的


> nh的漫画在详情页点击作者的搜索结果有点问题

了解了
