### ISSUE TITLE
历史记录超过100条会自动清空

### ISSUE THREAD

**Issue by Chilianxin** [wgh136/PicaComic#190]

**Comment by wgh136** [comment]
我现在不方便测试，看代码没发现什么问题，确定是“超过100条”就会出现问题吗

**Comment by Chilianxin** [comment]
> 我现在不方便测试，看代码没发现什么问题，确定是“超过100条”就会出现问题吗

又触发了几次，但是还是没看懂怎么触发的
只知道不是条数影响的，莫名其妙突然历史记录就清空了，有时候用着用着历史记录就没有了

**Comment by Chilianxin** [comment]
> 我现在不方便测试，看代码没发现什么问题，确定是“超过100条”就会出现问题吗

刚刚遇到一次，特别注意了一下
从历史记录进入到漫画页面，阅读，马上返回，再点击“我”页面，进入历史记录后，就清空了
