### ISSUE TITLE
横屏阅读图片不填充

### ISSUE THREAD

**Issue by tmby** [wgh136/PicaComic#191]
如图，在横屏状态下，无论选择哪种图片缩放模式，图片均不会填充到全屏
![1](https://github.com/wgh136/PicaComic/assets/88327304/443c5d74-730e-46c3-bc45-fe09dc469d7d)

![2](https://github.com/wgh136/PicaComic/assets/88327304/3df18834-24e0-44ba-bd81-c922fc783638)

![3](https://github.com/wgh136/PicaComic/assets/88327304/b173b9a4-e271-42e7-9854-b84c1af80f51)

**Comment by wgh136** [comment]
将会在下个版本中添加"限制图片最大显示宽度"设置解决此问题, 此设置默认启用, 如需使图片填充屏幕, 关闭此设置
![image](https://github.com/wgh136/PicaComic/assets/67669799/6e67ebc0-9352-46ee-b379-7382072b0b9a)
