### ISSUE TITLE
导出本地用户不含下载数据时崩溃闪退

### ISSUE THREAD

**Issue by Edmond0813** [wgh136/PicaComic#193]
手机是三星zfold5 在安全文件夹下安装的 之前2.0版本导出是没问题。升级2.2后再次导出不含本地下载的用户数据时 崩溃闪退。请教解决方法

**Comment by wgh136** [comment]
这部分代码应该是没动过的, 暂时不清楚原因

**Comment by wgh136** [comment]
无法确定问题
