### ISSUE TITLE
Hitomi可以正常阅读漫画但是无法下载

### ISSUE THREAD

**Issue by iiikunn** [wgh136/PicaComic#196]
Hitomi的漫画下到一半突然停了，也没提示失败。暂停再次重新开始下载之后就直接报错了，如图，不管哪个站点都一样，但是阅读是正常的。
![Screenshot_2023-10-01-23-56-54-032_com github wgh136 pica_comic](https://github.com/wgh136/PicaComic/assets/144868657/069f313a-fb1e-4b57-a23d-7a8659ea0d16)
![Screenshot_2023-10-01-23-57-26-383_com github wgh136 pica_comic](https://github.com/wgh136/PicaComic/assets/144868657/61ad18b6-1796-4ee6-9b3a-0313d4436af6)
![Uploading Screenshot_2023-10-01-23-57-33-275_com.github.wgh136.pica_comic.jpg…]()

**Comment by wgh136** [comment]
看不出来是什么问题, 我这里测试一切正常

**Comment by wgh136** [comment]
无法确定问题
