### ISSUE TITLE
希望下载下来的漫画导出时支持更多格式

### ISSUE THREAD

**Issue by serrayying** [wgh136/PicaComic#198]
现在的导出格式是生成压缩包打包，如果是.pdf或者是.epub一类的电子书格式的话阅读体验会好一些

**Comment by wgh136** [comment]
pdf可以, 找到了这个package: [pdf](https://pub-web.flutter-io.cn/packages/pdf)
epub有点难度

**Comment by guimc233** [comment]
https://github.com/guimc233/ComicEpubBuilder
