### ISSUE TITLE
哔咔漫画分类页面的抽风问题和绅士漫画的域名更换问题

### ISSUE THREAD

**Issue by jogGUY** [wgh136/PicaComic#199]
关于哔咔漫画：
和 #181 问题相同，第一次出现问题时在30号，靠“清理缓存”解决，第二次出现问题时在1号，只能通过清除所有数据解决，目前不会复现此问题，这可太怪了······

关于绅士漫画：
绅士漫画的主域名被墙不说，给的另外3个.lol域名也已经失效了，搜索引擎搜出来的发布页又换了新的域名。是不是可以弄个自己填域名的功能？（可惜这种网站的网址发布页是变来变去的，不然直接给发布页挺好的）如果可以的话感觉禁漫也可以······

**Comment by wgh136** [comment]
关于哔咔: 确实怪, 把分类页面的缓存功能给删了应该能解决
关于绅士漫画: 确实有必要加上自己填域名功能, 禁漫的api域名很少变动, 因此不需要
