### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by ShiJie137** [wgh136/PicaComic#201]
能否区分普通漫和条漫然后自动切换阅读习惯，就是条漫自动切上下连续

**Comment by wgh136** [comment]
如何判断漫画是条漫

**Comment by sforman2861597** [comment]
首先韩漫都是条漫，日漫基本上是他说的“普通漫”

**Comment by wgh136** [comment]
> 首先韩漫都是条漫，日漫基本上是他说的“普通漫”

那要如何区别韩漫和日漫, 禁漫中有明确的分类, 其它漫画源并没有

**Comment by sforman2861597** [comment]
> > 首先韩漫都是条漫，日漫基本上是他说的“普通漫”
> 
> 那要如何区别韩漫和日漫, 禁漫中有明确的分类, 其它漫画源并没有

哔咔是WEBTOON，别的真没法区分。阅读方式还是只能让用户自己切换

**Comment by wgh136** [comment]
也就是说没办法实现

**Comment by ShiJie137** [comment]
> 也就是说没办法实现

有一个想法，就是设置里有一个默认选项，设置后所有漫画按这个来，然后阅读漫画的时候有另一个只适用于这本漫画（包括多源）的选项，选择后只对当前的生效，和tg的自动翻译累死
