### ISSUE TITLE
eh无法加载漫画详情页

### ISSUE THREAD

**Issue by Spark-Plug** [wgh136/PicaComic#203]
![image](https://github.com/wgh136/PicaComic/assets/27739231/398bffd8-df1a-42a9-83bd-6402c96b0627)

**Comment by Spark-Plug** [comment]
安卓和iPad平台都试了，都是这个

**Comment by wgh136** [comment]
发下日志, 在设置里面

**Comment by Spark-Plug** [comment]
[logs.txt](https://github.com/wgh136/PicaComic/files/12840793/logs.txt)

**Comment by wgh136** [comment]
去EH网站, 在登录的账号和app相同的情况下, 随便点开个本子, 把缩略图显示改为Normal.
或者等我重新上传安装文件, 然后再次安装, 不会修改版本号, 这种错误没必要单独发一个版本

**Comment by wgh136** [comment]
已重新上传, 请重新安装
