### ISSUE TITLE
e-hentai 的 Tags的增强

### ISSUE THREAD

**Issue by sf467** [wgh136/PicaComic#204]
希望ehentai的tag可以采用更“专业”的中文翻译，类似ehviewer那样的

**Comment by wgh136** [comment]
翻译在这里, eh, hitomi, nhentai的标签都是使用这个进行的翻译, 如果你希望修改, 提pr或者直接在这里发修改后的文件都可以
https://github.com/wgh136/PicaComic/blob/5cb604c086e781bf71f935e21f07252898588bb3/lib/tools/tags_translation.dart

**Comment by wgh136** [comment]
应该不难看懂吧, 完全没学过编程的人也应该能看明白
冷门的tag就不要添加了

**Comment by sforman2861597** [comment]
好的我试试

**Comment by sforman2861597** [comment]
tag的翻译有很多是错误的，而且不只是翻译，目前ehentai的tag其实相当不完善，比如不能很便捷地标定tag所属的性别，无法确定空格隔开的两个单词是否为同一个tag，

**Comment by wgh136** [comment]
> tag的翻译有很多是错误的

很正常, 大部分tag都是我用爬虫获取的, 然后交给了chatgpt翻译, 原因也很简单, 我没那么多时间

> 不能很便捷地标定tag所属的性别

这个应该影响不大吧, 你看nhentai那边, 所有的tag都混在一起, 没有对其进行分类, 并没有产生什么问题

> 无法确定空格隔开的两个单词是否为同一个tag

不太明白什么意思, 文件中的翻译是用Map保存的, 在进行翻译时, tag的文本必须和左侧的键的文本完全一致才会被翻译为右侧的结果
假设有tag`multi-work series`, 则必须有有一条`"multi-work series": "多部作品系列"`才能触发翻译, 而`"multi-work": "多作品"`, `"series": "系列"`均无法触发翻译

**Comment by sforman2861597** [comment]
> > tag的翻译有很多是错误的
> 
> 很正常, 大部分tag都是我用爬虫获取的, 然后交给了chatgpt翻译, 原因也很简单, 我没那么多时间
> 
> > 不能很便捷地标定tag所属的性别
> 
> 这个应该影响不大吧, 你看nhentai那边, 所有的tag都混在一起, 没有对其进行分类, 并没有产生什么问题
> 
> > 无法确定空格隔开的两个单词是否为同一个tag
> 
> 不太明白什么意思, 文件中的翻译是用Map保存的, 在进行翻译时, tag的文本必须和左侧的键的文本完全一致才会被翻译为右侧的结果 假设有tag`multi-work series`, 则必须有有一条`"multi-work series": "多部作品系列"`才能触发翻译, 而`"multi-work": "多作品"`, `"series": "系列"`均无法触发翻译

翻译的错误我可以帮忙修改一下
然后是ehentai有一套tag搜索规则https://github.com/kk9448/ehDonate/blob/main/eh%E6%90%9C%E7%B4%A2%E8%A7%84%E5%88%99.md#%E6%90%9C%E7%B4%A2%E8%A7%84%E5%88%99
当然这一套规则可以完全可以自己搜索的时候自己加，如果能在弹出的候选词里自动应用一下那就更方便了。

**Comment by sforman2861597** [comment]
> > tag的翻译有很多是错误的
> 
> 很正常, 大部分tag都是我用爬虫获取的, 然后交给了chatgpt翻译, 原因也很简单, 我没那么多时间
> 
> > 不能很便捷地标定tag所属的性别
> 
> 这个应该影响不大吧, 你看nhentai那边, 所有的tag都混在一起, 没有对其进行分类, 并没有产生什么问题
> 
> > 无法确定空格隔开的两个单词是否为同一个tag
> 
> 不太明白什么意思, 文件中的翻译是用Map保存的, 在进行翻译时, tag的文本必须和左侧的键的文本完全一致才会被翻译为右侧的结果 假设有tag`multi-work series`, 则必须有有一条`"multi-work series": "多部作品系列"`才能触发翻译, 而`"multi-work": "多作品"`, `"series": "系列"`均无法触发翻译

另外ehentai的tag搜索，区分性别还是挺有必要的，比如我要是想看强奸类的，那就是 f:"rape". 如果想看逆推类的，那就是 m:"rape"。然后再引申到别的地方，比如Chinese，如果特指一下 o:"Chinese"那就是中文，不然在Chinese后没有$ 的话也可以指向 chinese dress 唐装

**Comment by wgh136** [comment]
这个就和翻译无关了, 在点击tag时进行额外处理一下即可, 不难实现

**Comment by sf467** [comment]
> 翻译在这里, eh, hitomi, nhentai的标签都是使用这个进行的翻译, 如果你希望修改, 提pr或者直接在这里发修改后的文件都可以 https://github.com/wgh136/PicaComic/blob/5cb604c086e781bf71f935e21f07252898588bb3/lib/tools/tags_translation.dart

翻译已经改完了，不知道怎么提交 https://wwwd.lanzoum.com/iKdEj1b83msj

**Comment by sf467** [comment]
这个是隔壁zhviewer的tag搜索
![54e5797d28943ddb1a26d18cc7ef2bc0](https://github.com/wgh136/PicaComic/assets/121373973/659a2f5f-16f8-47a3-8da1-a31943e85fd9)

![ccf76c5ecd6ec7c0465b67e99ce31dc6](https://github.com/wgh136/PicaComic/assets/121373973/2a087e32-b4e4-4f93-8338-8f5ed8c430e5)

**Comment by wgh136** [comment]
ok, 已修改

**Comment by wgh136** [comment]
大概就改成这样, 目前不太好区分tag的性别, 因此需要手动选择, 而作品或者人物的标签不需要
![image](https://github.com/wgh136/PicaComic/assets/67669799/f6f0bb14-7e62-410c-83bb-96074306ddf9)

**Comment by sf467** [comment]
> 大概就改成这样, 目前不太好区分tag的性别, 因此需要手动选择, 而作品或者人物的标签不需要 ![image](https://user-images.githubusercontent.com/67669799/273557179-f6f0bb14-7e62-410c-83bb-96074306ddf9.png)

这样的话ehentai的tag搜索就更完善了，这个issue可以关闭掉。
但是还是建议作者大大在项目的后期重做一下ehentai的tag系统，我发现一些其他有关于ehentai的项目，都不是这样自己翻译一份，而是从https://github.com/EhTagTranslation/Database/tree/master/database这里直接获取，从而可以保证tag翻译的正确与全面。并且更有利于选择tag的namespace
另外当前的tag搜索似乎并不能分辨一些性别特定的tag比如 milf 和 dilf ，并且不能添加性别之外的namespace比如artist、cosplayer、group、mixed、other 等，而在https://github.com/EhTagTranslation/Database/tree/master/database这里tag就是有12个类，然后搜索的时候直接从这12类里找，然后每一个类对应一个前缀
希望作者大大考虑一下，当然目前这一套也已经足够好用了

**Comment by wgh136** [comment]
那个tag数量实在是太多, 用起来会有点麻烦, 就开发效率而言远不如我用爬虫+gpt, 所以没有用它
暂且这样吧

**Comment by sf467** [comment]
在当前的tag存储方法下，似乎这里的可以直接用https://github.com/Ehviewer-Overhauled/EhTagTranslation/blob/tag-translations/tag-translations/tag-translations-zh-rCN.json

**Comment by wgh136** [comment]
决定改用 https://github.com/EhTagTranslation/Database
写了一个脚本去获取翻译
