### ISSUE TITLE
webdav备份问题反馈

### ISSUE THREAD

**Issue by Wei-Jian-Xian** [wgh136/PicaComic#209]
退出时自动上传备份数据，打开时检测是否有新数据。多端同步ᕕ(ᐛ)ᕗ（类似开源阅读）

**Comment by Goojoe** [comment]
1.无法正常使用，一直卡在uploading。webdav也没有文件。由于无法退出焦点。所以也看不了日志

2.上传的文件包含什么？

**Comment by wgh136** [comment]
> 无法正常使用，一直卡在uploading。webdav也没有文件。由于无法退出焦点。所以也看不了日志

怪, 是在设置的时候吗

> 上传的文件包含什么？

相当于导出不含下载的数据

> 可以加个进度条吗，本次上传xx mb的数据

没必要, 因为文件很小, 正常使用的情况下应该最多1-2MB

**Comment by Goojoe** [comment]
对，是在设置的时候
![Screenshot_2023-10-13-21-12-44-121_com github wgh136 pica_comic-edit](https://github.com/wgh136/PicaComic/assets/78355492/208af605-3ba7-431b-83dd-663d93ca6fbd)

**Comment by wgh136** [comment]
请安装[v2.2.2-hotfix](https://github.com/wgh136/PicaComic/releases/tag/v2.2.2-hotfix)版本

**Comment by Goojoe** [comment]
Failed to upload data to webdav server.
#0      WdDio.wdWriteWithStream (package:webdav_client/src/webdav_dio.dart:477)
<asynchronous suspension>
#1      Webdav.uploadData (package:pica_comic/network/webdav.dart:56)
<asynchronous suspension>
#2      syncDataSettings.<anonymous closure>.<anonymous closure> (package:pica_comic/views/settings/app_settings.dart:800)
<asynchronous suspension>

**Comment by wgh136** [comment]
@Goojoe 
确定填写的储存路径是可写入目录吗
这个错误是成功与webdav服务器建立链接, 但写入文件失败

**Comment by Goojoe** [comment]
是应该这么填:picacomic
还是这么填:/picacomic
这两个都不行诶

**Comment by wgh136** [comment]
看了下源代码
`#0 WdDio.wdWriteWithStream (package:webdav_client/src/webdav_dio.dart:477)`
这里是使用OPTIONS方法连接服务器, 得到响应码为非200, 即服务器的响应存在问题

**Comment by wgh136** [comment]
```dart
    var pResp = await this.wdOptions(self, path, cancelToken: cancelToken);
    if (pResp.statusCode != 200) {
      throw newResponseError(pResp);  // 477
    }
```

**Comment by Goojoe** [comment]
我换了坚果云，可以上传了。但是我不信任国内的云服务提供商

**Comment by wgh136** [comment]
我测试时使用的是alist

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Goojoe** [comment]
我现在使用的webdav提供商，在阅读app也能使用

**Comment by wgh136** [comment]
方便告知什么提供商吗，我去试试

________________________________

**Comment by Goojoe** [comment]
https://infini-cloud.net/ja/index.html

**Comment by TheStoryNeverEnd** [comment]
哔咔的转发服务器死了

**Comment by wgh136** [comment]
@TheStoryNeverEnd 
> 哔咔的转发服务器死了

并没有

**Comment by wgh136** [comment]
@Goojoe 
试了下, 这家服务商的服务器在响应时给出了301响应
```
*** Response ***
flutter: uri: https://ogi.teracloud.jp/dav/picadata/picadata
flutter: statusCode: 301
flutter: headers:
flutter:  content-type: text/html; charset=iso-8859-1
flutter:  location: https://ogi.teracloud.jp/dav/picadata/picadata/
flutter:  date: Sat, 14 Oct 2023 12:28:46 GMT
flutter:  content-length: 255
flutter:  server: Apache
flutter: Response Text:
flutter: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
flutter: <html><head>
flutter: <title>301 Moved Permanently</title>
flutter: </head><body>
flutter: <h1>Moved Permanently</h1>
flutter: <p>The document has moved <a href="https://ogi.teracloud.jp/dav/picadata/picadata/">here</a>.</p>
flutter: </body></html>
```
webdav库不是我写的
目前使用的webdav库是这个 https://github.com/flymzero/webdav_client, 我去提个issue看看什么情况

**Comment by wgh136** [comment]
这东西似乎没在维护了
我自己写个吧

**Comment by wgh136** [comment]
没区别
```
flutter: *** Response ***
flutter: uri: https://seto.teracloud.jp/dav/picadata/picadata
flutter: statusCode: 301
flutter: headers:
flutter:  content-type: text/html; charset=iso-8859-1
flutter:  location: https://seto.teracloud.jp/dav/picadata/picadata/
flutter:  date: Tue, 17 Oct 2023 09:01:54 GMT
flutter:  content-length: 256
flutter:  server: Apache
flutter: Response Text:
flutter: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
flutter: <html><head>
flutter: <title>301 Moved Permanently</title>
flutter: </head><body>
flutter: <h1>Moved Permanently</h1>
flutter: <p>The document has moved <a href="https://seto.teracloud.jp/dav/picadata/picadata/">here</a>.</p>
flutter: </body></html>
```

**Comment by Goojoe** [comment]
好吧，你知道是什么问题吗。还是说得去问webdav提供商

**Comment by wgh136** [comment]
我试试改一下这个库 https://github.com/flymzero/webdav_client, 允许301重定向, 看看能不能解决问题

**Comment by wgh136** [comment]
似乎可以, 问题解决
