### ISSUE TITLE
哔咔的漫画详细页面封面加载问题

### ISSUE THREAD

**Issue by jogGUY** [wgh136/PicaComic#210]
哔咔的封面其实已经在本地有缓存数据了，但是点开漫画的详细页面，封面这块只有一个⚠️，而点击⚠️是可以看到加载完成的封面大图的，诡异······

另：
有时候在搜索/分区排序页面会出现那种看着爱心数很少，但点进详细页面就会发现实际爱心数很多的本子，这是不是哔咔本身的问题？
禁漫的排行榜-日排行有时候会一片白什么都没，而总排行/月排行/周排行都没问题，这是不是禁漫自己抽风了？

**Comment by wgh136** [comment]
> 哔咔的漫画详细页面封面加载问题

没遇到过问题, 看代码也没发现问题

> 点进详细页面就会发现实际爱心数很多的本子

这是哔咔后端传过来的单个漫画数据
```json
     {
        "_id": "59243a14b56446454d9d80d8",
        "title": " サタニックカーニバル",
        "author": " うぉーたーどろっぷ (MA-SA)",
        "pagesCount": 23,
        "epsCount": 1,
        "finished": false,
        "categories": [
          "短篇",
          "同人"
        ],
        "thumb": {
          "fileServer": "https://storage1.picacomic.com",
          "path": "tobeimg/uM3bmQtUrrsnDl84ff-16ltk9PZL_fPlqVTGEwgWzq0/rs:fill:300:400:0/g:sm/aHR0cHM6Ly9zdG9yYWdlMS5waWNhY29taWMuY29tL3N0YXRpYy9lMmY2MTU2Mi04MWE4LTRiMWMtYTljOC0yODkzMmYzMzRlZTIuanBn.jpg",
          "originalName": "00.jpg"
        },
        "totalViews": 97128,
        "totalLikes": 825,
        "likesCount": 825
      },
```
可以看到有两个字段`totalLikes`和`likesCount`, 在某些情况下两者不相等, 具体什么情况我也不知道

> 禁漫的排行榜-日排行有时候会一片白什么都没

试了下, 官方app也是同样的

**Comment by wgh136** [comment]
刚才服务器突然寄了, 等我准备排查问题的时候又好了, 等我看看什么情况

**Comment by wgh136** [comment]
已修复
服务器在整一些新东西, 似乎有点问题, 先换回原来的了

**Comment by wgh136** [comment]
似乎封面加载没走转发服务器

> 软件里填进domain后，有的给RESET了，有的OK，可是过一段时间后原来OK的变RESET了，而原来RESET的变OK了

没看懂什么意思

**Comment by wgh136** [comment]
我这里测试[www.wn4.lol](http://www.wn4.lol/)和[www.wn5.lol](http://www.wn5.lol/)可直连访问, 在app和浏览器均正常
[www.wn04.lol](http://www.wn04.lol/)和[www.wn05.lol](http://www.wn05.lol/)不能直连访问
在使用代理的情况下均能正常访问
