### ISSUE TITLE
大佬有空帮忙看看转发服务器是否正常？最近包括更新222后哔咔都不太稳定，谢谢

### ISSUE THREAD

**Issue by mahoon777** [wgh136/PicaComic#211]

**Comment by wgh136** [comment]
接收数据的超时时间设的太短了, 提高一下应该就没问题了

**Comment by wgh136** [comment]
最近服务器的压力有点大, 导致响应时间延长

**Comment by wgh136** [comment]
请安装[v2.2.2-hotfix](https://github.com/wgh136/PicaComic/releases/tag/v2.2.2-hotfix)版本

**Comment by mahoon777** [comment]
现在OK了，感谢大佬，辛苦啦~
