### ISSUE TITLE
ehentai的tag搜索仍然有缺陷

### ISSUE THREAD

**Issue by sf467** [wgh136/PicaComic#212]
ehentai的tag搜索似乎只有性别，角色，作品的分类，其他的namespace没有，包括“语言”，"coser"，“重新分类”，“作者”，这些项目的tag没有获取到翻译，也没有在搜索候选栏里。希望作者大大可以修复一下

ehentai的漫画一般不会把中文译名放在标题里，所以想要精确搜索漫画只能靠这套tags系统，完善的tag搜索是很有必要的

**Comment by sf467** [comment]
![image](https://github.com/wgh136/PicaComic/assets/121373973/baf34cb8-6e5c-471b-bd80-20c0f8fa4f45)

**Comment by wgh136** [comment]
忘加语言了, 别的应该是有的, 另外限制了数量50条
```dart
        find(TagsTranslation.femaleTags, TranslationType.female);
        find(TagsTranslation.maleTags, TranslationType.male);
        find(TagsTranslation.parodyTags, TranslationType.parody);
        find(TagsTranslation.characterTranslations, TranslationType.character);
        find(TagsTranslation.otherTags, TranslationType.other);
        find(TagsTranslation.mixedTags, TranslationType.mixed);
```

**Comment by sf467** [comment]
> 这是代码, 确实少了几个
> 
> ```dart
>         find(TagsTranslation.femaleTags, TranslationType.female);
>         find(TagsTranslation.maleTags, TranslationType.male);
>         find(TagsTranslation.parodyTags, TranslationType.parody);
>         find(TagsTranslation.characterTranslations, TranslationType.character);
>         find(TagsTranslation.otherTags, TranslationType.other);
>         find(TagsTranslation.mixedTags, TranslationType.mixed);
> ```

https://github.com/EhTagTranslation/Database/blob/master/database/rows.md
rows文件里记录了所有的nameplace
![image](https://github.com/wgh136/PicaComic/assets/121373973/bb83b8cd-0253-4ada-b07e-ce27dec56a85)
然后就是，为什么要限制tag的数量呢

**Comment by wgh136** [comment]
性能问题, 避免过多的性能占用, 将结果渲染到屏幕上是要消耗资源的

**Comment by wgh136** [comment]
50个似乎有点少了, 提高限制会比较好

**Comment by sf467** [comment]
> 性能问题, 避免过多的性能占用, 将结果渲染到屏幕上是要消耗资源的

几个字符也会占用这么大的资源吗。然后就是，限制50个的意思是50个以外的tag不能被翻译，还是不能出现在搜索候选里，还是不会出现在作品的标注里？

**Comment by wgh136** [comment]
不能出现在搜索候选里, 那个是需要消耗大量资源的

**Comment by sf467** [comment]
> 不能出现在搜索候选里, 那个是需要消耗大量资源的

那是不是就是说，如果我将这个tag的翻译完整输入，那就一定可以出现在候选里，50个的限制只是对于自动补全来说的是吧

**Comment by wgh136** [comment]
是的

**Comment by wgh136** [comment]
或者改成动态加载就不存在这个问题了
没做动态加载是因为我认为没人会需要在几百个甚至几千个tags中寻找需要的结果

**Comment by sf467** [comment]
这样的话，50个的限制应该也没有问题

**Comment by sf467** [comment]
或许可以做这么一个页面，里面是所有的tag,然后可以多个同时选中，进行搜索，类似其他的的“分类”页面，然后在“分类“里就有ehentai了（
开个玩笑，ehentai的tag量太庞大了，有些小白不知道他们要搜索的是什么，所以似乎可以这样作为一种示范

**Comment by wgh136** [comment]
可以有, 但是不可能展示所有的tag, 只能展示一部分

**Comment by sf467** [comment]
> 可以有, 但是不可能展示所有的tag, 只能展示一部分

疯狂一点，直接展示所有，反正不是搜索候选框，加载一个静态的界面而已。用户在这种界面对时间也不敏感，加载时间长点就长点。或者就直接按照namepalce分成这么几组折叠起来，需要用的时候就点开开始加载，

你不会真的要把这个界面做出来吧😏

**Comment by wgh136** [comment]
也不是不可以, 没多少工作量, 代码直接从其它分类页面粘贴过来, 把数据源改一下就完成了

**Comment by sf467** [comment]
*⁠\⁠0⁠/⁠*
