### ISSUE TITLE
tag翻译有误

### ISSUE THREAD

**Issue by Swayang98** [wgh136/PicaComic#213]
版本：2.2.2-hotfix windows端
问题：女性类别下的oyakodon翻译为父子丼，看项目描述tag翻译应该是来自EhTagTranslation的，查看这个项目下的文件内容 https://github.com/EhTagTranslation/Database/blob/master/database/female.md ，其中female: oyakodon是翻译为母女丼的
问题图例：截取于eh板块
![1697277077526](https://github.com/wgh136/PicaComic/assets/128770883/30e904bd-d01d-4eb2-a148-ac5de1c824c6)

**Comment by Swayang98** [comment]
看了下本地的tags.json，发现一旁的shimaidon也错翻成了兄弟丼，图为已经手动修改后
![1697278490059](https://github.com/wgh136/PicaComic/assets/128770883/defabda1-1456-40ac-94fd-41e2c67bfe33)
这个json生成的时候是不是有什么遗漏呢，目前刚好撞到有误的就这两个tag

**Comment by wgh136** [comment]
这个是用这里的代码生成的
https://github.com/wgh136/PicaComic/blob/master/utils/tags_translation.dart
翻译源来自
https://github.com/EhTagTranslation/DatabaseReleases/blob/master/db.text.js

**Comment by wgh136** [comment]
![image](https://github.com/wgh136/PicaComic/assets/67669799/7a59590e-1b1c-4793-a953-0f9e96e4e1f4)
似乎翻译源存在错误

**Comment by wgh136** [comment]
等下, 并没有问题, 这个是在male中的, 生成的tags.json也没有问题

**Comment by wgh136** [comment]
![image](https://github.com/wgh136/PicaComic/assets/67669799/ab581cde-46f9-4a1d-a84a-2aa3936c4f73)
![image](https://github.com/wgh136/PicaComic/assets/67669799/ca33ade0-44e5-42f5-8a32-675689b7d315)
仅app在进行翻译时存在问题

**Comment by Swayang98** [comment]
好的，我尝试了下。修改了male类别下oyakodon的翻译，对应发生变动的是female那边的
![1697281211934](https://github.com/wgh136/PicaComic/assets/128770883/97806372-e645-4c1c-9d2b-94b6129cdb86)
![1697281250212](https://github.com/wgh136/PicaComic/assets/128770883/c2bb0fc1-7825-4a7f-a495-10469d55bb12)

**Comment by wgh136** [comment]
已在dev分支中修复
