### ISSUE TITLE
登陆哔咔显示错误

### ISSUE THREAD

**Issue by yanguiSV0** [wgh136/PicaComic#214]
type 'String' is not a subtype of type 'int' of
'index'
显示这么一段话，啥意思啊

**Comment by wgh136** [comment]
发下日志, 在设置里面

**Comment by yanguiSV0** [comment]
> 发下日志,在设置里面

发日志就能登陆了是吗，我下载回之前那个2.12版本倒是直接能登陆了，只不过这个版本不行，我也不会发日志。。

**Comment by wgh136** [comment]
发日志是为了让我确认问题的所在

> 下载回之前那个2.12版本倒是直接能登陆了

怪, 哔咔的登录已经很久没改过了

**Comment by yanguiSV0** [comment]
> 发日志是为了让我确认问题的所在
> 
> > 下载回那个2.12版本之前倒是直接能登陆了
> 
> 奇怪，哔咔的登录已经很久没有改过了

我不知道怎么发，打开日志也没有发送的操作，算了，用2.12版本也没关系

**Comment by yanguiSV0** [comment]
> 发日志是为了让我确认问题的所在
> 
> > 下载回那个2.12版本之前倒是直接能登陆了
> 
> 奇怪，哔咔的登录已经很久没有改过了

可以可以给阅读模式从上至下（连续）也增加自动加载下一话功能啊，其他阅读模式虽然能自动加载，但是看韩漫都是用这个从上至下（连续）模式看的，麻烦了

**Comment by wgh136** [comment]
> 我是觉得老哥你可以考虑把日志导出方法和要求导出日志写在README.MD/Releases/Issue模板里的显眼位置 @wgh136

改好了

**Comment by yanguiSV0** [comment]
> > > 发日志是为了让我确认问题的所在
> > > > 下载回那个2.12版本之前倒是可以直接登陆了
> > > 
> > > 
> > > 奇怪，哔咔的登录已经很久没有改过了
> > 
> > 
> > 我不知道怎么发，打开日志也没有发送的操作，算了，用2.12版本也没关系
> 
> ➡️“日志”设置➡️右上角“···”➡️“导出”，选择然后保存位置@yanguiSV0 所有的软件日志都是面向开发者和运营维护的，有很多玄学问题需要靠日志确认问题所在。

登上了，重新下载最新版本安装又能直接登上去了，不过下次有问题我会先把日志导出来的

**Comment by wgh136** [comment]
那就先关闭了
