### ISSUE TITLE
[Bug]: 全部页面无法访问

### ISSUE THREAD

**Issue by Spark-Plug** [wgh136/PicaComic#218]
### 描述

更新到v2.2.2-hotfix后全部显示如截图中的报错

### Version

latest

### 使用的操作系统

iOS

### 日志

Logs

info App Status 2023-10-16 16:01:28.483915 
CLOSE TO ROUTE /LogsPage

info App Status 2023-10-16 16:01:29.570587 
"CalculateCacheLogic" onDelete() called

info App Status 2023-10-16 16:01:29.570589 
"CalculateCacheLogic" deleted from memory

info App Status 2023-10-16 16:01:37.515490 
Instance "NhentaiHomePageController" has been created

info App Status 2023-10-16 16:01:37.515503 
Instance "NhentaiHomePageController" has been initialized

info Network 2023-10-16 16:01:37.527121 
Set Proxy PROXY :0;

info Network 2023-10-16 16:01:37.529079 
GET https://www.jmapinode2.cc/hot_tags?key=0b931a6f4b5ccc3f8d870839d07ae7b2&view_mode_debug=1&view_mode=null
headers:
{token: 913044a6b230799b8516491fbfd21bf5, tokenparam: 1697443297,1.5.9, user-agent: Mozilla/5.0 (Linux; Android 13; JM114514 Build/TQ1A.230205.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/114.0.5735.196 Safari/537.36, accept-encoding: gzip}
data:null

error Network 2023-10-16 16:01:37.531382 
GET https://www.jmapinode2.cc/hot_tags?key=0b931a6f4b5ccc3f8d870839d07ae7b2&view_mode_debug=1&view_mode=null
DioException [unknown]: null
Error: HttpException: Invalid proxy configuration PROXY :0;

info Network 2023-10-16 16:01:40.700174 
Set Proxy PROXY :0;

info Network 2023-10-16 16:01:40.702319 
GET https://e-hentai.org?inline_set=dm_l
headers:
{user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36}
data:null

error Network 2023-10-16 16:01:40.703233 
GET https://e-hentai.org?inline_set=dm_l
DioException [unknown]: null
Error: HttpException: Invalid proxy configuration PROXY :0;

info Network 2023-10-16 16:01:41.791638 
Set Proxy PROXY :0;

info Network 2023-10-16 16:01:41.793632 
GET https://e-hentai.org?inline_set=dm_l
headers:
{user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36}
data:null

error Network 2023-10-16 16:01:41.794474 
GET https://e-hentai.org?inline_set=dm_l
DioException [unknown]: null
Error: HttpException: Invalid proxy configuration PROXY :0;

info Network 2023-10-16 16:01:42.333638 
Set Proxy PROXY :0;

info Network 2023-10-16 16:01:42.335966 
GET https://e-hentai.org?inline_set=dm_l
headers:
{user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36}
data:null

error Network 2023-10-16 16:01:42.336807 
GET https://e-hentai.org?inline_set=dm_l
DioException [unknown]: null
Error: HttpException: Invalid proxy configuration PROXY :0;

info Network 2023-10-16 16:01:44.062991 
Set Proxy PROXY :0;

info Network 2023-10-16 16:01:44.064864 
GET https://www.jmapinode2.cc/hot_tags?key=0b931a6f4b5ccc3f8d870839d07ae7b2&view_mode_debug=1&view_mode=null
headers:
{token: 9b84293d640a450c77386997a6d33ae9, tokenparam: 1697443304,1.5.9, user-agent: Mozilla/5.0 (Linux; Android 13; JM114514 Build/TQ1A.230205.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/114.0.5735.196 Safari/537.36, accept-encoding: gzip}
data:null

error Network 2023-10-16 16:01:44.065492 
GET https://www.jmapinode2.cc/hot_tags?key=0b931a6f4b5ccc3f8d870839d07ae7b2&view_mode_debug=1&view_mode=null
DioException [unknown]: null
Error: HttpException: Invalid proxy configuration PROXY :0;

info App Status 2023-10-16 16:01:51.922438 
Instance "AccountsPageLogic" has been created

info App Status 2023-10-16 16:01:51.922454 
Instance "AccountsPageLogic" has been initialized

info App Status 2023-10-16 16:01:53.173054 
GOING TO ROUTE /LoginPage

info Network 2023-10-16 16:01:54.291870 
Set Proxy PROXY :0;

info Network 2023-10-16 16:01:54.292820 
Set Proxy PROXY :0;

info Network 2023-10-16 16:01:54.293232 
POST https://picaapi.picacomic.com/auth/sign-in
headers:
{api-key: C69BAF41DA5ABD1FFEDC6D2FEA56B, accept: application/vnd.picacomic.com.v1+json, app-channel: 3, time: 1697443314, nonce: 45406c306bfa11ee91ce73da4300d142, signature: 8d4bef39a0b7e9eb563b1f13924fe38ea9d0df22d49ea978bb80b489f1c330d5, app-version: 2.2.1.3.3.4, app-uuid: defaultUuid, image-quality: original, app-platform: android, app-build-version: 45, Content-Type: application/json; charset=UTF-8, user-agent: okhttp/3.8.1, version: v1.4.1, Host: picaapi.picacomic.com}
data:{email: kylin_flower, password: popkill9}

error Network 2023-10-16 16:01:54.293990 
POST https://picaapi.picacomic.com/auth/sign-in
DioException [unknown]: null
Error: HttpException: Invalid proxy configuration PROXY :0;

info App Status 2023-10-16 16:01:57.007807 
CLOSE TO ROUTE /LoginPage

info Network 2023-10-16 16:01:59.301377 
Set Proxy PROXY :0;

info Network 2023-10-16 16:01:59.303468 
GET https://www.jmapinode2.cc/hot_tags?key=0b931a6f4b5ccc3f8d870839d07ae7b2&view_mode_debug=1&view_mode=null
headers:
{token: 900fb62077707c0074588e27b36cd0bc, tokenparam: 1697443319,1.5.9, user-agent: Mozilla/5.0 (Linux; Android 13; JM114514 Build/TQ1A.230205.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/114.0.5735.196 Safari/537.36, accept-encoding: gzip}
data:null

error Network 2023-10-16 16:01:59.304279 
GET https://www.jmapinode2.cc/hot_tags?key=0b931a6f4b5ccc3f8d870839d07ae7b2&view_mode_debug=1&view_mode=null
DioException [unknown]: null
Error: HttpException: Invalid proxy configuration PROXY :0;

info Network 2023-10-16 16:02:07.047514 
Set Proxy PROXY :0;

info Network 2023-10-16 16:02:07.049520 
GET https://e-hentai.org?inline_set=dm_l
headers:
{user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36}
data:null

error Network 2023-10-16 16:02:07.050346 
GET https://e-hentai.org?inline_set=dm_l
DioException [unknown]: null
Error: HttpException: Invalid proxy configuration PROXY :0;

info App Status 2023-10-16 16:02:17.800044 
Instance "CalculateCacheLogic" has been created

info App Status 2023-10-16 16:02:17.800060 
Instance "CalculateCacheLogic" has been initialized

info App Status 2023-10-16 16:02:23.381797 
GOING TO ROUTE /LogsPage

### 截图或视频

![20231016-160447](https://github.com/wgh136/PicaComic/assets/27739231/bf92ac3c-8007-440c-b14a-f113c6e76358)

**Comment by wgh136** [comment]
代理设置存在问题
这个版本移除了对代理配置的检查
之前版本对格式不正确的代理会忽略并且没有提示
修改代理设置后应该就没问题了

**Comment by wgh136** [comment]
也有可能是读取系统代理设置出现了问题
这种情况下请禁用使用系统代理

**Comment by wgh136** [comment]
看了下代码, 确实有问题, 请在设置中将"使用系统代理"关闭
```swift
    let methodChannel = FlutterMethodChannel(name: "kokoiro.xyz.pica_comic/proxy", binaryMessenger: controller.binaryMessenger)
    methodChannel.setMethodCallHandler { [weak self] (call: FlutterMethodCall, result: @escaping FlutterResult) -> Void in
      if let proxySettings = CFNetworkCopySystemProxySettings()?.takeUnretainedValue() as NSDictionary? {
        let dict = proxySettings.object(forKey: kCFNetworkProxiesHTTPProxy) as? NSDictionary
        let host = dict?.object(forKey: kCFNetworkProxiesHTTPProxy) as? String ?? ""
        let port = dict?.object(forKey: kCFNetworkProxiesHTTPPort) as? Int ?? 0
        let proxyConfig = "\(host):\(port)"
        result(proxyConfig)
      } else {
        result("")
      }
    }
```
此代码在没有系统代理时返回":0", 这东西是gpt写的, 我原以为这么简单的东西gpt应该不会出现问题
之前的版本对不正确的代理会忽略, 因此没发现这个问题

**Comment by wgh136** [comment]
将在下个版本中修复
