### ISSUE TITLE
[Enhancement]: 关于UI的一些建议

### ISSUE THREAD

**Issue by ArtMoe** [wgh136/PicaComic#219]
### 描述

1. 探索页面下，顶部导航栏无法通过触摸切换页面，只能左右滑动切换，分类页面下正常。
2. 在详细漫画块显示模式下，漫画封面显示过小，特别是在大屏iPad上显得更小，能否放大封面。
3. 能否在底部导航栏增加自定义选项，添加历史记录、下载页面。
4. 能否增加一个默认设置，点击阅读后自动继续阅读，无须弹窗确认。

### 操作系统

iOS

**Comment by wgh136** [comment]
> 探索页面下，顶部导航栏无法通过触摸切换页面，只能左右滑动切换，分类页面下正常。

似乎只有iPhone存在此问题, iPad上正常, 其它操作系统也没有问题, 将会在下个版本修复

> 在详细漫画块显示模式下，漫画封面显示过小，特别是在大屏iPad上显得更小，能否放大封面

将会进行调整

> 能否在底部导航栏增加自定义选项，添加历史记录、下载页面

不太行, 涉及的东西太多, 改起来麻烦

> 能否增加一个默认设置，点击阅读后自动继续阅读，无须弹窗确认

将会把阅读按钮改为从头开始, 在显示上次阅读位置的那个地方添加继续阅读按钮
