### ISSUE TITLE
Pica Comic 網頁版無法正常登錄

### ISSUE THREAD

**Issue by tkp206093** [wgh136/PicaComic#22]
手機版已經成功登陸
![image](https://github.com/wgh136/PicaComic/assets/29872453/d88a7733-1258-487e-a3ad-b6b3e3908467)

以及bk網頁版都能夠成功登陸
<img width="1920" alt="image" src="https://github.com/wgh136/PicaComic/assets/29872453/6c76e6f7-bb89-4067-8b47-63b85d7f4c3d">

但不知為何你們的網站會這樣
<img width="1920" alt="image" src="https://github.com/wgh136/PicaComic/assets/29872453/3cf76c73-1654-417d-aa79-1de97d4bc1e7">
不是bk的帳戶密碼嗎？

**Comment by wgh136** [comment]
已修复, 长时间没有维护导致的
如果仍然无法登录请尝试清除缓存
