### ISSUE TITLE
[Enhancement]: eh警告页面处理

### ISSUE THREAD

**Issue by onlytheworld** [wgh136/PicaComic#220]
### 描述

部分eh的页面有警告页面，如下
如链接`https://e-hentai.org/g/2708006/a70925ff28/`
<img width="638" alt="1697701750712" src="https://github.com/wgh136/PicaComic/assets/37205103/4b8ff1a3-dfee-46ff-8707-244607d61dbd">

另：该APP似乎目前被手机管家检测为不良应用
![image](https://github.com/wgh136/PicaComic/assets/37205103/4b022090-2392-471e-9933-8dd59614854e)

**Comment by wgh136** [comment]
> 部分eh的页面有警告页面

也就是说需要加一个警告页面对吧

> 该APP似乎目前被手机管家检测为不良应用

哪家的手机管家, 有点好奇, 其它同类型app也是这样的吗

**Comment by onlytheworld** [comment]
> 也就是说需要加一个警告页面对吧
对，需要点view gallery或者点不再提醒
> 哪家的手机管家, 有点好奇, 其它同类型app也是这样的吗
华为，这个可以忽略，我下别的应用也容易有这种提示，不知道他怎么检测出来的。。。
