### ISSUE TITLE
[Bug]: eh的本子下载问题

### ISSUE THREAD

**Issue by NiuXZi** [wgh136/PicaComic#221]
### 描述

昨天还能下eh的本子，没下完，今天重启电脑就不能下了，一直显示错误，但直接看本子不受影响。

### Version

latest

### 使用的操作系统

Windows

**Comment by NiuXZi** [comment]
刚刚试了试，重新找本新的下载，也可以下载。。

**Comment by wgh136** [comment]
对于eh, 获取图片需要showkey和imgKey, 这两个值是临时的, 
app在下载的时候, 仅在开始下载的时候获取这两个值, 估计是因为这两个值过期了导致无法下载

**Comment by wgh136** [comment]
将在下个版本修复
