### ISSUE TITLE
[Bug]: 使用哔咔转发服务器后这样

### ISSUE THREAD

**Issue by TheStoryNeverEnd** [wgh136/PicaComic#223]
### 描述

Error: SocketException: Connection reset by
peer(OS Error: Connection reset by peer, errno
= 104), address = api.kokoiro.xyz, port =
49146

### Version

latest

### 使用的操作系统

Android

### 截图或视频

![B75C38DC38E06CC82890D9ACAA6CF6E9](https://github.com/wgh136/PicaComic/assets/140722613/bf802b65-a66d-4680-ad91-19538b720a7c)

**Comment by wgh136** [comment]
服务器运行正常, 这个是你的网络问题
