### ISSUE TITLE
[Bug]: exh无法查看收藏内容

### ISSUE THREAD

**Issue by lianyanjiajia** [wgh136/PicaComic#226]
### 描述

升级到最新后exh无法查看收藏内容，升级前正常

### Version

latest

### 使用的操作系统

Android

### 截图或视频

![Screenshot_20231024-232204](https://github.com/wgh136/PicaComic/assets/30580881/94b8bcb5-90bd-4539-be36-8e1471c6d6b2)

**Comment by wgh136** [comment]
你应该是使用的账号密码登录，app没拿到cookie的igneous字段

请使用cookie登录，下个版本将修复此问题

另外请把你发的logs删掉，里面有你的cookie信息，我现在使用的是手机，不方便操作

**Comment by lianyanjiajia** [comment]
已经改成coockie登录了 igneous字段也输入了

**Comment by wgh136** [comment]
仍然不行？其它地方是否正常

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by lianyanjiajia** [comment]
显示的图库好像也不对，显示的好像是eh的图库不是exh的图库，我exh设置里只显示同人，不会有这么多cg
![Screenshot_20231024-235928](https://github.com/wgh136/PicaComic/assets/30580881/122d0e03-1cfa-4d7a-8410-ac429543e59e)

**Comment by wgh136** [comment]
上个版本是正常的对吧，那我就直接把eh网络相关代码回滚到上个版本

________________________________

**Comment by lianyanjiajia** [comment]
我刚才重新安装了2.2版本 exh的封面 内容 收藏都正常了

**Comment by lianyanjiajia** [comment]
2.3 切换到eh源 内容虽然不对，但是可以看收藏
![Screenshot_20231025-002135_Pica_Comic](https://github.com/wgh136/PicaComic/assets/30580881/b2d1cf13-b34a-499b-9c9c-48ce567b85c2)
![Screenshot_20231025-002121_Pica_Comic](https://github.com/wgh136/PicaComic/assets/30580881/52603139-56c3-4316-aea8-7ff6b9c9f1a4)
![Screenshot_20231025-002151_Pica_Comic](https://github.com/wgh136/PicaComic/assets/30580881/c6a7ca57-96d8-48b1-81b8-32f4db960e79)
