### ISSUE TITLE
禁漫登陆错误

### ISSUE THREAD

**Issue by Chilianxin** [wgh136/PicaComic#228]
the request returned an invalid status code of 301

试了很久应该不是网络或者官方问题，官方app登陆也没问题

**Comment by wgh136** [comment]
![Screenshot_20231025-184244_JMComic2](https://github.com/wgh136/PicaComic/assets/67669799/c0f79434-cf79-42ca-8078-5706be790a73)
我这里官方app完全无法使用

**Comment by wgh136** [comment]
现在应该没问题了

**Comment by Chilianxin** [comment]
> 现在应该没问题了

还是不行，官方app一直能登陆，

**Comment by wgh136** [comment]
分流2没问题
我没用日本节点, 官方app也是只有分流2可以用

**Comment by wzgrx** [comment]
+1还是登录不了，显示301

**Comment by wgh136** [comment]
登录以外的东西有问题吗

**Comment by wzgrx** [comment]
> 登录以外的东西有问题吗

jm的都显示301

**Comment by Chilianxin** [comment]
现在又可以了，不知道怎么回事

**Comment by wzgrx** [comment]
可以登录了
