### ISSUE TITLE
2.2.2及2.2.3版本都出现类似FormatException

### ISSUE THREAD

**Issue by zhuhewei** [wgh136/PicaComic#229]
![微信图片_20231026111845](https://github.com/wgh136/PicaComic/assets/19264066/97d74a7c-b70e-4c0c-ac32-b1ad461d244f)

**Comment by wgh136** [comment]
这是禁漫的问题, 请切换分流

**Comment by zhuhewei** [comment]
切换分流无效

**Comment by wgh136** [comment]
发日志

**Comment by zhuhewei** [comment]
done!我按日志分析了一下，切换了api接口分流和图片分流

**Comment by zhuhewei** [comment]
多谢
