### ISSUE TITLE
近期的一些问题

### ISSUE THREAD

**Issue by jogGUY** [wgh136/PicaComic#23]
1. 哔咔的相关推荐没有了，但是我账号都4级了，这是哔咔本身的问题么？
2. [这个项目](https://github.com/niuhuan/jenny)的本子展示方式挺有意思的，那个分页浏览实现起来简单么？考不考虑做一下那个展示方式？
3. 最近一段时间禁漫老是超时，非常恼火，于是我在想：[这个项目](https://github.com/tonquer/jmcomic-qt)的分流设置那里有个“启用DoH”的设置，假如本项目也把这个功能做进来对改善禁漫的访问是否有帮助？更进一步的，DoH技术是否对哔咔有用？
4. 考虑将”添加绅士漫画“加入长期计划吗？
5. 现在开着的两个enhancement的issue或许可以放进Projects？

**Comment by wgh136** [comment]
1. 是的, 我在readme.md里面写了
2. 不难实现, 但问题是现在主界面已经够复杂了, 数据量很大, 之后还需要添加其它的漫画源, 实现这个方式将导致主界面过于复杂
3. 由于dart的限制, 无法直接实现. 当然, 可以通过调用原生平台代码方式实现, 但这样工作量非常大. 我更建议使用可靠的vpn服务
4. 可以有
5. 两个issue实际上均已进入后期阶段, 剩下的工作量不大

**Comment by jogGUY** [comment]
> 1. 是的, 我在readme.md里面写了
> 2. 不难实现, 但问题是现在主界面已经够复杂了, 数据量很大, 之后还需要添加其它的漫画源, 实现这个方式将导致主界面过于复杂
> 3. 由于dart的限制, 无法直接实现. 当然, 可以通过调用原生平台代码方式实现, 但这样工作量非常大. 我更建议使用可靠的vpn服务
> 5. 两个issue实际上均已进入后期阶段, 剩下的工作量不大

没看readme，我的🤦

对于第二点，意思就是说，出于减小代码复杂程度和统一UI的考虑，不会再更改显示方式咯？

对于第三点，意思是说，添加”启用DoH“功能对本项目过于复杂/困难咯？这个也不强求，有最好，没有也行，主要还是想了解一下使用DoH对登上哔咔和禁漫这个点子是不是真的有用。至于梯子的话，目前需求量不是特别大，所以我会先想想普通的上网方式 o(*￣▽￣*)o

对于第五点，主要是看到禁漫的那个issue回复太多了所以我这么说，这还是我开的坏头🤦‍♂️

**Comment by wgh136** [comment]
关于第二点, 目前的显示方式是必须要更改的, 更新到v1.6.0后你会发现手机端底部导航栏已经没有多余的空间了
也就是说, 如果要进一步整合其它的漫画源, 主界面的ui必须进行调整
但我还没想好使用哪种显示方式

关于第三点, 是的, 很困难, 必须放弃现有的网络请求代码, 转而使用原生代码实现
dart-lang仓库里面关于这个的isuue早在2019年就已经打开了, 但到现在都没有进展

**Comment by jogGUY** [comment]
关于UI的问题，我想到的是：

1. 比如说我不看E-Hentai，我能不能把它隐藏了？
2. 假如我看的漫画源有很多，是不是可以把不同的漫画源UI做成能够滑动选择的形式？比如说，现在底下的UI做成能够左右滑动的
3. 或许可以把“我”这个栏目放到搜索/排行/设置的那里？

**Comment by wgh136** [comment]
感谢建议，等整合下一个漫画源的时候再决定

________________________________

**Comment by jogGUY** [comment]
对了，Tachiyomi的“浏览”-“图源”这种展示方式不知道有没有参考价值？

**Comment by wgh136** [comment]
有参考价值

________________________________
