### ISSUE TITLE
[Bug]: 禁漫天堂无法连接

### ISSUE THREAD

**Issue by soha12** [wgh136/PicaComic#231]
### 描述

探索里，开梯子情况下，禁漫天堂账号登录显示：
the request returned an invalid status code of 301.
禁漫主页显示：
the request returned an invalid status code of 404
分类里显示403
关梯子后，禁漫主页还是404
分类显示连接时间过长，connnection took too longer than 0:00:08

正常开梯子，手机浏览器是可以进去禁漫的
目前ehentai和bika账号都可以正常登录并浏览
下载版本2.2.3 app-arm64-v8a-release.apk

### Version

latest2.2.3

### 使用的操作系统

Android

**Comment by wgh136** [comment]
禁漫的问题, 换分流, 我试了下, 分流2是正常的

**Comment by soha12** [comment]
> 禁漫的问题, 换分流, 我试了下, 分流2是正常的

确实可以了，没注意到分流选项(
感谢

**Comment by purepoorx** [comment]
> 禁漫的问题, 换分流, 我试了下, 分流2是正常的

**Comment by liguichase** [comment]
> 禁漫的问题, 换分流, 我试了下, 分流2是正常的

现在所有分流点进去都是一个漫画了

**Comment by wgh136** [comment]
别急, 再观察一下, 最近禁漫的服务器很不稳定

**Comment by wgh136** [comment]
更新至v2.2.4试试

**Comment by wgh136** [comment]
由于没有回复, 认为已完成
