### ISSUE TITLE
[Bug]: nhentai登录不了

### ISSUE THREAD

**Issue by TrappedCrow** [wgh136/PicaComic#232]
### 描述

在nhentai登录时，在账号密码正确的情况下，还是无法登录，一直显示错误，而且我在网页版登录发现也有server报错500的奇怪问题，不知道是不是n站的问题

### Version

2.1.2

### 使用的操作系统

Windows

**Comment by wgh136** [comment]
nhentai的登录是使用webview实现的, 和你使用浏览器登录没有区别
我试了下, 没有问题

**Comment by wordly123** [comment]
> nhentai的登录是使用webview实现的, 和你使用浏览器登录没有区别
> 我试了下, 没有问题

网页无法打开
位于 blob:https://nhentai.net/9d342b77-0602-414f-91a3-fa2531d52536 的网页无法加载，因为：

net::ERR_FILE_NOT_FOUND

我在安卓app上点安全挑战直接显示这个

**Comment by wgh136** [comment]
安卓上确实存在问题，此问题会在下个版本修复

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
