### ISSUE TITLE
禁漫天堂图文不对

### ISSUE THREAD

**Issue by wordly123** [wgh136/PicaComic#233]
### 描述

![Screenshot_20231027_230936](https://github.com/wgh136/PicaComic/assets/21117763/1a52c188-28e4-49cd-b8b4-7a77bae3978e)
无论是那个本子点开都是这个标题这个上传者这个些tag 

### Version

latest

### 使用的操作系统

Android

### 截图或视频

![Screenshot_20231027_230936.jpg](https://github.com/wgh136/PicaComic/assets/21117763/49c0723d-90fa-4279-9d5b-8b36c6a460ea)

**Comment by wgh136** [comment]
等禁漫服务器稳定了再尝试修复

**Comment by wgh136** [comment]
用了一上午时间找问题, 结果发现把UA中的设备型号给换掉就好了
原来的UA是`"Mozilla/5.0 (Linux; Android 13; JM114514 Build/TQ1A.230205.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/114.0.5735.196 Safari/537.36"`, 我把设备型号设置为了JM114514
将其替换为任意字符串就能正常加载了🤣
