### ISSUE TITLE
自动下一页

### ISSUE THREAD

**Issue by yaozi520be** [wgh136/PicaComic#235]
左下角下一页按钮，ViewId为空，无法识别，能否加下文字，方便配合大圣净化完成自动下一页操作。
谢谢。
![IMG_20231028_185301.jpg](https://github.com/wgh136/PicaComic/assets/13406523/1fa4546e-8ba1-4260-87b0-1028662411f7)

**Comment by wgh136** [comment]
ViewId是Android原生开发的东西, 本项目是flutter app, 无法控制这个
这个是下一章节的按钮吧, 你希望自动下一章节的触发条件是什么

**Comment by yaozi520be** [comment]
本来想滑到底出现下一章按钮就自动点击的，可惜没按钮没标识，如果能像谜妹那样无缝下一章那就更好了，如果能实现方便的话就加下，谢谢。
开发不易，建议设置页面底部加个发电连接，方便支持下。

**Comment by wgh136** [comment]
> 滑到底出现下一章按钮就自动点击

这样容易误触发, 可能最后一页还没看完就自动下一章节了

> 无缝下一章

现在的阅读器代码结构造成难以实现无缝下一章, 等哪天我有时间了可以改一下

> 加个发电连接

感谢支持
先在Github项目首页放上了ko-fi的链接, 有能力且有支付方式可以支持一下

**Comment by wgh136** [comment]
现在可以通过手势切换到下一章节: https://wgh136.github.io/posts/2
是否可以认为此问题得到解决?

**Comment by wgh136** [comment]
由于没有回复, 默认已解决
