### ISSUE TITLE
[Enhancement]: 设置选项查询

### ISSUE THREAD

**Issue by GeekerBug** [wgh136/PicaComic#236]
### 描述

是否能在设置页面添加一个查询设置条目

之前有一次想要调节图片预加载找了半天没找到）

**Comment by wgh136** [comment]
似乎不小心把图片预加载设置给删了, 这个原本是在设置页面里面的阅读板块, 因为阅读器里面有设置, 感觉意义不大, 就把阅读设置从设置页面里面移除了, 忘了阅读器里面的设置没有图片预加载选项

**Comment by wgh136** [comment]
没什么必要
