### ISSUE TITLE
捐赠不了

### ISSUE THREAD

**Issue by yanguiSV0** [wgh136/PicaComic#239]
### Content

我并没有那种银行卡，或者你可以弄个支付宝或者微信码来，我捐赠给你

**Comment by wgh136** [comment]
支付宝账号是我的邮箱`nyne19710@proton.me`
感谢

**Comment by yanguiSV0** [comment]
> 支付宝账号是我的邮箱`nyne19710@proton.me` 谢谢

添加你好友了，你看看有没有收到好友信息，确认一下，我再转你
