### ISSUE TITLE
阅读方式有点问题

### ISSUE THREAD

**Issue by qa12587** [wgh136/PicaComic#24]
我下划漫画停一下这个就老是显示，能否改为双击显示
![IMG_20230513_224315](https://github.com/wgh136/PicaComic/assets/116661799/2a15d09d-2e6b-4cb9-8f69-11c668675572)

**Comment by wgh136** [comment]
可以，将在下个版本进行调整

________________________________
From: qa12587 ***@***.***>
Sent: Saturday, May 13, 2023 10:47:41 PM
To: wgh136/PicaComic ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [wgh136/PicaComic] 阅读方式有点问题 (Issue #24)


我下划漫画停一下这个就老是显示，能否改为双击显示
[IMG_20230513_224315]<https://user-images.githubusercontent.com/116661799/238140341-2a15d09d-2e6b-4cb9-8f69-11c668675572.jpg>

―

**Comment by wgh136** [comment]
已完成
