### ISSUE TITLE
[Enhancement]: 搜索功能要点一次搜索栏进去才能搜索好不方便

### ISSUE THREAD

**Issue by gankumangcao** [wgh136/PicaComic#240]
### 描述

搜索栏可以改回原来的吗原来那个方便些，原来的在搜索栏填好直接搜方便多，选搜哪个源的也方便，现在要退出来才能选源 要搜很多个本也不方便，发的两张图第一张是点左下角搜索功能出来的界面，第二张是点搜索栏后的界面

### 操作系统

Windows

### 图片

![图像 2023-10-30 13-01](https://github.com/wgh136/PicaComic/assets/85823141/8e59e296-78ca-4253-93b8-957688eec07a)
![图像 2023-10-30 13-02](https://github.com/wgh136/PicaComic/assets/85823141/2e051469-0464-45b0-98a9-ad06ac74fffb)

**Comment by wgh136** [comment]
将会进行调整
________________________________
From: gankumangcao ***@***.***>
Sent: Monday, October 30, 2023 1:05:26 PM
To: wgh136/PicaComic ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [wgh136/PicaComic] [Enhancement]: 搜索功能要点一次搜索栏进去才能搜索好不方便 (Issue #240)


描述

搜索栏可以改回原来的吗原来那个方便些，原来的在搜索栏填好直接搜方便多，选搜哪个源的也方便，现在要退出来才能选源 要搜很多个本也不方便，发的两张图第一张是点左下角搜索功能出来的界面，第二张是点搜索栏后的界面

操作系统

Windows

图片

[图像 2023-10-30 13-01]<https://user-images.githubusercontent.com/85823141/278944025-8e59e296-78ca-4253-93b8-957688eec07a.png>
[图像 2023-10-30 13-02]<https://user-images.githubusercontent.com/85823141/278944034-2e051469-0464-45b0-98a9-ad06ac74fffb.png>

―
