### ISSUE TITLE
[Enhancement]: 能否提供程序语言更改选项？

### ISSUE THREAD

**Issue by Meonthb** [wgh136/PicaComic#243]
### 描述

Windows端习惯用英文系统，但这个app英文界面不太完善，因此希望能在使用英文系统的同时让PicaComic显示中文界面。

**Comment by wgh136** [comment]
可以
英文界面确实不完善, 因为做起来麻烦, 并且没有多少英文用户

**Comment by Meonthb** [comment]
感谢
