### ISSUE TITLE
[Bug]: 禁漫漫画图片数量获取错误

### ISSUE THREAD

**Issue by yezechuandl** [wgh136/PicaComic#244]
### 描述

观看禁漫资源，最后几页老是出现Exception:Failed to decode image: Data length is 0 bytes的报错

### Version

latest

### 使用的操作系统

Android

**Comment by wgh136** [comment]
对比了一下官方app, 发现本app的显示的图片数量比官方app多, 也就是说最后几页是不存在的, 因此加载出错

**Comment by yezechuandl** [comment]
> 对比一下显示官方app，发现本app的图片数量比官方app多，说明最后几页是不存在的，因此出现错误

我也发现了，多了不止一点，这个能修复吗，下一章还得划到底或者退出重选。

**Comment by yezechuandl** [comment]
> 对比一下显示官方app，发现本app的图片数量比官方app多，说明最后几页不存在的，因此出现错误

那这个能修复吗，刚开始还以为是节点问题

**Comment by wgh136** [comment]
下个版本修复

**Comment by yezechuandl** [comment]
> 下个版本修复

还有个问题，就刚才发生的，我切换后台后，再回到应用，图片划不动了，阅读模式是上下连续，但是菜单是可以呼出来的。必须重新选章节才能滑动

**Comment by wgh136** [comment]
> > 下个版本修复
> 
> 还有个问题，就刚才发生的，我切换后台后，再回到应用，图片划不动了，阅读模式是上下连续，但是菜单是可以呼出来的。必须重新选章节才能滑动

我大概知道哪里出了问题, 但不确定, 会在下个版本修改, 如果更新到下个版本后仍然有问题, 请再次告诉我

**Comment by wgh136** [comment]
大概是禁漫针对第三方APP做出的操作: 对仍然按照旧版本接口进行的请求一定概率会返回错误数据
对新版本官方app抓包并调整项目代码后, 我没再遇到这种情况了
应该是修好了, 讨厌概率问题

**Comment by yezechuandl** [comment]
> 大概是禁漫针对第三方APP做出的操作: 对仍然按照旧版本接口进行的请求一定概率会返回错误数据 对新版本官方app抓包并调整项目代码后, 我没再遇到这种情况了 应该是修好了, 讨厌概率问题

那岂不是有的折腾了｜д•´)!!

**Comment by wgh136** [comment]
> > 大概是禁漫针对第三方APP做出的操作: 对仍然按照旧版本接口进行的请求一定概率会返回错误数据 对新版本官方app抓包并调整项目代码后, 我没再遇到这种情况了 应该是修好了, 讨厌概率问题
> 
> 那岂不是有的折腾了｜д•´)!!

禁漫是这样的, 一直在修改接口, 哔咔就很稳定
