### ISSUE TITLE
[Enhancement]: 搜索界面改善建议

### ISSUE THREAD

**Issue by A99011** [wgh136/PicaComic#247]
### 描述

清除历史按钮对于部分使用虚拟按键手机来说会太低与按键重合按不到（在已经搜索的词条太多的情况下）

在搜索框有内容的情况下推荐词条会覆盖主搜索界面导致无法修改目标站点，按返回键会直接回到主界面（希望可以改为半屏单击其他地方可以取消推荐词条，或者按返回键会隐藏搜索词条推荐直至点击搜索框）

### 操作系统

Android

**Comment by wgh136** [comment]
了解了

**Comment by wgh136** [comment]
下个版本会添加一个关闭按钮, 并且优化显示逻辑
![image](https://github.com/wgh136/PicaComic/assets/67669799/c21520fb-5f17-4775-8630-0dc5963fc9b9)

**Comment by A99011** [comment]
感谢（○｀ 3′○）



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年11月6日(周一) 晚上10:11
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [wgh136/PicaComic] [Enhancement]: 搜索界面改善建议 (Issue #247)




 
下个版本会添加一个关闭按钮, 并且优化显示逻辑
