### ISSUE TITLE
[Enhancement]: 希望添加一个收藏标签的功能

### ISSUE THREAD

**Issue by opaiopaio** [wgh136/PicaComic#248]
### 描述

希望能提供一个收藏标签的功能用来收藏自己喜欢的作者或者本子类型的tag，像现在的收藏夹一样

**Comment by opaiopaio** [comment]
还有就是tag的跳转，nh如果在本子里点击作者他会搜索“****（作者名）”而不是nhbooks的tag格式“Artist:****（作者名）”，会出现一堆乱七八糟的搜索内容

**Comment by opaiopaio** [comment]
能不能给收藏夹添加一个标签收藏的页面啊，在搜索栏里这个标签太容易误触了😭，我浏览器收藏作者页面一次要几百个，放在搜索页面里面会堆的满满一堆

**Comment by wgh136** [comment]
> 能不能给收藏夹添加一个标签收藏的页面啊，在搜索栏里这个标签太容易误触了😭，我浏览器收藏作者页面一次要几百个，放在搜索页面里面会堆的满满一堆

放收藏夹里面感觉不太好, 在搜索页面加一个按钮, 点击后显示收藏的标签怎么样

**Comment by opaiopaio** [comment]
还是希望可以单独添加一个页面，最好能有排序分类的功能，但是现在也算勉强够用了。大佬能不能把收藏页面的布局改一下，我网络收藏用的比较多，现在点进去第一眼是空荡荡的本地收藏夹。
