### ISSUE TITLE
[Enhancement]: 关键词屏蔽对禁漫不生效

### ISSUE THREAD

**Issue by Kamho-github** [wgh136/PicaComic#249]
### 描述

实在不懂jm官App为何不做tag屏蔽
时不时就冒出来几个大只佬

### 操作系统

Android

**Comment by wgh136** [comment]
因为做不到, 禁漫的漫画列表数据没有tag, 只能根据标题和作者进行屏蔽

**Comment by wgh136** [comment]
你可以去给禁漫官方提意见, 让他们加上

**Comment by Kamho-github** [comment]
> 因为做不到, 禁漫的漫画列表数据没有tag, 只能根据标题和作者进行屏蔽

取回数据再做本地筛选屏蔽如何？至少能不看到

**Comment by Kamho-github** [comment]
或者直接ID黑名单屏蔽吧，长按加入黑名单。禁漫重复上传还是比较少的

**Comment by wgh136** [comment]
你可以直接屏蔽漫画名的一部分, 这是判断是否屏蔽的代码
```dart
    bool block = false;
    for(var key in appdata.blockingKeyword){
      block = block || name.contains(key) || author==key || tags.contains(key);
    }
    if(block){
      throw Error();
    }
```

**Comment by Kamho-github** [comment]
> 你可以直接屏蔽漫画名的一部分, 这是判断是否屏蔽的代码
> 
> ```dart
>     bool block = false;
>     for(var key in appdata.blockingKeyword){
>       block = block || name.contains(key) || author==key || tags.contains(key);
>     }
>     if(block){
>       throw Error();
>     }
> ```

好的谢谢，我自个去琢磨吧。
说实话不是很想直接按作者和标题去屏蔽，因有些作者可能会起奇奇怪怪的名称和标题，有可能会误伤
