### ISSUE TITLE
隐藏入口

### ISSUE THREAD

**Issue by MarkChan0225** [wgh136/PicaComic#25]
建议加一个设置可以隐藏自己不想要的平台 现在的介面太复杂了

**Comment by wgh136** [comment]
可以

________________________________
From: MarkChan0225 ***@***.***>
Sent: Saturday, May 13, 2023 11:19:55 PM
To: wgh136/PicaComic ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [wgh136/PicaComic] 隐藏入口 (Issue #25)


建议加一个设置可以隐藏自己不想要的平台 现在的介面太复杂了

―

**Comment by wgh136** [comment]
已完成
