### ISSUE TITLE
已下载的漫画阅读问题[Bug]: 

### ISSUE THREAD

**Issue by newbe007** [wgh136/PicaComic#251]
### 描述

阅读已下载的漫画时使用从上往下连续，没翻一页都会卡顿一下

### Version

latest

### 使用的操作系统

Android

**Comment by wgh136** [comment]
猜测是设备性能太弱或者性能被其它程序占用导致读取图片的速度跟不上翻页速度

**Comment by newbe007** [comment]
,

**Comment by newbe007** [comment]
同一个漫画，章节页数很多上千页的话会卡顿，章节页数就几十页的话不会卡顿。希望作者大大可以优化一下

**Comment by wgh136** [comment]
设备信息可以提供一下吗, 我这里没有出现任何的卡顿

**Comment by suppermanzero** [comment]
> 设备信息可以提供一下吗, 我这里没有出现任何的卡顿

这个情况我也遇到过，不过是改了下载路径后才卡顿的，用软件默认的路径下载多少页的漫画都可以流程看，改到其它路径后再点进去浏览滑动时就会一卡一卡的
