### ISSUE TITLE
[Bug]: windows端使用nhbooks源进行安全验证和登录账户的时候webview白屏

### ISSUE THREAD

**Issue by opaiopaio** [wgh136/PicaComic#253]
### 描述

在设置代理处设置代理就打不开 关掉就能加载出来 ，但是不设置代理本子加载不出来

### Version

latest

### 使用的操作系统

Windows

**Comment by wgh136** [comment]
app设置中的代理与webview没有任何关系
webview是系统给的

**Comment by wgh136** [comment]
由于缺少信息, 无法解决
