### ISSUE TITLE
[Enhancement]: 希望新增长按放大功能，按住同时手指移动可转移查看区域

### ISSUE THREAD

**Issue by bearcloney** [wgh136/PicaComic#254]
### 描述

希望能新增个长按放大的功能，按住的同时手指轻微移动可以转移查看区域放大倍率自定（每个平台）
这个功能对单手使用非常友好，因为有些漫画的文字太小了，加上大多用户都是用手机，因此我觉的很有必要
可以参考NeeView（PC）或者 可达漫画（ios）他们都有类似的功能
希望大佬能采纳

对了，在双页模式下双击放大不起作用应该是个bug，姑且提一下

### 图片

https://github.com/wgh136/PicaComic/assets/51289114/681e0ba9-972b-4710-ac42-c65d82c8e356

**Comment by Deskfrest** [comment]
很好的建议，有的汉化版字体确实太小了，手机端看着很费劲

**Comment by wgh136** [comment]
完成

**Comment by bearcloney** [comment]
> 完成好快的speed 大佬牛逼，不过我刚刚试了下，好像放大后移动图像需要在屏幕上滑动距离挺远的（在可达上基本手指只要在按下去的2cmX3cm区域内滑动就能显示到画布的上下左右了）
