### ISSUE TITLE
[Bug]: 绅士漫画是不是不能网络收藏

### ISSUE THREAD

**Issue by TrappedCrow** [wgh136/PicaComic#255]
### 描述

本地收藏不受影响，但是没有办法网络收藏，网络收藏的时候也没有发现报错，不知道是哪里的问题

### Version

latest

### 使用的操作系统

Windows

**Comment by wgh136** [comment]
我没问题，你是不是改了绅士漫画的域名，是的话把你用的域名发一下

**Comment by TrappedCrow** [comment]
域名就是www.wnacg.com，我用这个域名能正常访问，是这个的问题吗

**Comment by wgh136** [comment]
这就是app默认的域名，我没遇到问题

________________________________

**Comment by TrappedCrow** [comment]
已经解决了，是没有新建一个收藏夹的原因
