### ISSUE TITLE
[Bug]: ehviewer关闭内容警告后依然无法查看重口本

### ISSUE THREAD

**Issue by SaiKaede36** [wgh136/PicaComic#260]
### 描述

在漫画源关闭ehviewer的忽略警告后依然无法查看重口本内容

### Version

latest

### 使用的操作系统

Android

### 日志

Bugs

### 截图或视频

![Uploading Screenshot_20231118_032744_edit_367119796038808.jpg…]()

**Comment by wgh136** [comment]
给个画廊链接或者画廊名

**Comment by wgh136** [comment]
由于缺少信息, 无法解决
