### ISSUE TITLE
希望下载后的文件夹能显示原本标题名称[Enhancement]: 

### ISSUE THREAD

**Issue by sparrow970** [wgh136/PicaComic#262]
### 描述/Description

现在下载的文件夹名称是一串数字，在本软件里正常显示，但在第三方软件里不方便查看
希望下载后的本地文件夹能显示原本标题名称，搭配第三方相册软件更方便，如quickpic软件

### 操作系统/Operating System

Android

**Comment by wgh136** [comment]
不太行
那串字符是漫画的唯一ID, 用于识别漫画, 改成漫画标题将会面临很多问题, 比如旧数据的兼容性问题, 名称冲突问题, 特殊字符问题
太麻烦, 不想做
