### ISSUE TITLE
漫画详情页创建收藏报错

### ISSUE THREAD

**Issue by yezechuandl** [wgh136/PicaComic#263]
### 描述/Description

又来反馈问题啦，随便创建个标签出现Bad state:Type with tag me page Not Four，文件夹是创建出来了，在我的那里创建就没问题，更新最新版出现的问题，之前都没有。

### Version

latest

### 使用的操作系统/Operating system

Android

**Comment by wgh136** [comment]
这个是尝试更新"我"页面时出现了问题, 由于对"我"页面做了些修改, 导致出现此情况
能用就不着急修

**Comment by yezechuandl** [comment]
> 这个是尝试更新"我"页面时出现了问题, 由于对"我"页面做了些修改, 导致出现此情况 能用就不着急修

嗯，没有影响

**Comment by wgh136** [comment]
已修复, 并且重新上传了安装包, 重新安装v2.2.7以解决此问题
此问题导致在部分情况下无法保存数据
