### ISSUE TITLE
禁漫全分流无法正常登录，不同分流不同报错，405 ，403，网络错误

### ISSUE THREAD

**Issue by sakuraMY** [wgh136/PicaComic#266]
### Content

app内无法登录，官网登录正常
Set Proxy null 分流1

FormatException: Unexpected extension byte (at offset 3)
#0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1748)
#1      Utf8Decoder.convert (dart:convert/utf.dart:356)
#2      JmNetwork.convertData (package:pica_comic/network/jm_network/jm_main_network.dart:67)
#3      JmNetwork.post (package:pica_comic/network/jm_network/jm_main_network.dart:132)
<asynchronous suspension>
#4      JmNetwork.login (package:pica_comic/network/jm_network/jm_main_network.dart:591)
<asynchronous suspension>
#5      _JmLoginPageState.build.<anonymous closure> (package:pica_comic/views/jm_views/jm_login_page.dart:76)
<asynchronous suspension>

POST https://www.jmapinode2.top/login
DioException [bad response]: The request returned an invalid status code of 403.
分流2

FormatException: Missing extension byte (at offset 2)
#0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1748)
#1      Utf8Decoder.convert (dart:convert/utf.dart:356)
#2      JmNetwork.convertData (package:pica_comic/network/jm_network/jm_main_network.dart:67)
#3      JmNetwork.post (package:pica_comic/network/jm_network/jm_main_network.dart:132)
<asynchronous suspension>
#4      JmNetwork.login (package:pica_comic/network/jm_network/jm_main_network.dart:591)
<asynchronous suspension>
#5      _JmLoginPageState.build.<anonymous closure> (package:pica_comic/views/jm_views/jm_login_page.dart:76)
<asynchronous suspension>分流3

等等不同报错......

**Comment by wgh136** [comment]
看 #267
