### ISSUE TITLE
[Bug]: 已下载漫画消失

### ISSUE THREAD

**Issue by newbe007** [wgh136/PicaComic#268]
### 描述/Description

已下载的漫画在下载页面突然不现实，但内存占用还在

### Version

latest

### 使用的操作系统/Operating system

Android

**Comment by wgh136** [comment]
所有都不显示还是单独某个

**Comment by newbe007** [comment]
全都不显示了，jm分流都不能用了，这两个问题一起出现的

**Comment by wgh136** [comment]
如果是卡在加载中, 请到设置中查看日志, 然后发给我
如果没有显示加载中, 检查一下设置中的下载路径是否正确
jm的问题看 #267
