### ISSUE TITLE
欢迎提供建议和bug反馈

### ISSUE THREAD

**Issue by wgh136** [wgh136/PicaComic#27]
# 关于功能建议
无论多么细微的建议都可以提出
不保证采纳, 但我会积极考虑

# 关于bug反馈
需要详细描述如何触发, 设备信息
只有成功复现问题, 我才能尝试解决
请尽量单独提一个issue, 而不是在其它issue下回复, 除非反馈的是同一个问题

**Comment by monkeen** [comment]
禁漫天堂搜索显示403
![Uploading Screenshot_2023-06-13-22-59-12-110_com.kokoiro.xyz.pica_comic.jpg…]()

**Comment by wgh136** [comment]
> 禁漫天堂搜索显示403

禁漫对搜索接口进行了一些修改, 明天修

**Comment by Smile8848** [comment]
哔咔漫画可以长按复制本子名吗？每次都要按住然后点全选怪麻烦的。

**Comment by wgh136** [comment]
你连续点标题3下就全选了，然后再点复制

________________________________

**Comment by wgh136** [comment]
> ios好像不能手动清除缓存

忘写了, 下个版本补上

**Comment by llstsdfg** [comment]
佬，有时候会直接卡死，不知道是不是我操作不当，因为看e有些ip不能用，然后一直换，换到能用的ip看漫画点进去会直接卡住，经常性的，卡住返回桌面挂后台再点进去软件就直接黑了，vpn网络很正常

**Comment by wgh136** [comment]
@llstsdfg 进入阅读器时卡死？只有eh吗
请单独开一个issue描述下情况，最好提供设备信息

**Comment by llstsdfg** [comment]
> 佬，有时候会直接卡死，不知道是不是我操作不当，因为看e有些ip不能用，然后一直换，换到能用的ip看漫画点进去会直接卡住，经常性的，卡住返回桌面挂后台再点进去软件就直接黑了，vpn网络很正常

现在没换ip开了vpn正常看e，然后随便在搜索栏搜作者，往下划就直接卡死了，现在一直这样，就e绅士的搜索栏搜作者有这问题，其他都很正常

**Comment by wgh136** [comment]
> > 佬，有时候会直接卡死，不知道是不是我操作不当，因为看e有些ip不能用，然后一直换，换到能用的ip看漫画点进去会直接卡住，经常性的，卡住返回桌面挂后台再点进去软件就直接黑了，vpn网络很正常
> 
> 现在没换ip开了vpn正常看e，然后随便在搜索栏搜作者，往下划就直接卡死了，现在一直这样，就e绅士的搜索栏搜作者有这问题，其他都很正常

我试了下，似乎是不断重复发送网络请求，设备性能不够就崩了，下个版本进行修复
目前在设置中切换到分页浏览就可以正常访问了

**Comment by Smile8848** [comment]
能不能看完之后能自动退出到详情页

**Comment by kongmingtang** [comment]
能不能简化一下分流.每次换分流很麻烦😀

**Comment by wgh136** [comment]
@kongmingtang 请具体一点
目前是在设置中切换分流, 为什么麻烦, 如何简化

**Comment by kongmingtang** [comment]
有些漫画这个分流看，他刷不出来，我只能去设置换分流，你在阅读界面的设置中添加切换分流发自我的手机-------- 原始邮件 --------发件人： wgh136 ***@***.***>日期： 2023年7月14日周五 14:03收件人： wgh136/PicaComic ***@***.***>抄送： kongmingtang ***@***.***>, Mention ***@***.***>主    题： Re: [wgh136/PicaComic] 欢迎提供建议和bug反馈 (Issue #27)
@kongmingtang 请具体一点
目前是在设置中切换分流, 为什么麻烦, 如何简化

**Comment by kongmingtang** [comment]
能增加一个定期清理缓存，或者退出就清理缓存，的选项

**Comment by imgblz** [comment]
下载本子全选下载发现所有的都是第一章

**Comment by wgh136** [comment]
> 下载本子全选下载发现所有的都是第一章

应该是上次更新重构漫画详情页面时改错了，会进行修复

**Comment by wolo2603** [comment]
能增加一个一次显示双页的漫画阅读布局的选项吗

**Comment by 1162706031** [comment]
禁漫天堂搜索显示403

**Comment by wgh136** [comment]
> 禁漫天堂搜索显示403，而且还有一个问题 就是E-Hentai会锁IP，经常显示当前IP超过图片限制。不知道有没有好的解决方法。

禁漫官方app又更新了, 搞不懂他们在干嘛, 等会儿我发个新版本
eh这个我没办法, 用更干净的节点是唯一办法

**Comment by zhongfly** [comment]
安卓版2.0.2~2.0.4(暂未测试其他2.x版本)，在我的使用时有严重的bug
1，无法保存设置、登录信息、是否首次打开应用。每次打开都是首次打开一样，显示了设置引导，而且每次打开都是未登录状态，需要重新登录账号。
![Screenshot_20230726221350](https://github.com/wgh136/PicaComic/assets/11155705/323d78cd-5c3e-4ce7-95ed-13869cc07e5d)

2，所有源的所有漫画都不显示封面图片，本子列表页、详情页都不会显示封面图片，但打开章节，可以正常显示漫画图片…
![Screenshot_20230726221422](https://github.com/wgh136/PicaComic/assets/11155705/3b144f87-61c5-4d37-a09d-25854250eb21)
![Screenshot_20230726221434](https://github.com/wgh136/PicaComic/assets/11155705/119e338b-9305-42d7-a551-9f9ce0dbedb4)

**Comment by wgh136** [comment]
根据描述似乎是数据读写出现了问题，打开设置-APP-Logs看一下是否存在错误日志。另外能否提供一下系统信息

________________________________

**Comment by zhongfly** [comment]
> 根据描述似乎是数据读写出现了问题，打开设置-APP-Logs看一下是否存在错误日志。另外能否提供一下系统信息

我更新了描述，找到了原因，是旧版迁移数据方法导致的。由于删除了之前复制过去的旧版数据文件夹，log也没有之前的了。

**Comment by zhongfly** [comment]
1. ![Screenshot_20230726222228](https://github.com/wgh136/PicaComic/assets/11155705/fec479af-f695-4626-a749-29b9009133d9)
这个“新到书”是笔误吧

**Comment by wgh136** [comment]
> 1. ![Screenshot_20230726222228](https://user-images.githubusercontent.com/11155705/256262385-fec479af-f695-4626-a749-29b9009133d9.png)
>    这个“新到书”是笔误吧

感谢告知

**Comment by zhongfly** [comment]
可以增加一个设置，列表里一页显示多少本。
目前在我的手机上，一页也就显示4本半，我觉得可以适当提高到7本，不过考虑每个人都各有偏好，所以可以变成一个设置，自由选择显示的数量。
漫画详情页感觉可以更紧凑，尽量是减少上下滑动的需求，目前每个地方都偏大，应该主要显示漫画简介、章节相关的信息，缩小一些图标 文字。比如增加一个紧凑样式，类似这样，或者是其他漫画应用那样：
![Screenshot_20230726224616](https://github.com/wgh136/PicaComic/assets/11155705/5b659c1f-5f87-42b1-b2c2-18875d935efd)

**Comment by wgh136** [comment]
> 1.可以增加一个设置，列表里一页显示多少本。 目前在我的手机上，一页也就显示4本半，我觉得可以适当提高到7本，不过考虑每个人都各有偏好，所以可以变成一个设置，自由选择显示的数量。 2.漫画详情页感觉可以更紧凑，尽量是减少上下滑动的需求，目前每个地方都偏大，应该主要显示漫画简介、章节相关的信息，缩小一些图 /标 文字。比如增加一个紧凑样式，类似这样，或者是其他漫画应用那样： ![Screenshot_20230726224616](https://user-images.githubusercontent.com/11155705/256272136-5b659c1f-5f87-42b1-b2c2-18875d935efd.png) ![Screenshot_20230726225249](https://user-images.githubusercontent.com/11155705/256274135-5f35e4de-7a6a-4f2a-96d3-017747d066a6.png)
> 
> 总的来说ui各个元素能小点就好了，提高密度

1. 确实有必要进行调整
2. 漫画详情页的紧凑样式将导致在屏幕较大的设备上显示效果糟糕, 目前没有精力做动态调整大小, 调ui并使其在各个屏幕大小下都有较好效果是一件很麻烦的事

**Comment by wgh136** [comment]
> 概率触发的Bug：手机端，从上到下（连续）的阅读模式，双指放大再缩小，有概率卡住不能再上下滑动，然后唤出菜单或者退出再进就不会了
> 
> Bug貌似要看几十本才可能出现一次这样的频率，没法100%稳定复现，只能说确实有这回事，然后去看log也没发现什么异常

难以复现, 我记得我曾经触发过这个bug, 暂时没办法解决

**Comment by wgh136** [comment]
> 建议：加上“重新加载该图片”的选项，不然有时候有部分图片加载超时/加载错误的话就只能退出重新再进才会重新加载没加载出来的图片

切换一下图片会触发重构, 就重新加载了
如果是从上到下（连续）, 需要滑动远一点, 因为有缓存机制

**Comment by nekoreimu** [comment]
能在阅读界面添加右滑返回吗,ipad每次都要点左上角返回很不方便

**Comment by wgh136** [comment]
> 能在阅读界面添加右滑返回吗,ipad每次都要点左上角返回很不方便

ipad不能右滑返回吗? 🤔
查了一下, 是flutter的bug, 2018年的问题, 到现在都没修复. 需要寻找其他方式解决

**Comment by Smile8848** [comment]
点击翻页总是。。需要点两下才能反应过来这是BUG吗？我是左到右翻页

**Comment by wgh136** [comment]
> 点击翻页总是。。需要点两下才能反应过来这是BUG吗？我是左到右翻页

是有延迟吧, 因为同时在检测双击

**Comment by Smile8848** [comment]
> > 点击翻页总是。。需要点两下才能反应过来这是BUG吗？我是左到右翻页
> 
> 是有延迟吧, 因为同时在检测双击

能设置关掉双击就好了，平板用的也不要放大。。

**Comment by LMKSHINE** [comment]
![image](https://github.com/wgh136/PicaComic/assets/117559802/c8d02386-0f4e-41ad-a994-3ed8b31e40ff)
请问搜索栏可以添加一键删除吗，连续搜索多个本子时删除有点麻烦

**Comment by Skadi703** [comment]
hitomi报错
DioException [bad response]:The request returned an invalid status code of 403.

**Comment by qqet** [comment]
佬，双页浏览的图片顺序希望可以调整，图一图二变成图二图一这种，然后翻页也可以从右到左。小小的建议。
大佬辛苦了，感谢付出。

**Comment by NidehogeFool** [comment]
收索picacg时返回500，能改吗？
the request returned a invalid status code 500

**Comment by NidehogeFool** [comment]
pc端搜索picacg时返回500，能改吗？
the request returned a invalid status code 500

**Comment by wgh136** [comment]
太长了, 重新开一个

**Comment by SerenBanka** [comment]
账号找回email无法接收，账号不见
