### ISSUE TITLE
关于禁漫老是错误的问题[Enhancement]: 

### ISSUE THREAD

**Issue by yinyan9066** [wgh136/PicaComic#271]
### 描述/Description

作者大大方不方便加一个让我们自己修改禁漫地址的功能然后把发布页放进去 这样不用每次禁漫更新一次网址APP就要更新一次

**Comment by yezechuandl** [comment]
> ### 描述/Description
> 作者大大方不方便加一个让我们自己修改禁漫地址的功能然后把发布页放进去 这样不用每次禁漫更新一次网址APP就要更新一次
> 
> ### 操作系统/Operating System
> _No response_
> 
> ### 图片/picture
> _No response_
目前是用的禁漫的官方App的api接口写的，换接口也得自己会抓包，所以作者在重构了，之后应该会加上吧

**Comment by sevenmine** [comment]
@yinyan9066 老哥禁漫的地址一般从哪里获取
