### ISSUE TITLE
[Bug]: 手机端不显示禁漫收藏夹下面的翻页按钮

### ISSUE THREAD

**Issue by ccicnce113424** [wgh136/PicaComic#274]
### 描述/Description

当收藏夹内项目较多时，只能加载收藏夹最前面一部分项目，对应禁漫官方app在收藏夹界面不点击“加载更多”所能显示的全部项目。

### Version

latest

### 使用的操作系统/Operating system

Android

**Comment by wgh136** [comment]
我现在的禁漫收藏夹是空的, 不清楚什么情况
多少收藏时会显示“加载更多”?

**Comment by ccicnce113424** [comment]
> 我现在的禁漫收藏夹是空的, 不清楚什么情况 多少收藏时会显示“加载更多”?

实测点进去加载20个，每点一次加载更多最多增加20个

**Comment by ccicnce113424** [comment]
> 我现在的禁漫收藏夹是空的, 不清楚什么情况 多少收藏时会显示“加载更多”?

您可以随意塞超过20个项目到任意收藏夹里面，然后问题应该就会复现

**Comment by wgh136** [comment]
我试了下并没有问题
当收藏夹中漫画数量超过20时, 禁漫网页上会出现页面选择
![image](https://github.com/wgh136/PicaComic/assets/67669799/90b90e19-5b8f-4426-a26a-4344c0642953)
app也正常处理了
![image](https://github.com/wgh136/PicaComic/assets/67669799/e126e3fb-e582-4bf0-a881-e60f109632d7)

**Comment by ccicnce113424** [comment]
> 我试了下并没有问题 当收藏夹中漫画数量超过20时, 禁漫网页上会出现页面选择 ![image](https://private-user-images.githubusercontent.com/67669799/285902109-90b90e19-5b8f-4426-a26a-4344c0642953.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExMzk4NzksIm5iZiI6MTcwMTEzOTU3OSwicGF0aCI6Ii82NzY2OTc5OS8yODU5MDIxMDktOTBiOTBlMTktNWI4Zi00NDI2LWEyNmEtNDM0NGMwNjQyOTUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDAyNDYxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzZTFlMWYzY2ZkYzdiYjMwOWY2YjE2NGRjMmJmYWVlNDU0MzFjMDNmM2ZjNzMwMjk5M2NmY2NkNDA0OGE5MGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jcj0nwdZnTBhqshxsFJtThzeqtHbPAL0274jEZ5WA70) app也正常处理了 ![image](https://private-user-images.githubusercontent.com/67669799/285901895-e126e3fb-e582-4bf0-a881-e60f109632d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExMzk4NzksIm5iZiI6MTcwMTEzOTU3OSwicGF0aCI6Ii82NzY2OTc5OS8yODU5MDE4OTUtZTEyNmUzZmItZTU4Mi00YmYwLWE4ODEtZTYwZjEwOTYzMmQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDAyNDYxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyYWVhMmJlY2ZlMzUyZGNmZTNjMTlhZDM3MzNhODhmNzI1ZTg4M2E4NmRmMmQ1ODM0YjAzMjI2NzI1NGJmMjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OTLTfUhJyjlyapwpJpGG4EXzyEq6G8HVJ5EleOcKIjI)

等下回去我会试试。如果是这样我会close这个issue，很抱歉耗费了您的时间和精力。

**Comment by ccicnce113424** [comment]
> 我试了下并没有问题 当收藏夹中漫画数量超过20时, 禁漫网页上会出现页面选择 ![image](https://private-user-images.githubusercontent.com/67669799/285902109-90b90e19-5b8f-4426-a26a-4344c0642953.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExNDg1NzksIm5iZiI6MTcwMTE0ODI3OSwicGF0aCI6Ii82NzY2OTc5OS8yODU5MDIxMDktOTBiOTBlMTktNWI4Zi00NDI2LWEyNmEtNDM0NGMwNjQyOTUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDA1MTExOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3YzBlODAzYzQ3MmQxMzU4YTc4NmFiMzE5YjkzYmUxM2QyMWYxMTZhZTE3M2Y0MmU0ZWI0YzhkYTExNDBiMzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ox6rEO1PuMAKifHgqvBH67hJDVM1If0YPEna2OJEAao) app也正常处理了 ![image](https://private-user-images.githubusercontent.com/67669799/285901895-e126e3fb-e582-4bf0-a881-e60f109632d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExNDg1NzksIm5iZiI6MTcwMTE0ODI3OSwicGF0aCI6Ii82NzY2OTc5OS8yODU5MDE4OTUtZTEyNmUzZmItZTU4Mi00YmYwLWE4ODEtZTYwZjEwOTYzMmQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDA1MTExOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1MTVjYzczNjU5NDg2NWRkZTY2YmI2NTIyODdiODA5MjkxYWRlMzYxNzZkZWRmNWQzMjcxN2U4ODI0YTQwMjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jeFSPAK5XvzLpeO22cHWNjAgLjzBCE0CR_vo5QZyXew)

平板上面可以看到底下的翻页选项，但是手机上面找不到

**Comment by wgh136** [comment]
是不是被手机底部的导航栏挡住了

**Comment by ccicnce113424** [comment]
![IMG_20231129_021442](https://github.com/wgh136/PicaComic/assets/30774232/29923167-f84c-4ff3-8208-e688bc173976)
拉到最下
![IMG_20231129_021608](https://github.com/wgh136/PicaComic/assets/30774232/068f99e4-d9f7-4c9f-a213-4c23571d01b2)
拉到最上
设备是Redmi K60 Pro，系统版本MIUI 14.0.25。手头上没有别的机型来验证能否复现。

**Comment by wgh136** [comment]
现在应该不存在这个问题了, 小屏设备上切换页面的按钮被移动至侧边
