### ISSUE TITLE
建议加载缩略图时优先加载当前所处位置的缩略图

### ISSUE THREAD

**Issue by Chilianxin** [wgh136/PicaComic#278]
比如我打开一个新的nh漫画页，我希望能优先加载我划到的缩略页，而不是从头开始要把之前的部分全部加载

另外禁漫改成网页以后，添加收藏夹会有超过上限添加失败的问题，但仍然提示成功添加收藏夹
禁漫的网页端在收藏夹超额后无法继续添加，app超额后仍然能正常添加

**Comment by wgh136** [comment]
并不会从头开始加载, 你可以找一个图片数量很多的漫画试试, 当一个图片离开屏幕显示范围较远时, 它会被销毁, 并且停止加载

**Comment by Chilianxin** [comment]
> 并不会从头开始加载, 你可以找一个图片数量很多的漫画试试, 当一个图片离开屏幕显示范围较远时, 它会被销毁, 并且停止加载

至少NH不是这样的，我在打开一个长篇本后只会按序加载预览图，并不会移动到哪优先加载哪

**Comment by wgh136** [comment]
没有必要, 只要网络正常, 加载100张缩略图也就一两秒的时间
这东西做起来不简单, 我不应该把时间用在这上面

**Comment by Chilianxin** [comment]
> 没有必要, 只要网络正常, 加载100张缩略图也就一两秒的时间 这东西做起来不简单, 我不应该把时间用在这上面

好的
