### ISSUE TITLE
后续会有win端的ex站点直连吗

### ISSUE THREAD

**Issue by pansuto** [wgh136/PicaComic#28]
账号是有里站权限的，但是换了好多个节点都进不去，网页倒偶尔能进（用cookie改是百分百进的，但是app里只有两行ipb没有igneous不知道是不是这个原因），换其他人的账号同节点却进去了。两账号在绿色eh上使用正常

**Comment by wgh136** [comment]
我这里一切正常
因为在仅使用两行ipb的情况下没有发现任何问题，所以没有提供igneous的设置
或许不同的账号不一样？

**Comment by wgh136** [comment]
现在加上了igneous的设置
请更新至最新版, 然后重新登录试试

**Comment by Yaoxystar** [comment]
加上igneous能进里站了，之前也是有权限进不了

**Comment by wgh136** [comment]
那么我就认为这个issue完成了, 欢迎提出其它问题
