### ISSUE TITLE
[Enhancement]: 希望在阅读页可以隐藏左下角的章节和页数信息

### ISSUE THREAD

**Issue by suppermanzero** [wgh136/PicaComic#281]
### 描述/Description

希望在阅读页面左下角可以增加个开关，隐藏章节和页数信息，那样就可以沉浸式观看了。其他APP我也找了几个，发现里面有的是一键隐藏页面信息，有的甚至给做成单个开关了，状态栏、电量、页码、时间等都可以隐藏，希望大佬可以做一下。

### 操作系统/Operating System

Android

**Comment by wgh136** [comment]
你为什么要开两个同样的issue
