### ISSUE TITLE
[Bug]: 绅士漫画收藏后没变化

### ISSUE THREAD

**Issue by suppermanzero** [wgh136/PicaComic#284]
### 描述/Description

绅士漫画收藏后，收藏按钮没变化，不会从收藏按钮变成已收藏；哔咔、禁漫、E站等成功收藏后按钮都会从收藏 变成 已收藏，大佬看看绅士漫画这个收藏按钮是不是BUG呢
![IMG_20231128_135846](https://github.com/wgh136/PicaComic/assets/151978274/055ec9f0-2f11-4ec3-9c27-63175817b3d3)
![IMG_20231128_135824](https://github.com/wgh136/PicaComic/assets/151978274/e15f020a-e77d-4a7a-bbad-d3a745592b1f)

### Version

latest

### 使用的操作系统/Operating system

Android

**Comment by wgh136** [comment]
你去绅士漫画官网看看
