### ISSUE TITLE
[Bug]: 禁漫源无法收藏本子，也无法通过页码翻页查看收藏

### ISSUE THREAD

**Issue by jogGUY** [wgh136/PicaComic#285]
### 描述/Description

早上开了APP想收藏本子，结果点了收藏按钮，”收藏中“过了一小会就弹窗报错，进日志看到的错误就是第一张图。等中午再打开APP，进了收藏界面，能进到收藏夹页面，也能看见收藏夹的第一页，也能通过点击下一页按钮翻页，但是通过输入页码翻页时就会显示Instance of ‘Error’，进日志看到的错误就是剩下两张图

### Version

latest

### 使用的操作系统/Operating system

Android

### 截图或视频/Screenshot or video

![Screenshot_2023-11-28-08-19-44-73](https://github.com/wgh136/PicaComic/assets/108516858/384038f9-01e5-4673-965b-da0c0c8fb57a)
![Screenshot_2023-11-28-13-18-39-82_ac34e1ea2cb6328eff9323b065294cd0](https://github.com/wgh136/PicaComic/assets/108516858/53590086-d293-4764-9738-d353126d64ba)
![Screenshot_2023-11-28-13-18-54-03](https://github.com/wgh136/PicaComic/assets/108516858/2a93e4f1-6c1a-4dd0-b3a0-a8a84e4ba7bb)

**Comment by wgh136** [comment]
第一张图是403, 表示你的ip被禁漫ban了
第二张图是一个bug, 将会修复
