### ISSUE TITLE
[Bug]: 重构后的jm请求看起来未达到预期效果

### ISSUE THREAD

**Issue by zhuhewei** [wgh136/PicaComic#286]
### 描述/Description

重构后的jm请求看起来未达到预期效果

### Version

latest

### 使用的操作系统/Operating system

Android

### 日志/logs

NetworkerrorDioException [unknown]: null
Error: SocketException: Connection failed (OS Error: Network is unreachable, errno = 101), address = 18comic.vip, port = 443
#0      DioMixin.fetch.<anonymous closure> (package:dio/src/dio_mixin.dart:507)
#1      _rootRunUnary (dart:async/zone.dart:1407)
#2      _CustomZone.runUnary (dart:async/zone.dart:1308)
#3      _FutureListener.handleError (dart:async/future_impl.dart:180)
#4      Future._propagateToListeners.handleError (dart:async/future_impl.dart:858)
#5      Future._propagateToListeners (dart:async/future_impl.dart:879)
#6      Future._completeError (dart:async/future_impl.dart:655)
#7      _SyncCompleter._completeError (dart:async/future_impl.dart:63)
#8      _Completer.completeError (dart:async/future_impl.dart:27)
#9      Future.any.onError (dart:async/future.dart:618)
#10     _rootRunBinary (dart:async/zone.dart:1423)
#11     _CustomZone.runBinary (dart:async/zone.dart:1315)
#12     _FutureListener.handleError (dart:async/future_impl.dart:177)
#13     Future._propagateToListeners.handleError (dart:async/future_impl.dart:858)
#14     Future._propagateToListeners (dart:async/future_impl.dart:879)
#15     Future._completeError (dart:async/future_impl.dart:655)
#16     Future._chainForeignFuture.<anonymous closure> (dart:async/future_impl.dart:556)
#17     _rootRun (dart:async/zone.dart:1399)
#18     _CustomZone.run (dart:async/zone.dart:1301)
#19     _CustomZone.runGuarded (dart:async/zone.dart:1209)
#20     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249)
#21     _microtaskLoop (dart:async/schedule_microtask.dart:40)
#22     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49)
2023-11-28 16:09:09复制

可能性1，源本身有问题（这个应该如何获取？）

**Comment by wgh136** [comment]
app和源都没有问题
挂梯子或者改个能直连的域名

**Comment by zhuhewei** [comment]
直连域名是什么？
![1dcb4eefd9b9097948c76c97f11923be](https://github.com/wgh136/PicaComic/assets/19264066/46d418c8-888c-422b-88c8-29542bf010fb)
![7f6412c45336d8245444719a16281e34](https://github.com/wgh136/PicaComic/assets/19264066/a823d427-7c71-4e82-91a7-0f63454cfe3e)
经过测试，看起来跟这个验证相关
