### ISSUE TITLE
[Bug]: 禁漫无法登录和加载

### ISSUE THREAD

**Issue by hzz888999** [wgh136/PicaComic#290]
### 描述/Description

禁漫无法登录和加载，更换节点也不行

### Version

latest

### 使用的操作系统/Operating system

Android

### 截图或视频/Screenshot or video

![Screenshot_20231130_120658](https://github.com/wgh136/PicaComic/assets/152464686/1281fedd-0a0f-4992-a7f9-1a2d815a9abc)

**Comment by wgh136** [comment]
你在设置中设置了一个无效的禁漫域名

**Comment by zhuhewei** [comment]
@hzz888999 
老哥，看#286
