### ISSUE TITLE
[Enhancement]: PC端操作有冲突 建议滚轮加个设置

### ISSUE THREAD

**Issue by KougamiYuriko** [wgh136/PicaComic#292]
### 描述/Description

PC端阅读模式上下的时候，往上滚动漫画会和放大图片冲突。选项里没有关闭放大的功能。往上滚动就会放大图片。

### 操作系统/Operating System

Windows

**Comment by KougamiYuriko** [comment]
在建议加个鼠标左键上下拖动的功能，就像网页一样。

**Comment by wgh136** [comment]
按住CTRL键才会缩放图片
