### ISSUE TITLE
[Bug]: 新版APP下哔咔源的一些错误

### ISSUE THREAD

**Issue by jogGUY** [wgh136/PicaComic#298]
### 描述/Description

升级到新版之后，哔咔源封面几乎加载不出来，分区图片也一样。尝试了两次，第一次使用移动数据，第二次使用WiFi，结果都一样，日志中的错误分别见截图1、2。这里有个问题：和hosts中的哔咔IP是服务器真实IP还是Cloudflare分发下的CDN的IP？本次更新是不是意味着：

- 重新实现了在三月份更新时去除的自选IP分流功能（ #5 ）？
- 转发服务器花销过大？🤣

后来，我尝试下了某本，发现会报下载错误，日志结果见图4。最后，一开始测试时看本还可以，后来就出现了图3的错误，这是哔咔方面的问题么？日志结果见图5（图五的日志下面还有一个跟图5第二个error一模一样的，懒得截图了······）。

### Version

latest

### 使用的操作系统/Operating system

Android

### 截图或视频/Screenshot or video
图1：
![Screenshot_2023-12-02-14-11-06-30_ac34e1ea2cb6328eff9323b065294cd0](https://github.com/wgh136/PicaComic/assets/108516858/9b39791c-9ca6-4ed9-83af-e1d255f80612)
图2：
![Screenshot_2023-12-02-14-19-56-41_ac34e1ea2cb6328eff9323b065294cd0](https://github.com/wgh136/PicaComic/assets/108516858/aed6dd6c-26ef-44b6-bd48-232854d8259b)
图3：
![Screenshot_2023-12-02-14-22-26-96_ac34e1ea2cb6328eff9323b065294cd0](https://github.com/wgh136/PicaComic/assets/108516858/82dfac03-a08a-4c17-92a0-186477515d0f)
图4：
![Screenshot_2023-12-02-15-07-37-43](https://github.com/wgh136/PicaComic/assets/108516858/ce06df67-ba61-41cb-b92e-30b32db1191c)
图5：
![Screenshot_2023-12-02-15-11-38-91](https://github.com/wgh136/PicaComic/assets/108516858/2c4da69f-89f4-495d-b95d-22dd465eb8af)

**Comment by wgh136** [comment]
建议使用梯子, 这是最优的方式
转发服务器维护成本较高, 不是长久之计, 但暂时不会关闭, 如有需要, 先使用旧版

**关于hosts**
内置的哔咔ip是cf的cdn, 你可以自己更换; 如果你知道原站的ip, 把它写到https下面, 直接通过https访问cf的cdn会出现tls握手失败,
图上有一个301错误, 那是我没有处理301重定向, 下个版本修复

**关于epub**
因为没有可用的库, 我需要自己造轮子, 而我也不了解epub, 我需要花时间学

**Comment by wgh136** [comment]
首先明确一点: 我从来没说过这是"面向大众提供的第三方APP", 所有的功能应当是我自己需要的情况下我才会付出大量时间和精力去做, 我从来都不存在"不开转发服务器根本无法使用"的问题, 之前有转发服务器是因为我手上有一个空闲的vps.

hosts功能的实现方式已经更改, 现在应该不存在什么问题了
