### ISSUE TITLE
关于APP功能

### ISSUE THREAD

**Issue by jogGUY** [wgh136/PicaComic#3]
你好作者，这个APP很不错，不过似乎这个APP还比较“稚嫩”，不知道接下来会优先更新哪些功能或者解决哪些问题呢？

1. 本项目用了中转服务器来实现CN直连，那有没有可能通过添加自定义代理或者分流的功能解决连接问题，比如[picacg-qt](https://github.com/tonquer/picacg-qt)这个项目实现的Cloudflare的CDN分流？
2. 有没有可能实现收藏夹分页浏览呢？
3. 有没有可能实现滚动浏览图片呢？
4. 有没有可能在未来获取本子妹/本子母推荐呢？
5. 有没有可能可以复制作者名/Tag呢？
6. 会不会需要输出错误日志的功能来排查将来可能出现的故障？

**Comment by wgh136** [comment]
感谢你的建议
1. 本项目使用的中转服务器和web端服务器都套了cloudflare的cdn, 自定义代理可以并且不难实现, 之后会加上. [picacg-qt](https://github.com/tonquer/picacg-qt)实现的是一个选择Cloudflare的CDN功能, 等我研究一下再说
2. 目前的收藏夹是滑动到底部自动加载下一页(如果有的话), 不太清楚分页浏览相对于这种方式有什么优点
3. 可以实现, 等我将其它功能实现后再提供阅读器的各种自定义选项
4. 不难实现, 下个版本加上
5. 在漫画详情页点右上角图标可以查看漫画详情, 此处可以复制作者名, 下个版本把复制tag也加上
6. 目前采用的是[Sentry](https://sentry.io/)提供的错误捕捉系统, 错误日志会自动上传, 因此不需要输出错误日志

**Comment by jogGUY** [comment]
感恩作者🌹

关于“分页浏览有什么优点”这个问题，我想说的是：可能只要不像我一样本子收藏了上千本的话那么现在这种方式还是够用的，这个也只是一个可选项罢了，有很多feature可能会因为实现起来麻烦、缺时间、没有太大必要等因素没有实装，这可以理解😎

另外，看到作者提供了Web端，我有点好奇去试了一下，发现打开就是白屏，它是到现在还是处于寄的状态还是我的网络有问题？或许Web端可以搞成那种自己本地一键部署的样子？😂
![Windows 7 x64-2023-02-14-22-35-33](https://user-images.githubusercontent.com/108516858/218770281-464c4405-0eed-4436-a665-56ea88ac7de0.png)

**Comment by wgh136** [comment]
@jogGUY 
上千本的话确实有必要分页浏览, 之后会实现
Web端我也不清楚发生了什么, 刚才重启了一下, 现在好了
Web端加载有点慢, 第一次启动会加载很久, 下一个版本解决这个问题
本地部署没什么必要, Web端第一次加载完成后浏览器中会有缓存, 下次打开就不需要加载了(除非版本更新)

**Comment by wgh136** [comment]
我这里使用官方app, 本子妹/本子母推荐是空的. 抓包得到的数据也是空的.
不清楚为什么, 所以暂时没做
```json
{
  "code": 200,
  "message": "success",
  "data": {
    "collections": [
      {
        "title": "本子妹推薦",
        "comics": []
      },
      {
        "title": "本子母推薦(貧乳)",
        "comics": []
      }
    ]
  }
}
```

**Comment by shizq123** [comment]
> 我这里使用官方app， 本子妹/本子母推荐是空的.抓包得到的数据也是空的. 不清楚为什么， 所以暂时没做
> 
> ```json
> {
>   "code": 200,
>   "message": "success",
>   "data": {
>     "collections": [
>       {
>         "title": "本子妹推薦",
>         "comics": []
>       },
>       {
>         "title": "本子母推薦(貧乳)",
>         "comics": []
>       }
>     ]
>   }
> }
> ```

二级以后会有的

{
  "code": 200,
  "message": "success",
  "data": {
    "collections": [
      {
        "title": "本子妹推薦(New)",
        "comics": [
          {
            "_id": "5c2994a7c6645303849ba5ed",
            "title": "楓と鈴2",
            "author": "きょくちょ",
            "pagesCount": 25,
            "epsCount": 1,
            "finished": true,
            "categories": [
              "短篇",
              "純愛"
            ],
            "thumb": {
              "fileServer": "https://storage1.picacomic.com",
              "path": "a3c65355-9c41-4ce2-a3bf-1a083b922d9a.jpg",
              "originalName": "1.jpg"
            },
            "totalLikes": 11532,
            "totalViews": 439227
          },
          {
            "_id": "61417e43e393d66f60f71bc6",
            "title": "安眠枕。",
            "author": "まんねんドコドコドンドドコ (とっととねろ太郎。)",
            "totalViews": 20329,
            "totalLikes": 197,
            "pagesCount": 30,
            "epsCount": 1,
            "finished": false,
            "categories": [
              "短篇",
              "生肉"
            ],
            "thumb": {
              "originalName": "01.jpg",
              "path": "76347770-fb5f-46a6-957d-51f4d3b3ec36.jpg",
              "fileServer": "https://storage1.picacomic.com"
            }
          },
          {
            "_id": "62c1cfc0bec00f31d3b97d7f",
            "title": "らぶりー♡",
            "author": "きょくちょ",
            "totalViews": 242249,
            "totalLikes": 4554,
            "pagesCount": 204,
            "epsCount": 1,
            "finished": false,
            "categories": [
              "長篇",
              "單行本"
            ],
            "thumb": {
              "originalName": "001__00.jpg",
              "path": "tobs/34833f09-5271-4c2b-a3f0-1ae83efce432.jpg",
              "fileServer": "https://storage-b.picacomic.com"
            }
          },
          {
            "_id": "63059d16db417d7d19150803",
            "title": "キャッチアップ!",
            "author": "Cuvie",
            "totalViews": 13981,
            "totalLikes": 125,
            "pagesCount": 26,
            "epsCount": 1,
            "finished": false,
            "categories": [
              "短篇"
            ],
            "thumb": {
              "originalName": "0.jpg",
              "path": "tobs/915eb8ba-2948-4c45-abfd-d00deba663fa.jpg",
              "fileServer": "https://storage-b.picacomic.com"
            }
          }
        ]
      },
      {
        "title": "本子母推薦(貧乳)",
        "comics": [
          {
            "_id": "5e0e0856ff2c7627e8a20e4d",
            "title": "りりすぱ!",
            "author": "毛玉牛乳 (玉之けだま)",
            "totalViews": 73382,
            "totalLikes": 1204,
            "pagesCount": 29,
            "epsCount": 1,
            "finished": false,
            "categories": [
              "全彩",
              "短篇",
              "生肉"
            ],
            "thumb": {
              "originalName": "img001.jpg",
              "path": "5100c784-7962-430c-912c-d7f4b7b260cf.jpg",
              "fileServer": "https://storage1.picacomic.com"
            }
          },
          {
            "_id": "5e5fc9df9e1fb175abc7a7ac",
            "title": "ポータちゃんとまーくんのいちゃエロ新婚生活",
            "author": "Ultimate Sugar (みやもとゆう)",
            "totalViews": 10876,
            "totalLikes": 94,
            "pagesCount": 26,
            "epsCount": 1,
            "finished": false,
            "categories": [
              "短篇",
              "同人",
              "生肉",
              "純愛"
            ],
            "thumb": {
              "originalName": "01_001.jpg",
              "path": "f7d6b426-1ad2-44a5-bf72-5369e4e178cd.jpg",
              "fileServer": "https://storage1.picacomic.com"
            }
          },
          {
            "_id": "6054e28d5b485b6d53e2cb5c",
            "title": "メイドさんになってあげる",
            "author": "しまじや (しまじ)",
            "totalViews": 8995,
            "totalLikes": 85,
            "pagesCount": 20,
            "epsCount": 1,
            "finished": false,
            "categories": [
              "短篇",
              "生肉"
            ],
            "thumb": {
              "originalName": "1.jpg",
              "path": "acf70bf5-b69e-46f1-a1d6-ba5f4735156c.jpg",
              "fileServer": "https://storage1.picacomic.com"
            }
          },
          {
            "_id": "618cde0a4a93a7190d449e44",
            "title": "ひっこしのよる",
            "author": "天気輪 (甘露アメ)",
            "totalViews": 91283,
            "totalLikes": 785,
            "pagesCount": 37,
            "epsCount": 2,
            "finished": false,
            "categories": [
              "短篇"
            ],
            "thumb": {
              "fileServer": "https://storage-b.picacomic.com",
              "path": "tobs/c24bf0b5-32a8-4814-8712-af4cce5aea83.jpg",
              "originalName": "001.jpg"
            }
          }
        ]
      }
    ]
  }
}

**Comment by shizq123** [comment]
二级以后会有的
```json
{
  "code": 200,
  "message": "success",
  "data": {
    "collections": [
      {
        "title": "本子妹推薦(New)",
        "comics": [
          {
            "_id": "5c2994a7c6645303849ba5ed",
            "title": "楓と鈴2",
            "author": "きょくちょ",
            "pagesCount": 25,
            "epsCount": 1,
            "finished": true,
            "categories": [
              "短篇",
              "純愛"
            ],
            "thumb": {
              "fileServer": "https://storage1.picacomic.com",
              "path": "a3c65355-9c41-4ce2-a3bf-1a083b922d9a.jpg",
              "originalName": "1.jpg"
            },
            "totalLikes": 11532,
            "totalViews": 439227
          },
          {
            "_id": "61417e43e393d66f60f71bc6",
            "title": "安眠枕。",
            "author": "まんねんドコドコドンドドコ (とっととねろ太郎。)",
            "totalViews": 20329,
            "totalLikes": 197,
            "pagesCount": 30,
            "epsCount": 1,
            "finished": false,
            "categories": [
              "短篇",
              "生肉"
            ],
            "thumb": {
              "originalName": "01.jpg",
              "path": "76347770-fb5f-46a6-957d-51f4d3b3ec36.jpg",
              "fileServer": "https://storage1.picacomic.com"
            }
          },
          {
            "_id": "62c1cfc0bec00f31d3b97d7f",
            "title": "らぶりー♡",
            "author": "きょくちょ",
            "totalViews": 242249,
            "totalLikes": 4554,
            "pagesCount": 204,
            "epsCount": 1,
            "finished": false,
            "categories": [
              "長篇",
              "單行本"
            ],
            "thumb": {
              "originalName": "001__00.jpg",
              "path": "tobs/34833f09-5271-4c2b-a3f0-1ae83efce432.jpg",
              "fileServer": "https://storage-b.picacomic.com"
            }
          },
          {
            "_id": "63059d16db417d7d19150803",
            "title": "キャッチアップ!",
            "author": "Cuvie",
            "totalViews": 13981,
            "totalLikes": 125,
            "pagesCount": 26,
            "epsCount": 1,
            "finished": false,
            "categories": [
              "短篇"
            ],
            "thumb": {
              "originalName": "0.jpg",
              "path": "tobs/915eb8ba-2948-4c45-abfd-d00deba663fa.jpg",
              "fileServer": "https://storage-b.picacomic.com"
            }
          }
        ]
      },
      {
        "title": "本子母推薦(貧乳)",
        "comics": [
          {
            "_id": "5e0e0856ff2c7627e8a20e4d",
            "title": "りりすぱ!",
            "author": "毛玉牛乳 (玉之けだま)",
            "totalViews": 73382,
            "totalLikes": 1204,
            "pagesCount": 29,
            "epsCount": 1,
            "finished": false,
            "categories": [
              "全彩",
              "短篇",
              "生肉"
            ],
            "thumb": {
              "originalName": "img001.jpg",
              "path": "5100c784-7962-430c-912c-d7f4b7b260cf.jpg",
              "fileServer": "https://storage1.picacomic.com"
            }
          },
          {
            "_id": "5e5fc9df9e1fb175abc7a7ac",
            "title": "ポータちゃんとまーくんのいちゃエロ新婚生活",
            "author": "Ultimate Sugar (みやもとゆう)",
            "totalViews": 10876,
            "totalLikes": 94,
            "pagesCount": 26,
            "epsCount": 1,
            "finished": false,
            "categories": [
              "短篇",
              "同人",
              "生肉",
              "純愛"
            ],
            "thumb": {
              "originalName": "01_001.jpg",
              "path": "f7d6b426-1ad2-44a5-bf72-5369e4e178cd.jpg",
              "fileServer": "https://storage1.picacomic.com"
            }
          },
          {
            "_id": "6054e28d5b485b6d53e2cb5c",
            "title": "メイドさんになってあげる",
            "author": "しまじや (しまじ)",
            "totalViews": 8995,
            "totalLikes": 85,
            "pagesCount": 20,
            "epsCount": 1,
            "finished": false,
            "categories": [
              "短篇",
              "生肉"
            ],
            "thumb": {
              "originalName": "1.jpg",
              "path": "acf70bf5-b69e-46f1-a1d6-ba5f4735156c.jpg",
              "fileServer": "https://storage1.picacomic.com"
            }
          },
          {
            "_id": "618cde0a4a93a7190d449e44",
            "title": "ひっこしのよる",
            "author": "天気輪 (甘露アメ)",
            "totalViews": 91283,
            "totalLikes": 785,
            "pagesCount": 37,
            "epsCount": 2,
            "finished": false,
            "categories": [
              "短篇"
            ],
            "thumb": {
              "fileServer": "https://storage-b.picacomic.com",
              "path": "tobs/c24bf0b5-32a8-4814-8712-af4cce5aea83.jpg",
              "originalName": "001.jpg"
            }
          }
        ]
      }
    ]
  }
}
```

**Comment by wgh136** [comment]
@shizq123 原来是这样, 感谢
之前用哔咔一直只是看漫画, 没有关注等级

**Comment by shizq123** [comment]
> @shizq123 原来是这样， 感谢 之前用哔咔一直只是看漫画， 没有关注等级

客气 哈哈，漫画下面推荐也是需要二级以上

**Comment by shizq123** [comment]
> @shizq123 原来是这样, 感谢 之前用哔咔一直只是看漫画, 没有关注等级


漫画下面推荐
https://picaapi.picacomic.com/comics/漫画id/recommendation

 ```json
{
  "code": 200,
  "message": "success",
  "data": {
    "comics": [
      {
        "_id": "5d6144674b4df031401d2238",
        "title": "楓と鈴3 (COMIC BAVEL 2019年9月号) [中国翻訳] [DL版]",
        "author": "きょくちょ",
        "pagesCount": 49,
        "epsCount": 2,
        "finished": true,
        "categories": [
          "短篇",
          "純愛"
        ],
        "thumb": {
          "fileServer": "https://storage1.picacomic.com",
          "path": "tobeimg/sAAe84rMNB9yaDDMYjCSs0VII4MvQ89xgWc78EeNhVs/rs:fill:300:400:0/g:sm/aHR0cHM6Ly9zdG9yYWdlMS5waWNhY29taWMuY29tL3N0YXRpYy9hYzRlYjI2Yy01NWZiLTQ3MzEtOTE5Ni1hMTNjM2RjYjUxNzcuanBn.jpg",
          "originalName": "001.jpg"
        },
        "likesCount": 1857
      },
      {
        "_id": "5f7755d176e2e479c65de9d2",
        "title": " 楓と鈴 4.5 (COMIC BAVEL 2020年11月号) [中国翻訳] [DL版]",
        "author": "きょくちょ",
        "pagesCount": 23,
        "epsCount": 2,
        "finished": true,
        "categories": [
          "短篇",
          "姐姐系"
        ],
        "thumb": {
          "fileServer": "https://storage1.picacomic.com",
          "path": "tobeimg/12tC-ime5KPJrVuSupOGuCSo4vKhJHN7RWKvcGT4ALE/rs:fill:300:400:0/g:sm/aHR0cHM6Ly9zdG9yYWdlMS5waWNhY29taWMuY29tL3N0YXRpYy82OWUzNzljNC1iMDk5LTQ0YmEtOWE3Ni02ZmQ1NTllY2E1ZmQuanBn.jpg",
          "originalName": "103 (1).jpg"
        },
        "likesCount": 1224
      },
      {
        "_id": "5f469ecff7060d6a0c6e9b20",
        "title": "楓と鈴 4 (COMIC BAVEL 2020 年 10 月号)",
        "author": "きょくちょ",
        "pagesCount": 27,
        "epsCount": 1,
        "finished": true,
        "categories": [
          "短篇",
          "後宮閃光",
          "純愛"
        ],
        "thumb": {
          "originalName": "001.jpg",
          "path": "tobeimg/kGUa6fbfl5c2EEBsakUXow_IV_Y3LjVj0h6l0kGJ2nU/rs:fill:300:400:0/g:sm/aHR0cHM6Ly9zdG9yYWdlMS5waWNhY29taWMuY29tL3N0YXRpYy83NjY5NGRiMS1jMDY1LTQ1ZWEtODk1MS1mODE1ZTBmNTRkNmMuanBn.jpg",
          "fileServer": "https://storage1.picacomic.com"
        },
        "likesCount": 2586
      },
      {
        "_id": "5bc8c99e9b4c797c12edd8dc",
        "title": "楓と鈴",
        "author": "きょくちょ",
        "pagesCount": 25,
        "epsCount": 1,
        "finished": false,
        "categories": [
          "短篇",
          "強暴"
        ],
        "thumb": {
          "fileServer": "https://storage1.picacomic.com",
          "path": "tobeimg/f8EETcAPq2Vm5PwKdM7x1hnnWOBPW1AodAIQxmrg7c4/rs:fill:300:400:0/g:sm/aHR0cHM6Ly9zdG9yYWdlMS5waWNhY29taWMuY29tL3N0YXRpYy9kODE4MDE4Ni02MjU3LTRiMDgtOWVjZC03MWRkZjkwMDQ2ZjIuanBn.jpg",
          "originalName": "gIVqI2X.jpg"
        },
        "likesCount": 4032
      },
      {
        "_id": "60d7566d7873c31e99f83e72",
        "title": "楓と鈴 5 (COMIC BAVEL 2021年8月号)",
        "author": "きょくちょ",
        "pagesCount": 25,
        "epsCount": 1,
        "finished": true,
        "categories": [
          "短篇"
        ],
        "thumb": {
          "originalName": "001.jpg",
          "path": "tobeimg/AX8GnjowUqIFT86vI8EMmh-Z-P3r0WOwHPPnd9zK-4I/rs:fill:300:400:0/g:sm/aHR0cHM6Ly9zdG9yYWdlMS5waWNhY29taWMuY29tL3N0YXRpYy9iYTEzNWJlOS0yNzc3LTQ5M2MtYjgxOS1jMTI1NzIyODJmMTcuanBn.jpg",
          "fileServer": "https://storage1.picacomic.com"
        },
        "likesCount": 1962
      },
      {
        "_id": "62406b7c957de4458893cbdd",
        "title": " 楓と鈴 6 (COMIC BAVEL 2022年5月号) [中国翻訳] [DL版]",
        "author": "きょくちょ",
        "pagesCount": 26,
        "epsCount": 1,
        "finished": true,
        "categories": [
          "短篇",
          "純愛",
          "姐姐系"
        ],
        "thumb": {
          "originalName": "00.jpg",
          "path": "tobeimg/2DyEfN-vqEikZBAirurotSNSRFCHcRELqV_2HEXgSAw/rs:fill:300:400:0/g:sm/aHR0cHM6Ly9zdG9yYWdlLWIucGljYWNvbWljLmNvbS9zdGF0aWMvY2JjZmYzYzYtZTZiMS00MjE0LWFhODktMzc0NGFiZTcwOGJmLmpwZw.jpg",
          "fileServer": "https://storage-b.picacomic.com"
        },
        "likesCount": 2942
      },
      {
        "_id": "5f756c652ab34579d86045f4",
        "title": "らぶみー♥ 疼愛我嘛",
        "author": "きょくちょ",
        "pagesCount": 202,
        "epsCount": 1,
        "finished": true,
        "categories": [
          "長篇",
          "純愛",
          "後宮閃光",
          "單行本",
          "姐姐系",
          "妹妹系",
          "SM"
        ],
        "thumb": {
          "originalName": "001.jpg",
          "path": "tobeimg/4DlWIejgT3LF8SXQmUei_BSGetnysVn5AsxqMd880Es/rs:fill:300:400:0/g:sm/aHR0cHM6Ly9zdG9yYWdlMS5waWNhY29taWMuY29tL3N0YXRpYy8yMGZlM2JkYi1mNjFlLTQ5NTQtYjMwZC1jODdhNmE0OTBmMzIuanBn.jpg",
          "fileServer": "https://storage1.picacomic.com"
        },
        "likesCount": 4558
      },
      {
        "_id": "5e7bef095a66f70647e5f19e",
        "title": "みやびなせ先輩❤ (COMIC BAVEL 2020年5月号) [中国翻訳] [DL版]",
        "author": "きょくちょ",
        "pagesCount": 25,
        "epsCount": 1,
        "finished": true,
        "categories": [
          "短篇",
          "純愛"
        ],
        "thumb": {
          "originalName": "017.jpg",
          "path": "tobeimg/bhQo8BcIGmJL3DZy1fCWhwkvu_UAlUkiE2Mnqj8thko/rs:fill:300:400:0/g:sm/aHR0cHM6Ly9zdG9yYWdlMS5waWNhY29taWMuY29tL3N0YXRpYy8yNGMzOTc1NS02OWQzLTRkMDAtODA0Yy1lMGY2ODAwMzIyNWQuanBn.jpg",
          "fileServer": "https://storage1.picacomic.com"
        },
        "likesCount": 2043
      },
      {
        "_id": "5c32075b38c0f873bf87af46",
        "title": "らぶりー♥ 淫美可愛",
        "author": "きょくちょ",
        "pagesCount": 209,
        "epsCount": 1,
        "finished": true,
        "categories": [
          "單行本",
          "長篇",
          "後宮閃光",
          "SM",
          "妹妹系",
          "姐姐系",
          "純愛"
        ],
        "thumb": {
          "originalName": "000.jpg",
          "path": "tobeimg/spMSLesRv87DPOPuowoEP38Wcz7qgHlcgKdMmkf4fmg/rs:fill:300:400:0/g:sm/aHR0cHM6Ly9zdG9yYWdlMS5waWNhY29taWMuY29tL3N0YXRpYy8yNzBkOGQ0ZC1jMGUzLTRkNzUtOTRhNC1jMTZiNDI1M2NmNTUuanBn.jpg",
          "fileServer": "https://storage1.picacomic.com"
        },
        "likesCount": 3693
      },
      {
        "_id": "632d5e009c0a9a1aaa4adb01",
        "title": " メイド教育3-没落貴族瑠璃川椿- [DL版] [中国語]",
        "author": "きょくちょ局 (きょくちょ)",
        "pagesCount": 26,
        "epsCount": 1,
        "finished": true,
        "categories": [
          "短篇"
        ],
        "thumb": {
          "originalName": "q000.jpg",
          "path": "tobeimg/976lKbUsazRQX-f8S9KJA0EqoEBZhWngis6KVduvSrM/rs:fill:300:400:0/g:sm/aHR0cHM6Ly9zdG9yYWdlLWIucGljYWNvbWljLmNvbS9zdGF0aWMvMzk3MmYxYzMtNjliMS00N2M2LThiYzgtZjFiMWI0OWExZjdjLmpwZw.jpg",
          "fileServer": "https://storage-b.picacomic.com"
        },
        "likesCount": 21421
      }
    ]
  }
}
```

**Comment by liangzp190** [comment]
请问如何调整图片质量？用平板看图的时候清晰度很低。

**Comment by wgh136** [comment]
> 请问如何调整图片质量？用平板看图的时候清晰度很低。

设置的是最高质量, 没有给出切换选项
https://github.com/wgh136/PicaComic/blob/5d319e176106aa2166d485cffec4ff197181a3ed/lib/network/headers.dart#L89

**Comment by wgh136** [comment]
> 请问如何调整图片质量？用平板看图的时候清晰度很低。

找到问题了, 我的中转服务器没有设置最高质量, 已调整

**Comment by liangzp190** [comment]
感恩作者，平板升级了MIUI14之后不能用原应用了。折腾半天也没降级下来，这下终于有的可用了。

**Comment by jogGUY** [comment]
请问是不是可以考虑加一个屏蔽分类的功能？之前，纯爱分类点开来，“新书在前”排序，一堆BL给我看傻了o(￣┰￣*)ゞ
另外，点击本子的作者/汉化组/分类/标签进行搜索好像有问题——点进去会发现其实是返回了当前本子的分区⊙﹏⊙∥

**Comment by wgh136** [comment]
>请问是不是可以考虑加一个屏蔽分类的功能？之前，纯爱分类点开来，“新书在前”排序，一堆BL给我看傻了o(￣┰￣*)ゞ

可以有, 下个版本加上
>另外，点击本子的作者/汉化组/分类/标签进行搜索好像有问题——点进去会发现其实是返回了当前本子的分区⊙﹏⊙∥

我这里正常, 不知道哪里有问题


https://user-images.githubusercontent.com/67669799/225208679-3e2d82ba-6f6c-4ab7-9176-facfc70dddd0.mp4

**Comment by jogGUY** [comment]
![gif_20230315_125131](https://user-images.githubusercontent.com/108516858/225210407-43745b8c-09b7-422c-b04e-7830c508619a.gif)
@wgh136

**Comment by jogGUY** [comment]
可能，大概，Web端没有这种问题？

**Comment by wgh136** [comment]
了解了，从分类里面点进去的漫画会出现这个问题，下个版本修

**Comment by wgh136** [comment]
如果有其它的功能建议请另外开一个Issue
