### ISSUE TITLE
如果可以的话，希望增加下这些功能

### ISSUE THREAD

**Issue by guest-zero** [wgh136/PicaComic#30]
下载时好像是默认放在c盘，如果可以的话，还是希望默认与软件在同一个盘符，或者能够自行选择下载盘符。
下载界面的话，希望可以加个排序，或者按作者之类的自动分类，这样不同平台下载下来的东西方便查找。
暂时就这些，目前来说，软件不清楚下载是否有上限，如果没有那最好。站内其他软件大部分都是有上限或者需要挂梯子了，难道有个直连的，幸苦作者了

**Comment by wgh136** [comment]
目前的下载目录位于app的数据目录下, 即
`C:\Users\[用户名]\AppData\Roaming\com.kokoiro.xyz\pica_comic\download`
注意: AppData是一个隐藏目录
自行选择下载目录可以实现, 确实有必要

排序功能也确实有必要

不存在下载上限, 只要储存空间足够

**Comment by guest-zero** [comment]
嗯，谢谢，先去收藏漫画了，等更新再下载，不然我的c盘要撑不住了。
然后谢谢你的回复

**Comment by guest-zero** [comment]
@wgh136 
谢谢，那我就慢慢等下次更新啦，幸苦了

**Comment by wgh136** [comment]
设置下载目录的功能完成

但是排序遇到一点麻烦, 目前使用unicode进行排序, 这种方式很烂, 所以我也没写在更新内容里面
实现多语言字符串排序并不容易, 而且居然没有package可以用, 所以只能我自己写一个排序算法了
对于中文, 需要根据拼音排序, 但我也没有找到将汉字转为拼音的package, 也就是说这个也需要我自己去写
很麻烦, 以后再说吧

欢迎提出其它的建议

**Comment by guest-zero** [comment]
@wgh136 关于拼音排序，我觉得这个如果不翻译作者名字的话，这个排序方式可以不急，大部分作者使用的都是英语或日语。但如果软件使用的作者及其作品是翻译后的话，那这个就很麻烦，而且这种排序有可能会因为汉化组在作品前缀的原因，导致分类出现问题

**Comment by wgh136** [comment]
我是使用漫画名进行排序的, 使用作者名进行排序会更好吗

**Comment by guest-zero** [comment]
@wgh136 嗯，按漫画名排的话，感觉其实和直接下载下来默认排序差别不大。仅从我个人角度，我通常是喜欢同一作者的作品排在一起，这样找作品时也比较方便。按漫画名排的话，有部分漫画的名字是相差不大的，所以可能想找时会找到另一个作品。可能我的排序方式比较特殊，如果可以的话，还是希望添加按作者排序的方式

**Comment by wgh136** [comment]
了解了，之后会进行调整
