### ISSUE TITLE
增加新漫画源（拷贝漫画和包子漫画）

### ISSUE THREAD

**Issue by Jokervvv9** [wgh136/PicaComic#302]
### Content

大佬，能否增加非H漫画源（拷贝漫画https://www.copymanga.site/和包子漫画https://www.baozimh.com/）? Big thanks!

**Comment by wgh136** [comment]
暂时不打算添加新的漫画源, 以后再考虑

**Comment by wgh136** [comment]
使用自定义漫画源功能
