### ISSUE TITLE
[Enhancement]: Ex 站点封面加载优化

### ISSUE THREAD

**Issue by ScintillaH** [wgh136/PicaComic#305]
### 描述/Description

目前 App 初始 hosts 规则配置下无法直连加载 Ex 站点封面。在 rule 和 sni 中手动添加 `s.exhentai.org` 项目后可正常访问。建议将其加入到 App 初始配置中。

另外，希望优化 Eh 源的封面加载策略。目前浏览列表时封面加载速度较慢，似乎同时只会加载一张封面。

### 操作系统/Operating System

Android

**Comment by wgh136** [comment]
我不知道s.exhentai.org的ip地址
关于封面, 之前是并行请求, 经常出现`Connection terminated during handshake`错误, 经过我反复地测试, 发现只要并行请求就会有概率出现这个问题, 所以我把它改成这样了

**Comment by ScintillaH** [comment]
s.exhentai.org 的 IP 可以填 178.175.129.254，与 exhentai.org 一致
