### ISSUE TITLE
给下载分一个文件夹

### ISSUE THREAD

**Issue by zyzx201** [wgh136/PicaComic#306]
### 描述/Description

兄弟能不能像eh那样给下载分个文件夹.我下载的种类太多名字有的是日文搜索也难搞.拜托了兄弟

**Comment by wgh136** [comment]
你可以用本地收藏，在设置中把点击本地收藏时的行为改成阅读漫画，再把你的下载的漫画添加到本地收藏

zyzx201 ***@***.***> 于 2023年12月9日周六 17:18写道：
