### ISSUE TITLE
[Bug]: 安卓端Webdav只可上传不可下载

### ISSUE THREAD

**Issue by ParanoiaIsGreat** [wgh136/PicaComic#308]
### 描述/Description

Win端上传下载都正常

安卓端在使用同一个Webdav服务的情况下
上传无问题
但点击下载数据后，显示“Failed to sync data”

### Version

latest

### 使用的操作系统/Operating system

Android

**Comment by wgh136** [comment]
有个判断写错了, 已修复, 正在进行测试

**Comment by wgh136** [comment]
https://github.com/wgh136/PicaComic/releases/tag/v2.3.1-hotfix
windows端也要更新, 只是看起来工作正常, 实际上也存在问题
