### ISSUE TITLE
禁漫無法搜索

### ISSUE THREAD

**Issue by Jerry199022** [wgh136/PicaComic#310]
### 描述/Description

已登錄 看漫畫正常 收藏也正常 就是不能搜索

### Version

latest

### 使用的操作系统/Operating system

iOS

### 截图或视频/Screenshot or video

![EE6DC2E7-1CFC-4A6A-AF19-590A31C98E8E](https://github.com/wgh136/PicaComic/assets/146102835/94e3d528-89eb-4fa1-8740-8eb7141f8fe6)
![AEB873A6-C9B2-4034-B258-1CF19A45C130](https://github.com/wgh136/PicaComic/assets/146102835/6b2bbd02-2fd4-482f-ae39-34c1bd0f9d17)
![31F83E76-B223-4097-92F5-B7ED0DA94310](https://github.com/wgh136/PicaComic/assets/146102835/a1b72f52-61fc-4165-bf5d-4a0eaf607dd3)
![6D4D5E5D-B63D-4609-9F73-96293FFCA8A9](https://github.com/wgh136/PicaComic/assets/146102835/8f95f56c-38d8-495a-a323-979f3faa3a56)
](url)

**Comment by wgh136** [comment]
禁漫的cf验证很奇怪, 暂时不清楚原因, 建议是多换一下网络环境试试
