### ISSUE TITLE
[Bug]: 报错提示偶发性不超时消失

### ISSUE THREAD

**Issue by orzgithub** [wgh136/PicaComic#311]
### 描述/Description

如标题所述。
例如登录发生错误，连接重置时，原本预期应对显示几秒钟后超时消失的底部弹出提示无法消失。
由于界面未遮挡部分可以正常互动点击，判断应用整体并未卡住。
目前未找到稳定复现方式，在使用时随机出现，目前已触发多次该bug。只有安卓设备故无法测试其它平台表现。
另外，建议让更改使这个提示框不要遮挡下方控件触摸操作，允许点击穿透，或者至少能够手动点击关闭它。

### Version

latest

### 使用的操作系统/Operating system

Android

### 截图或视频/Screenshot or video

![截图](https://github.com/wgh136/PicaComic/assets/49035592/1d3893e1-bd7f-493f-a173-a02e451a23af)

**Comment by wgh136** [comment]
不清楚原因, v2.3.2做出了一些调整, 希望有些改善
