### ISSUE TITLE
[Bug]: 可能也不算bug，但是最近jm出现了如下情况

### ISSUE THREAD

**Issue by guest-zero** [wgh136/PicaComic#313]
### 描述/Description

上次更改了地址后就不要求验证了，但最近又开始这种情况，不知道是软件问题还是别的

### Version

latest

### 使用的操作系统/Operating system

Windows

### 截图或视频/Screenshot or video

![QQ截图20231213192406](https://github.com/wgh136/PicaComic/assets/133760269/a0039405-0732-4cc3-8d4e-239e096ae772)

**Comment by guest-zero** [comment]
今天又好了，奇怪

**Comment by wgh136** [comment]
禁漫的cf验证很奇怪, 有时候需要, 有时候始终不需要, 暂时不清楚原因
