### ISSUE TITLE
本地收藏丢失

### ISSUE THREAD

**Issue by Chilianxin** [wgh136/PicaComic#314]
### 描述/Description

今天打开偶然发现一个本地收藏变成了Null check operator used on a null value
本地收藏即使站点删了源应该保留有基本的信息吧？我想知道这个丢失的本是哪个需要怎么查看？

另外建议在历史记录搜索中加入一些筛选条件，比如来源站点，浏览时间等

### Version

latest

### 使用的操作系统/Operating system

Android

### 日志/logs

Null check operator used on a null value
#0      FavoriteItem.toDownloadId (package:pica_comic/foundation/local_favorites.dart:40)
#1      LocalFavoriteTile.badge (package:pica_comic/views/local_favorites_page.dart:194)
#2      ComicTile._buildDetailedMode (package:pica_comic/views/widgets/comic_tile.dart:164)
#3      ComicTile.build (package:pica_comic/views/widgets/comic_tile.dart:124)
#4      StatelessElement.build (package:flutter/src/widgets/framework.dart:5541)
#5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5471)
#6      Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#7      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#10     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#11     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6736)
#12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#13     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#14     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6736)
#15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#16     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#17     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#18     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#19     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#20     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#21     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5625)
#22     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#24     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#25     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#26     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#27     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#28     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#29     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#30     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#31     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#32     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#33     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#34     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#35     Element.inflateWidget (package:flutte...

**Comment by wgh136** [comment]
这个并不是丢失, 是显示错误, 等下次更新就好了
