### ISSUE TITLE
[Enhancement]: 希望可以调整顺序

### ISSUE THREAD

**Issue by suppermanzero** [wgh136/PicaComic#318]
### 描述/Description

希望可以调整默认页面的顺序，软件每次重新进入默认的进入是全部收藏夹，希望可以在这增加调整顺序，可以自由选择把本地建立的收藏夹一一排序；还可以参考一下其他人的软件，就像那个欢迎页，可以选择每次直接进入的是哪个页面，比如直接本地收藏，或者其他漫画源
![IMG_20231215_102033](https://github.com/wgh136/PicaComic/assets/151978274/e83e689e-ca04-4e26-ade6-7ae882104882)
![IMG_20231215_102510](https://github.com/wgh136/PicaComic/assets/151978274/0bb62b77-330e-400a-b862-061ab81b7ca0)

**Comment by suppermanzero** [comment]
就像排名一样，可以自由选择把新建的收藏夹排在前面或者后面就好了

**Comment by suppermanzero** [comment]
收藏夹自定义顺序不知道大佬能不能实现，本地收藏夹内调整顺序就挺厉害，如果上一级的收藏夹也可以自定义顺序调整的话，那就更方便了。

**Comment by suppermanzero** [comment]
或者像TG群这样，他那个群组的文件夹排序，可以随便调整顺序位置，调整完点完成就固定了，大佬可以参考参考
![IMG_20231215_112130](https://github.com/wgh136/PicaComic/assets/151978274/dd9cec4c-9651-439f-9f3d-04f6bb735ccf)

**Comment by wgh136** [comment]
改顺序有点麻烦, 但是设置默认打开的收藏夹很简单, 目前设置中不是有一个默认收藏夹吗, 就用那个吧
顺便提一下, "全部"收藏夹已经被我删了, 因为没什么意义

**Comment by suppermanzero** [comment]
> 改顺序有点麻烦, 但是设置默认打开的收藏夹很简单, 目前设置中不是有一个默认收藏夹吗, 就用那个吧 顺便提一下, "全部"收藏夹已经被我删了, 因为没什么意义

大佬那个顺序还有希望改吗，不行改一下那个默认的收藏夹，默认收藏夹不行啊，那个默认的只能第一次进去是自选的，退出再进就变成全部的了，除非点那个最右边的隐藏，但是又划又点那几下不是更麻烦了吗，因为在第二张图那，默认就是全部，在设置那选的默认收藏夹只支持从最外面点进去才是默认，不隐藏的话后续进多少次都还是默认全部的收藏夹
![IMG_20231215_122738](https://github.com/wgh136/PicaComic/assets/151978274/718208e6-b7a5-459a-981a-495e3d587fe0)
![IMG_20231215_122752](https://github.com/wgh136/PicaComic/assets/151978274/3079e9d0-a5a2-4f0a-926a-38ae2924a0c2)

**Comment by wgh136** [comment]
等下次更新

**Comment by suppermanzero** [comment]
> 改顺序有点麻烦, 但是设置默认打开的收藏夹很简单, 目前设置中不是有一个默认收藏夹吗, 就用那个吧 顺便提一下, "全部"收藏夹已经被我删了, 因为没什么意义

 大佬，设置里面那个默认收藏夹只能第一次点进去是自己选的那个，第二次那个界面不点隐藏不会回到第一个界面，也就是不管退出重进多少次，再进去的都还是全部的那个界面，而不是设置里设置的收藏夹

**Comment by suppermanzero** [comment]
> 等下次更新

下次更新那个默认收藏夹就能不管在哪个界面进去都生效了吗
