### ISSUE TITLE
[Bug]: jm搜索问题

### ISSUE THREAD

**Issue by 553531284** [wgh136/PicaComic#323]
### 描述/Description

1. 对于jm原本的组合搜索失效，例如“A +B”
2. 进入搜索页后切换排序规则没有生效

### Version

latest

### 使用的操作系统/Operating system

Android

**Comment by wgh136** [comment]
关于1, 我试了下并没有问题
![image](https://github.com/wgh136/PicaComic/assets/67669799/1d5b7e58-11ed-432b-ac39-24cf2a9f1cc3)
关于2, 将在下个版本修复

**Comment by 553531284** [comment]
> 关于1, 我试了下并没有问题 ![image](https://private-user-images.githubusercontent.com/67669799/291833087-1d5b7e58-11ed-432b-ac39-24cf2a9f1cc3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM5MjgyMTIsIm5iZiI6MTcwMzkyNzkxMiwicGF0aCI6Ii82NzY2OTc5OS8yOTE4MzMwODctMWQ1YjdlNTgtMTFlZC00MzJiLWFjMzktMjRjZjJhOWYxY2MzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMwVDA5MTgzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1YjYyZGU3YWY0YmI4NDhjNDkwOTgzYjExZjAwNDYxN2Q1YmI4MmUxYTQ4YmM4YzU0M2Q2MDU1ZGZmNGU3NzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qZ54_LAqwNdxuwX9wW4DqCI-zNsjkweJKDMmWniDK1E) 关于2, 将在下个版本修复

1有问题的，+前必须有空格。不加空格搜索效果会问题。你试下吧两个关键词颠倒下，结果都不一致了。

**Comment by 553531284** [comment]
点错，重开问题

**Comment by wgh136** [comment]
本app使用的是web接口, 只能实现禁漫网页有的功能
