### ISSUE TITLE
[Bug]: 禁漫无法读取到账户里收藏的列表

### ISSUE THREAD

**Issue by zerobird-0** [wgh136/PicaComic#324]
### 描述/Description

好久没看了，更新了后，我从网络收藏进去禁漫的收藏里列表是空的

### Version

latest

### 使用的操作系统/Operating system

Android

### 日志/logs

[logs.txt](https://github.com/wgh136/PicaComic/files/13692959/logs.txt)

**Comment by wgh136** [comment]
我看到你被禁漫反复地重定向, 建议换个域名试试

**Comment by zerobird-0** [comment]
目前退出账号后无法成功登录，收藏夹不知道能不能看，探索是可以的
