### ISSUE TITLE
[Enhancement]: 搜索框支持一键清空, 同时搜索页面提示已收藏以及阅读进度

### ISSUE THREAD

**Issue by luckyray-fan** [wgh136/PicaComic#325]
### 描述/Description

希望支持搜索框一键清空, 同时搜索页面提示已收藏以及阅读进度

### 图片/picture
<div style="display:inline-block">
  <img src="https://github.com/wgh136/PicaComic/assets/38815993/55403c0b-8144-4c6b-bb62-7c3c25efcd25" alt="image1" width="180">
  <img src="https://github.com/wgh136/PicaComic/assets/38815993/d2771f2b-bce7-44cf-bdb1-18c73ad0f6df" alt="image2" width="180">
</div>

![image](https://github.com/wgh136/PicaComic/assets/38815993/53345d78-4d2b-4d6b-8a73-81833d489c72)

**Comment by wgh136** [comment]
一键清空很简单
"提示已收藏以及阅读进度"有点问题, 目前的布局似乎没有位置能够放这个东西
