### ISSUE TITLE
[Enhancement]: Webdav增加已下载的本子信息

### ISSUE THREAD

**Issue by preBall** [wgh136/PicaComic#328]
### 描述/Description

希望在Webdav同步中增加已经下载过的本子的信息，手机系统扫描杀毒时自动把这个app给卸载了，我都来不及反应，之前的本子信息只剩下历史记录了，希望能增加这个功能。

### 操作系统/Operating System

Android

**Comment by wgh136** [comment]
有三种方式解决这个问题
1. 刷系统/换手机
2. 更改下载目录, 重新安装app后在设置中还原下载目录的设置即可还原下载内容
3. 使用本地收藏功能, 可以在已下载界面多选本子添加至本地收藏, 本地收藏会通过webdav同步
