### ISSUE TITLE
eh加载图片遇到 网络错误 安卓端

### ISSUE THREAD

**Issue by Vemon233** [wgh136/PicaComic#33]
首先感谢作者大大的app
在同一台安卓手机上，都是系统代理运行其他app如ehviewer是能够正常加载漫画的，而PicaComic在eh站加载图片会出现网络错误（其他站是没有问题的）， 换了很多节点也不行，能劳烦作者解答吗？感激不尽
版本是最新的1.6.6

**Comment by wgh136** [comment]
哪部漫画, 还是说都不能加载
如果画廊站点设置为exhentai.org, 必须登录并且有权限

**Comment by Vemon233** [comment]
哇，大佬回的好快，是全部不能加载，画廊站点ex和eh都不能加载

**Comment by wgh136** [comment]
这我也没办法知道原因, 下个版本给图片加载增加一个错误提示, 把错误原因显示出来

**Comment by Vemon233** [comment]
好的谢谢作者大大，如果很费时间就算了，我只用其他功能也可以的，谢谢谢谢

**Comment by Vemon233** [comment]
其实有时候会出现一些错误代码（而且错误代码很多都不一样，因为我试过挺多次），有时候是只有网络错误。但我没截图，等我之后截图发上来。

**Comment by wgh136** [comment]
现在增加了错误日志上传, 请更新到最新版, 然后再尝试访问
找到原因后, 我会进行修复

**Comment by wgh136** [comment]
仍然无法找到问题, 有人能提供更多信息吗

**Comment by Vemon233** [comment]
好的，我马上下载最新版，麻烦稍等，明天上传信息

**Comment by Vemon233** [comment]
emm，我安装了1.6.8之后eh站就能加载图片了，目前功能正常了，谢谢作者，也是很神奇

**Comment by Vemon233** [comment]
作者大大，我知道问题是怎么出现的了。
只要我登录我的eh账号，它就无法加载图片。重装之后不登陆就能够正常运行。（我试过几次）
然后我的账号应该没有问题，在其他app登录账号之后能够正常使用。
但是报错仍然不显示错误信息，只是显示网络错误。

**Comment by wgh136** [comment]
找到问题了，eh账号设置里有一个漫画详情页的缩略图大小，更改后导致网页布局发生变化，因此app解析html失败

**Comment by Vemon233** [comment]
牛的，感谢作者，期待更新
