### ISSUE TITLE
[Bug]: 切换到后台后再回来有概率黑屏卡死，只能重启软件

### ISSUE THREAD

**Issue by AIsouler** [wgh136/PicaComic#331]
### 描述/Description

切换到后台后再回来有概率黑屏卡死，只能重启软件

### Version

latest

### 使用的操作系统/Operating system

Android

### 日志/logs

[logs.txt](https://github.com/wgh136/PicaComic/files/13747799/logs.txt)

**Comment by AIsouler** [comment]
软件使用过程中也有概率卡死

**Comment by wgh136** [comment]
怀疑可能和hosts功能有关, 将会在下个版本进行一些调整
