### ISSUE TITLE
[Bug]: jm的收藏失败

### ISSUE THREAD

**Issue by Readedd** [wgh136/PicaComic#332]
### 描述/Description

其他功能一切正常，有且仅有收藏功能无法使用，已经尝试更换包括但不限于18comic，jmcomic1.me，等源

### Version

2.3.2 patch

### 使用的操作系统/Operating system

Android

### 日志/logs

Response https://jmcomic1.me/ajax/favorite_album 200
headers:
date: Fri, 22 Dec 2023 18:28:04 GMT
content-type: text/html; charset=UTF-8
expires: Thu, 19 Nov 1981 08:52:00 GMT
cache-control: no-store, no-cache, must-revalidate
pragma: no-cache
vary: Accept-Encoding
cf-cache-status: DYNAMIC
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=z8WAKKiP%2BanFHkdasjx2Ng%2BnCpVEhSdmb%2F%2F7cWNMJXYTAx%2FiPl2dGy0CEaEGyoEBupKN0XpO80lEYYV0Z1RIFxDQYwRgkDC26aAOd4eySn9wgGGgRw8TQTSP48%2F0OA%3D%3D"}],"group":"cf-nel","max_age":604800}
nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
server: cloudflare
cf-ray: 839a6c22696e4c83-SIN
alt-svc: h3=":443"; ma=86400

{"status":0,"msg":"<div class=\"alert alert-dismissable alert-danger m-b-15 m-t-0\"><button type=\"button\" class=\"close\" data-dismiss=\"alert\">\u00d7<\/button>\u6536\u85cf\u5df2\u6eff \uff01 <\/div>"}

### 截图或视频/Screenshot or video

无

**Comment by wgh136** [comment]
你的日志中有一串unicode编码的信息`\u6536\u85cf\u5df2\u6eff \uff01`, 表示"收藏已满"
