### ISSUE TITLE
[Bug]: bk下载前，如果不先进行阅读，那下载后会出现如下状况

### ISSUE THREAD

**Issue by guest-zero** [wgh136/PicaComic#333]
### 描述/Description

如标题所示，效果大概如下
![QQ截图20231223180131](https://github.com/wgh136/PicaComic/assets/133760269/e4b77b80-54b8-420b-8ddc-0a9e171a4891)

### Version

latest

### 使用的操作系统/Operating system

Windows

**Comment by wgh136** [comment]
更新至v2.3.2-patch
