### ISSUE TITLE
安卓14环境下，APP使用过程中，息屏后再亮屏，APP有概率黑屏

### ISSUE THREAD

**Issue by DrDzy01** [wgh136/PicaComic#335]
### 描述/Description

环境：小米hyperOS，K60，最新版系统，Android14
复现：打开APP，随意处在任意界面上，息屏，一段时间后亮屏（系统没有设置息屏后清理内存），APP会处在黑屏状态，只能强行退出

### Version

latest

### 使用的操作系统/Operating system

Android

**Comment by wgh136** [comment]
是否使用了hosts功能，测试发现使用此功能并在大量网络请求时会出现此问题

**Comment by DrDzy01** [comment]
> 是否使用了hosts功能，测试发现使用此功能并在大量网络请求时会出现此问题

使用了VPN，但没有使用APP内置的代理功能，为了避免出现未知问题，APP内的代理被完全关闭了。黑屏前确实正在阅读，可能确实在后台进行了网络请求。

**Comment by sunnysteam** [comment]
我也是这样，上划出去再回来就会黑，开了hosts
