### ISSUE TITLE
[Bug]: picacg漫画下载后出现画面失真

### ISSUE THREAD

**Issue by jayeew** [wgh136/PicaComic#336]
### 描述/Description

win10/安卓端，在picacg下载漫画，概率出现画面失真

### Version

latest

### 使用的操作系统/Operating system

Android, Windows

### 截图或视频/Screenshot or video

![Uploading 16.jpg…]()

**Comment by zyxhzyf** [comment]
的确出现了这个bug

**Comment by wgh136** [comment]
更新
