### ISSUE TITLE
[Enhancement]: 我看到一个第三方哔咔pc端可以搜索多个关键词，希望也能有这个功能

### ISSUE THREAD

**Issue by zhongsheng469** [wgh136/PicaComic#342]
### 描述/Description

https://github.com/tonquer/picacg-qt
这个第三方哔咔pc端的搜索可以 关键词空格加号另一个关键词 的这样搜索多个关键词，希望也能有这样的功能

**Comment by wgh136** [comment]
它是使用了一个本地的数据库实现的, 这个数据库占用的空间达到了91MB, 对于本项目来说, 很难接受
