### ISSUE TITLE
[Enhancemnt]: 是否可以将pica的网络收藏目录转存到本地收藏？

### ISSUE THREAD

**Issue by tikko-now** [wgh136/PicaComic#343]
### 描述/Description

是否可以将pica的网络收藏目录转存到本地收藏？就像是现在的jm里那个功能，pica没有文件夹，找本子一遍遍的加载太麻烦了

**Comment by wgh136** [comment]
对于没有收藏夹的漫画源, 直接在本地收藏中新建收藏夹, 然后点击从网络导入
