### ISSUE TITLE
[Bug]: 退出阅读黑屏

### ISSUE THREAD

**Issue by yezechuandl** [wgh136/PicaComic#350]
### 描述/Description

应该是在看一些章节数比较多的漫画时，时间比较长，退出阅读界面会出现黑屏的情况，半天没有反应。

### Version

latest

### 使用的操作系统/Operating system

Android

**Comment by yezechuandl** [comment]
又试了下，确定了，似乎就是在看的时候多次翻页（中途未退出阅读界面），大概看个三四章再退出就黑屏了。

**Comment by wgh136** [comment]
使用的是哪个版本, 我记得曾经修复过这个问题

**Comment by yezechuandl** [comment]
> 使用的是哪个版本, 我记得曾经修复过这个问题

最新版2.3.2-patch
