### ISSUE TITLE
[Bug]: 软件内禁漫搜索异常，返回500

### ISSUE THREAD

**Issue by Readedd** [wgh136/PicaComic#353]
### 描述/Description

除此之外一切正常，收藏阅读功能正常。其他平台的搜索也正常，有且仅有禁漫搜索异常。
浏览器访问官网正常

### Version

latest

### 使用的操作系统/Operating system

Android

### 日志/logs

DioException [bad response]: The request returned an invalid status code of 500.
#0      DioMixin.fetch.<anonymous closure> (package:dio/src/dio_mixin.dart:507)
#1      _rootRunUnary (dart:async/zone.dart:1407)
#2      _CustomZone.runUnary (dart:async/zone.dart:1308)
#3      _FutureListener.handleError (dart:async/future_impl.dart:180)
#4      Future._propagateToListeners.handleError (dart:async/future_impl.dart:858)
#5      Future._propagateToListeners (dart:async/future_impl.dart:879)
#6      Future._completeError (dart:async/future_impl.dart:655)
#7      _SyncCompleter._completeError (dart:async/future_impl.dart:63)
#8      _Completer.completeError (dart:async/future_impl.dart:27)
#9      Future.any.onError (dart:async/future.dart:618)
#10     _rootRunBinary (dart:async/zone.dart:1423)
#11     _CustomZone.runBinary (dart:async/zone.dart:1315)
#12     _FutureListener.handleError (dart:async/future_impl.dart:177)
#13     Future._propagateToListeners.handleError (dart:async/future_impl.dart:858)
#14     Future._propagateToListeners (dart:async/future_impl.dart:879)
#15     Future._completeError (dart:async/future_impl.dart:655)
#16     Future._chainForeignFuture.<anonymous closure> (dart:async/future_impl.dart:556)
#17     _rootRun (dart:async/zone.dart:1399)
#18     _CustomZone.run (dart:async/zone.dart:1301)
#19     _CustomZone.runGuarded (dart:async/zone.dart:1209)
#20     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249)
#21     _microtaskLoop (dart:async/schedule_microtask.dart:40)
#22     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49)

**Comment by wgh136** [comment]
禁漫的问题
目前是登录后无法搜索, 未登录时正常
