### ISSUE TITLE
[Bug]: 最近的下载有问题，不是乱码图就是缺图

### ISSUE THREAD

**Issue by tikko-now** [wgh136/PicaComic#354]
### 描述/Description

最近的下载有问题，不是乱码图就是缺图，，情况似乎是最新的发行版出行的
![image](https://github.com/wgh136/PicaComic/assets/94343527/567f9a80-14e8-4d3c-b478-b22fc92b7a3b)
![image](https://github.com/wgh136/PicaComic/assets/94343527/f488dc99-d811-47d3-9410-abf0e9ca83a0)

### Version

latest2.3.2

### 使用的操作系统/Operating system

Android, Windows

### 日志/logs

[logs.txt](https://github.com/wgh136/PicaComic/files/13887990/logs.txt)

**Comment by wgh136** [comment]
更新
https://github.com/wgh136/PicaComic/releases/tag/v2.3.2
