### ISSUE TITLE
[Enhancement]: 希望改进一下内置代理的逻辑

### ISSUE THREAD

**Issue by maxshiro** [wgh136/PicaComic#364]
### 描述/Description

当我添加了代理地址保存后退出，临时关闭时再打开已经填好的代理地址会消失。
附图是jhentai的内置代理选择器，可以选择对应的代理方式并保存。
另外可以给每个源都加上代理的开关，ehentai用机场的话很容易被ban，加上单独控制的话就可以单独给ehentai设代理。

### 操作系统/Operating System

Android

### 图片/picture

![Screenshot_20240117_085654](https://github.com/wgh136/PicaComic/assets/20143941/ecc73a02-8045-433e-96e4-807ab17249df)

**Comment by wgh136** [comment]
我认为"临时关闭时再打开已经填好的代理地址会消失"不存在问题, 代理的设置并不是什么麻烦的事情, 也就很短的一行文本
目前没办法实现socks代理, 因为禁漫必须使用http2请求, dart的http2库仅支持http代理
就目前的代码结构来说, 每个源提供一个代理非常麻烦, 因此不打算做
