### ISSUE TITLE
[Bug]: 关于删除网络收藏

### ISSUE THREAD

**Issue by newbe007** [wgh136/PicaComic#367]
### 描述/Description

删除全部网络收藏后，网络收藏管理页面出错

### Version

latest

### 使用的操作系统/Operating system

Android

### 日志/logs

Null check operator used on a null value
#0      _MultiPagesFilterState.buildItem (package:pica_comic/views/settings/multi_pages_filter.dart:66)
#1      _MultiPagesFilterState.build.<anonymous closure> (package:pica_comic/views/settings/multi_pages_filter.dart:40)
#2      MappedIterable.elementAt (dart:_internal/iterable.dart:385)
#3      ListIterator.moveNext (dart:_internal/iterable.dart:354)
#4      new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189)
#5      new _GrowableList.of (dart:core-patch/growable_array.dart:150)
#6      new List.of (dart:core-patch/array_patch.dart:39)
#7      ListIterable.toList (dart:_internal/iterable.dart:224)
#8      _MultiPagesFilterState.build (package:pica_comic/views/settings/multi_pages_filter.dart:40)
#9      StatefulElement.build (package:flutter/src/widgets/framework.dart:5583)
#10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5471)
#11     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#12     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#13     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#14     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5625)
#15     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#16     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#17     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#18     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6736)
#19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#20     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#22     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#23     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#24     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#25     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#26     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#27     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6736)
#28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#29     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#30     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6736)
#31     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#32     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#33     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#34     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#35     Element.rebuild (package:flutter/s...

### 截图或视频/Screenshot or video

![Screenshot_2024-01-20-13-21-40-713_com github wgh136 pica_comic](https://github.com/wgh136/PicaComic/assets/104706611/ca56f68c-08e5-4f5e-9e12-d2da59fc5a78)

**Comment by wgh136** [comment]
与 #358 重复
