### ISSUE TITLE
[Feature Request]探索页面增加缩略图的布局

### ISSUE THREAD

**Issue by akschy** [wgh136/PicaComic#368]
### 描述/Description

列表的形式对探索这个页面来说效率有点低，可不可以增加一个类似彩e的缩略图布局

### 操作系统/Operating System

Android, Windows

**Comment by wgh136** [comment]
这是已有的功能, 在设置里面改

**Comment by akschy** [comment]
是漫画块大小嘛？

**Comment by akschy** [comment]
找到了，是漫画块显示模式
