### ISSUE TITLE
请问考虑提供iOS ipa包吗

### ISSUE THREAD

**Issue by alphavvv** [wgh136/PicaComic#37]

**Comment by wgh136** [comment]
需要一些时间, 部分功能是使用原生代码实现的

**Comment by Vemon233** [comment]
如果可以的话希望加入ios支持，感觉这个app真的很赞，赞美作者

**Comment by wgh136** [comment]
现在提供了ipa包, 但是由于缺乏测试条件, 可能存在问题

**Comment by alphavvv** [comment]
用轻松签自签显示「未找到.app文件」
![image](https://github.com/wgh136/PicaComic/assets/83694637/f259e260-f290-451e-9c1c-1f19975a978b)

**Comment by wgh136** [comment]
打包的时候弄错了, 已重新上传
