### ISSUE TITLE
[Bug]: 下载页面数量与显示不符

### ISSUE THREAD

**Issue by guest-zero** [wgh136/PicaComic#371]
### 描述/Description

从已下载下面看是72本，但进入页面后仅有70本。最新的均来自e站
同时希望下载和搜索后的页面能添加翻页功能，每50做一页会好一点；以及各软件之间还是统一一下好，jm和哔咔两个都是作者名，但到了别的类似e或者绅士则变成了上传者在作者的位置

### Version

latest

### 使用的操作系统/Operating system

Windows

### 截图或视频/Screenshot or video

![Uploading QQ截图20240126010307.png…]()

**Comment by guest-zero** [comment]
![Uploading QQ截图20240126010307.png…]()

**Comment by guest-zero** [comment]
图片出了点问题
![1 (1)](https://github.com/wgh136/PicaComic/assets/133760269/1bf44c29-9b11-461b-9943-00ac20707942)
![1 (2)](https://github.com/wgh136/PicaComic/assets/133760269/3b82f44e-3c1a-4230-a3a6-0c67a8090f07)
![1 (3)](https://github.com/wgh136/PicaComic/assets/133760269/a4f4f7cf-3040-4745-a692-208c519d734e)
![1 (4)](https://github.com/wgh136/PicaComic/assets/133760269/2e9c91cf-35c1-40ed-a28c-7f2cb725baae)
![1 (5)](https://github.com/wgh136/PicaComic/assets/133760269/2d912a43-ee05-4a4c-b9f6-c92153487c34)
![1 (6)](https://github.com/wgh136/PicaComic/assets/133760269/133fa15b-c3bc-4767-ab4a-82c42190484a)
![1 (7)](https://github.com/wgh136/PicaComic/assets/133760269/c91f3598-0c9f-4eee-a161-65f02ec74a0c)
![1 (8)](https://github.com/wgh136/PicaComic/assets/133760269/b9218afd-fac7-4127-8b08-fc4c30db595c)
![1 (9)](https://github.com/wgh136/PicaComic/assets/133760269/427bf1b7-c18a-431d-a906-190452ac6d54)
![1 (1)](https://github.com/wgh136/PicaComic/assets/133760269/1bf44c29-9b11-461b-9943-00ac20707942)
![1 (2)](https://github.com/wgh136/PicaComic/assets/133760269/3b82f44e-3c1a-4230-a3a6-0c67a8090f07)

**Comment by wgh136** [comment]
安装这个再看看下载页面的数量是否一致: https://github.com/wgh136/PicaComic/releases/tag/v2.3.4
关于作者名, 如果有, 当然能够显示, 但是e站的漫画列表里面没有作者信息, 只有上传者信息, 因此没办法

**Comment by guest-zero** [comment]
@wgh136 可以了，现在一致了
