### ISSUE TITLE
[Bug]: Nhentai在pc端的登录问题

### ISSUE THREAD

**Issue by ldqs365** [wgh136/PicaComic#372]
### 描述/Description

Nhentai在pc端调用的webview登录，但是如果不开启系统代理，webview会一直卡白屏，开启系统代理，就可以登录了，希望可以让webview走自定义代理

### Version

latest

### 使用的操作系统/Operating system

Windows

**Comment by wgh136** [comment]
windows的webview没有提供代理配置
