### ISSUE TITLE
禁漫的相关推荐出了点问题

### ISSUE THREAD

**Issue by jogGUY** [wgh136/PicaComic#38]
点击禁漫的任意漫画的相关推荐中任意一本漫画都无法跳转到其对应的详细页面，而点击长按漫画弹出的菜单的“查看详细”也是没有任何响应，这个菜单的“收藏/取消收藏”倒是没有出问题。

**Comment by wgh136** [comment]
添加弹出菜单的时候不小心改错了
奇怪, 怎么每天都有不得不修的bug, 每天都发一个版本是不是不太好

**Comment by wgh136** [comment]
已完成
