### ISSUE TITLE
希望webdav增加本地收藏同步功能

### ISSUE THREAD

**Issue by 2375399351** [wgh136/PicaComic#398]
### 描述/Description

和导出用户数据一样，可以把本地所有数据包括已下载项目都同步到webdav服务器

**Comment by wgh136** [comment]
本地收藏有同步，已下载项目同步并不是一个好的选择

**Comment by 2375399351** [comment]
> 本地收藏有同步，已下载项目同步并不是一个好的选择

主要是服务器资源可能会失效

**Comment by wgh136** [comment]
较大规模数据的同步是很麻烦的事情，我不打算做，你可以手动备份或者借助某些同步软件
