### ISSUE TITLE
找不到key.properties这个文件？

### ISSUE THREAD

**Issue by jasonhui512** [wgh136/PicaComic#4]
FAILURE: Build failed with an exception.

* Where:
Build file 'D:\flutter\PicaComic\android\app\build.gradle' line: 30

* What went wrong:
A problem occurred evaluating project ':app'.
> D:\flutter\PicaComic\android\key.properties (ϵͳ�Ҳ���ָ�����ļ���)

**Comment by wgh136** [comment]
key.properties文件储存了证书位置和密码, 不可能上传到Github
如果你想要自己打包app, 请自己生成一个证书, 然后建一个key.properties文件, 写上相关信息

**Comment by jasonhui512** [comment]
是哦，但如果只想用调试模式启动的话也不行？

**Comment by wgh136** [comment]
把PicaComic\android\app\build.gradle里面的28-30行,67-81行删掉就行了

**Comment by jasonhui512** [comment]
好了
