### ISSUE TITLE
反馈一下，可能不一定算bug

### ISSUE THREAD

**Issue by guest-zero** [wgh136/PicaComic#40]
嗯，目前禁漫下载恢复了，但是整体下载速度好像慢了，可能是我网速问题。
比起这个，现在已下载界面好像下到一定程度的漫画后，会卡在加载中界面，重启后也是一样

**Comment by wgh136** [comment]
目前是单线程下载，有时间了做个多线程
卡住是数据读取出现了问题，已经看到错误日志了，有个漫画的作者信息读取出错

**Comment by wgh136** [comment]
已修复
