### ISSUE TITLE
[Bug]: 同一部漫画，浏览器可以看，PicaComic就报错Exception: Invalid image data

### ISSUE THREAD

**Issue by chuwza** [wgh136/PicaComic#400]
### 描述/Description

同样一部漫画，浏览器是可以正常浏览的，PicaComic就报错Exception: Invalid image data（不是配额到上限了，因为浏览器就能正常看）

### Version

latest

### 使用的操作系统/Operating system

Android

### 日志/logs

Exception: Invalid image data
#0      _futurize (dart:ui/painting.dart:6959)
#1      ImageDescriptor.encoded (dart:ui/painting.dart:6773)
#2      instantiateImageCodecWithSize (dart:ui/painting.dart:2307)
#3      PaintingBinding.instantiateImageCodecWithSize (package:flutter/src/painting/binding.dart:141)
#4      BaseImageProvider._loadBufferAsync (package:pica_comic/foundation/image_loader/base_image_provider.dart:46)
<asynchronous suspension>
#5      MultiFrameImageStreamCompleter._handleCodecReady (package:flutter/src/painting/image_stream.dart:969)
<asynchronous suspension>

### 截图或视频/Screenshot or video

![Screenshot_20240229-100910_Kiwi_Browser](https://github.com/wgh136/PicaComic/assets/30049891/16c7f4be-cf59-4d8e-8578-21eacc07113c)
![Screenshot_20240229-100916_Pica_Comic](https://github.com/wgh136/PicaComic/assets/30049891/e81b4638-b392-4a92-ad66-aa1b5ed4f71e)

**Comment by wgh136** [comment]
需要更完整的日志，我需要知道Exception: Invalid image data之前发生了什么，建议使用导出日志功能

**Comment by chuwza** [comment]
> 需要更完整的日志，我需要知道Exception: Invalid image data之前发生了什么，建议使用导出日志功能

好的，这是日志
[logs.txt](https://github.com/wgh136/PicaComic/files/14442126/logs.txt)

**Comment by chuwza** [comment]
> 需要更完整的日志，我需要知道Exception: Invalid image data之前发生了什么，建议使用导出日志功能

好的，这是日志，我先清空了日志，然后强行停止PicaComic，然后清除缓存，再点开漫画报错，然后导出的
[logs.txt](https://github.com/wgh136/PicaComic/files/14442144/logs.txt)

**Comment by wgh136** [comment]
> > 需要更完整的日志，我需要知道Exception: Invalid image data之前发生了什么，建议使用导出日志功能
> 
> 好的，这是日志，我先清空了日志，然后强行停止PicaComic，然后清除缓存，再点开漫画报错，然后导出的 [logs.txt](https://github.com/wgh136/PicaComic/files/14442144/logs.txt)

确定操作没有问题吗，你这里面全是Invalid image data

**Comment by chuwza** [comment]
> > > 需要更完整的日志，我需要知道Exception: Invalid image data之前发生了什么，建议使用导出日志功能
> > 
> > 
> > 好的，这是日志，我先清空了日志，然后强行停止PicaComic，然后清除缓存，再点开漫画报错，然后导出的 [logs.txt](https://github.com/wgh136/PicaComic/files/14442144/logs.txt)
> 
> 确定操作没有问题吗，你这里面全是Invalid image data

操作应该没有问题吧，可能是我预加载得数量设置成了15，并且阅读模式是从上到下（连续），所以产生了大量的错误？

**Comment by wgh136** [comment]
这样，你重新按照你说的操作去做，但是进阅读器后不要进行任何操作，出现错误后就退出阅读器然后导出日志
app限制了最多400条日志

**Comment by chuwza** [comment]
> 这样，你重新按照你说的操作去做，但是进阅读器后不要进行任何操作，出现错误后就退出阅读器然后导出日志 app限制了最多400条日志

大佬你好，我重新安装了一下，发现问题了在哪了😂，只要给e站开了优先加载原图，就会报这个错，所以是这个选项的问题。这个选项具体作用是什么呢？开了会更加清晰吗？（因为我开了就会加载不出图，所以我也没法测试这个选项）

**Comment by chuwza** [comment]
> 这样，你重新按照你说的操作去做，但是进阅读器后不要进行任何操作，出现错误后就退出阅读器然后导出日志 app限制了最多400条日志

大佬好，原来问题在这里，我之前不知道，现在用浏览器测试发现发现exhentai加载原图需要GP，我没有GP，就报错了Downloading original files of this gallery requires GP, and you do not have enough. 所以能不能e-hentai就加载原图，exhentai识别到没有GP，自动降级至非原图呢？
