### ISSUE TITLE
[Bug]: 禁漫下载到了一定页数后无法继续下载

### ISSUE THREAD

**Issue by guest-zero** [wgh136/PicaComic#402]
### 描述/Description

如标题所言，希望修复
![QQ截图20240302134702](https://github.com/wgh136/PicaComic/assets/133760269/cfa405be-1ee3-4ec2-95b3-7d4829e4a641)

### Version

latest

### 使用的操作系统/Operating system

Windows

**Comment by guest-zero** [comment]
正常阅读不会出现卡页的情况，哔咔还没测试，也许也有问题，但哔咔之前出现过部分页加载错误，无法刷新的问题，简单点说就是哔咔那边是下载页数和实际页数不符

**Comment by wgh136** [comment]
https://api.wgh136.xyz/static/v3.0.0-dev2.exe
先删除下载任务, 然后安装这个测试版试试

**Comment by guest-zero** [comment]
可以了，不过你准备大更到3.0版本了吗，难怪这么久没更新，辛苦了

**Comment by KingOfBlingBling** [comment]
> https://api.wgh136.xyz/static/v3.0.0-dev2.exe 先删除下载任务, 然后安装这个测试版试试

大佬，apk也是，下载到最后三张就不显示
