### ISSUE TITLE
[Bug]: jm的下载不知道为什么总是剩下3张下不下来，换了个本子试也一样

### ISSUE THREAD

**Issue by tikko-now** [wgh136/PicaComic#407]
### 描述/Description

jm的下载不知道为什么总是剩下3张下不下来，换了个本子试也一样
![image](https://github.com/wgh136/PicaComic/assets/94343527/ff3d3f79-a45d-4cad-b7cb-f440e848dcfe)

### Version

latest2.3.5

### 使用的操作系统/Operating system

Windows

### 截图或视频/Screenshot or video

![image](https://github.com/wgh136/PicaComic/assets/94343527/09664fbd-6916-4266-a45e-631bf34a5c0b)

**Comment by wgh136** [comment]
与 #402 重复
