### ISSUE TITLE
为本地目录添加.nomedia

### ISSUE THREAD

**Issue by DrDzy01** [wgh136/PicaComic#409]
### 描述/Description

当下载目录改为自定义目录后，会在相册中显示下载内容，建议为所有本地目录添加.nomedia文件

**Comment by wgh136** [comment]
无论下载目录设置在哪里都会创建.nomedia文件

**Comment by DrDzy01** [comment]
> 无论下载目录设置在哪里都会创建.nomedia文件

如果先使用默认目录，下载足量内容后修改目录并转移到公开目录中，这个过程不会创建.nomedia

**Comment by wgh136** [comment]
没试过，但是每次app启动时都会检测有没有创建，因此不存在这个问题
