### ISSUE TITLE
安卓横屏后，希望可以铺满全屏

### ISSUE THREAD

**Issue by ye6fan** [wgh136/PicaComic#411]
### 描述/Description

横屏后虽然可以放大，但是无法全屏，且滑动时会左右摇摆

### 操作系统/Operating System

Android

### 图片/picture

![demo](https://github.com/wgh136/PicaComic/assets/83660373/cf53206c-094b-49d5-85a0-74a36d67b9e7)

**Comment by sumaxiyan** [comment]
怎么登录的啊

**Comment by ye6fan** [comment]
[首先你要有漫画官方的账号，没有去注册一个，[JMComic](https://18comic.vip/signup)

**Comment by wgh136** [comment]
关闭阅读设置中的限制图片最大显示宽度
