### ISSUE TITLE
[Enhancement]: 希望工具栏和信息栏可以交换位置

### ISSUE THREAD

**Issue by AIsouler** [wgh136/PicaComic#412]
### 描述/Description

工具栏操作频率比较高，放在上面用大拇指操作很不方便，而且工具栏有很大的空白空间没有利用上，可以让按钮变大一点
现在工具栏的收藏按钮看不出是否收藏了该漫画，我记得上个版本是可以的，希望能优化一下

### 图片/picture

![Screenshot_2024-03-10-21-36-39-854_com github wgh136 pica_comic-edit](https://github.com/wgh136/PicaComic/assets/57941037/b00d51ba-986b-495e-9035-aa913fadb50b)

**Comment by gankumangcao** [comment]
我倒觉得工具栏在上面好，别的软件也是工具栏在上面，变了反而不适应，反对票+1
