### ISSUE TITLE
[Bug]: eh无法搜索

### ISSUE THREAD

**Issue by lancer-wang** [wgh136/PicaComic#413]
### 描述/Description

eh搜索任何关键词都是 Exception：empty data

### Version

latest

### 使用的操作系统/Operating system

iOS

### 截图或视频/Screenshot or video

![](https://image.azurebest.eu.org/file/170dfe23947ba994216e2.png)

**Comment by lancer-wang** [comment]
准确来说，用的漫画源是ex

**Comment by wgh136** [comment]
你需要同时有ex的访问权限和正确的cookie

**Comment by lancer-wang** [comment]
> 你需要同时有ex的访问权限和正确的cookie

找到了，是igneous过期了。。。
