### ISSUE TITLE
添加新内容

### ISSUE THREAD

**Issue by PostQing** [wgh136/PicaComic#414]
### 描述/Description

希望大佬能够把pixiv也添加进来

### 图片/picture

![Screenshot_2024-03-12-00-35-42-889_jp pxv android](https://github.com/wgh136/PicaComic/assets/163023381/eff790a4-cc60-44ea-a8bc-07b0ddbe99f5)

**Comment by wgh136** [comment]
本app的逻辑并不适合pixiv
