### ISSUE TITLE
关于漫画源的建议

### ISSUE THREAD

**Issue by xingluo233** [wgh136/PicaComic#418]
### 描述/Description

既然代码都是用js写的，那为什么要用toml文件呢，为何不直接用js文件，那些漫源信息都存在变量里面，需要的功能写一个函数实现

下图是某个软件的书源示例

### 图片/picture

![Screenshot_2024-03-14-12-08-34-720_com fhzm funread five](https://github.com/wgh136/PicaComic/assets/54618947/9a855e6c-0f10-40b4-9334-bc77d6a06a7a)
![Screenshot_2024-03-14-12-08-44-027_com.fhzm.funread.five.jpg](https://github.com/wgh136/PicaComic/assets/54618947/b0a4f8ae-6306-45df-84ca-22157278b4f3)

**Comment by wgh136** [comment]
因为我喜欢, 这两种方式并不存在优劣
