### ISSUE TITLE
[Bug]: 筛选语言失效

### ISSUE THREAD

**Issue by tdxh9688** [wgh136/PicaComic#422]
### 描述/Description

在nhentai搜索时筛选语言功能失效，选择了中文，但是搜索结果还是有其他语言；并且希望搜索其他目标源时也能添加筛选语言功能

### Version

latest

### 使用的操作系统/Operating system

iOS

**Comment by wgh136** [comment]
筛选语言功能只是自动向搜索关键词中添加了语言, 如果搜索结果还是有其他语言, 只能认为是漫画源的问题
