### ISSUE TITLE
[Bug]: 绅士漫画网络收藏没有把书架加进去

### ISSUE THREAD

**Issue by suppermanzero** [wgh136/PicaComic#426]
### 描述/Description

绅士漫画软件内收藏夹没把官网的书架合并，到官网书架去看收藏跟软件内不一样，书架内只有一个漫画，而软件内的绅士漫画网络收藏是全版本的，有58个，请大佬看一下扎哈维，之前版本还正常呢

### Version

latest

### 使用的操作系统/Operating system

Android

**Comment by wgh136** [comment]
测试并无问题
