### ISSUE TITLE
问题与意见

### ISSUE THREAD

**Issue by qa12587** [wgh136/PicaComic#43]
设置漫画源这里，设置好之后再重新打开软件又恢复原样。上面这些有些分类用不到能不能加个隐藏功能
https://ibb.co/xF52psg

**Comment by qa12587** [comment]
![Uploading IMG_20230527_104054.jpg…]()

**Comment by qa12587** [comment]
![Uploading IMG_20230527_104054.jpg…]()

**Comment by wgh136** [comment]
为什么要不停地开关issue
将会在下个版本修复没有保存设置的问题，用不到的分类可以通过关闭漫画源方式隐藏

**Comment by qa12587** [comment]
因为发图片不显示，所以就变这样了

**Comment by qa12587** [comment]
举个例子，有EH主页和热门，我想隐藏主页留热门所以才提这个意见

**Comment by wgh136** [comment]
确实有必要，将在下个版本进行调整

________________________________

**Comment by wgh136** [comment]
完成
