### ISSUE TITLE
[Enhancement]: 左上角菜单建议

### ISSUE THREAD

**Issue by mx41shy** [wgh136/PicaComic#438]
### 描述/Description

使用左上角菜单打开画面，例如打开设置画面，重复该操作3次，然后退出设置画面时也需要退出3次。
使用左上角菜单打开画面相当于打开新标签页，但是打开的标签页并没有在标题栏显示，希望可以显示出来。

### 操作系统/Operating System

Windows

### 图片/picture

![image](https://github.com/wgh136/PicaComic/assets/16437280/28a78dc7-23f0-4229-9ee1-b0cdd92dab29)

**Comment by wgh136** [comment]
> 相当于打开新标签页

这是路由堆栈, 不是新标签页, 在目前的代码结构下, 很难实现查看路由堆栈顶部的页面的信息
