### ISSUE TITLE
希望添加默认开屏主页选项

### ISSUE THREAD

**Issue by misaka-13766** [wgh136/PicaComic#44]
您好，首先感谢您一直以来不辞辛劳的开发，我也向很多人安利了这款应用。

但是这边想提个小建议。目前开屏主页是“我的”，无法直接打开软件就能浏览到最近更新的本子。希望能够提供一个默认主页的选择，让大家有更多的选择权。

就这个小建议了，谢谢，祝好！:)

**Comment by wgh136** [comment]
感谢建议，将在下个版本加入此功能

**Comment by misaka-13766** [comment]
太感谢啦www
