### ISSUE TITLE
[Enhancement]: 希望增加批量导出已下载漫画功能

### ISSUE THREAD

**Issue by ray4b** [wgh136/PicaComic#448]
### 描述/Description

目前已下载的菜单里一次只允许导出一个漫画，无法批量选择漫画并一键导出，希望后续版本能增加相关功能。批量导出不一定需要打包成压缩包再导出，可以以多个文件夹并以图片或pdf形式导出在所选文件夹内。

### 操作系统/Operating System

Android, Windows

**Comment by wgh136** [comment]
"打包成压缩包"是必要的, 因为app不一定有完整的读写储存的权限, 只能走系统api, 部分系统只提供了保存单个文件的api, 因此只能这样做
