### ISSUE TITLE
[Bug]: 更新之后禁漫动画打不开了

### ISSUE THREAD

**Issue by ypq123456789** [wgh136/PicaComic#452]
### 描述/Description

之前禁漫是可以打开的，更新之后打不开了。关闭了host，网络环境是自建代理。

### Version

latest

### 使用的操作系统/Operating system

Android

### 日志/logs

RangeError (length): Invalid value: Not in inclusive range 0..3: 4
#0      JmNetwork.baseUrl (package:pica_comic/network/jm_network/jm_network.dart)
#1      JmNetwork.getHomePage (package:pica_comic/network/jm_network/jm_network.dart:214)
#2      JmHomePageLogic.getData (package:pica_comic/views/jm_views/jm_home_page.dart:23)
#3      JmHomePage.build.<anonymous closure> (package:pica_comic/views/jm_views/jm_home_page.dart:48)
#4      StateBuilder.builderWrapped (package:pica_comic/foundation/state_controller.dart:118)
#5      _StateBuilderState.build (package:pica_comic/foundation/state_controller.dart:166)
#6      StatefulElement.build (package:flutter/src/widgets/framework.dart:5592)
#7      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5480)
#8      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
#9      Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#10     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
#11     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5634)
#12     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
#13     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
#14     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
#15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#16     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#17     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
#18     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
#19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
#20     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
#21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#22     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#23     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
#24     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
#25     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
#26     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
#27     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6758)
#28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
#29     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
#30     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6758)
#31     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
#32     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
#33     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#34     StatefulElement.performRebuild (package:flutter/src/widg...

**Comment by wgh136** [comment]
旧数据导致的问题, 清数据或者等下次更新
