### ISSUE TITLE
[Bug]: eh报错

### ISSUE THREAD

**Issue by ypq123456789** [wgh136/PicaComic#457]
### 描述/Description

切换自建节点都不行，之前登录eh都可以的，应该是最近的更新导致的

### Version

latest

### 使用的操作系统/Operating system

Android

### 日志/logs

[logs.txt](https://github.com/wgh136/PicaComic/files/14832067/logs.txt)

### 截图或视频/Screenshot or video

![Screenshot_20240402_134617_com github wgh136 pica](https://github.com/wgh136/PicaComic/assets/114487221/55030214-6fc9-4d9b-9749-0804cd98f8a2)

**Comment by wgh136** [comment]
重新登录

**Comment by ypq123456789** [comment]
解决了，感谢。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月2日(周二) 中午1:53
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [wgh136/PicaComic] [Bug]: eh报错 (Issue #457)




 
重新登录
