### ISSUE TITLE
[Bug]: 作者大大，禁漫的收藏失效

### ISSUE THREAD

**Issue by zekai-aini** [wgh136/PicaComic#458]
### 描述/Description

在禁漫官网上收藏的漫画可以在app上看到，在app上新收藏的漫画虽然显示已成功收藏到“网络”——“全部收藏”中，但是到收藏中却看不到该漫画，返回漫画详情页“已收藏”按钮又变回“收藏”按钮（开没开梯子都是一样的）

### Version

latest

### 使用的操作系统/Operating system

Android

### 日志/logs

GET https://www.jmapinodeudzn.xyz/favorite?
headers:
{token: 1beedaea3850fe1cb28e2a7275ae7ef3, tokenparam: 1712046074,1.6.8, user-agent: Mozilla/5.0 (Linux; Android 13; 012345678 Build/TQ1A.230305.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/114.0.5735.196 Safari/537.36, accept-encoding: gzip, Host: www.jmapinodeudzn.xyz, cookie: ipcountry=CN; ipm5=517793ecd6abfb67d12491fdbac1f553; AVS=ehblai2sp1atvcids8vtaktb60; remember_id=deleted; __cflb=0H28vXTt7XwkcM8Fr48hRnw5qchxwDnCCqrNTKEsq2k}
data:null

Response https://www.jmapinodeudzn.xyz/favorite 200
headers:
{connection: keep-alive, cache-control: no-store, no-cache, must-revalidate, last-modified: Tue, 02 Apr 2024 08:21:17 GMT, date: Tue, 02 Apr 2024 08:21:17 GMT, vary: Accept-Encoding, content-encoding: gzip, cf-cache-status: DYNAMIC, report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v4?s=PNACZxZGnjnbsK5PCsqLyEswrFzquM5cTXh1tozvu40fk4K8pzweOCi%2FD3%2B0hrAXkAVVg7fQZO3axrSoEYNUApk2O64gtBXazZBl2zkGVojFXI%2FGxGtDRk2QkLotsS10Crq%2Fi%2FZ60w%3D%3D"}],"group":"cf-nel","max_age":604800}, pragma: no-cache, content-type: application/javascript; charset=utf-8;, server: cloudflare, content-length: 130, nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}, cf-ray: 86df678d7f543b35-IAD, expires: Thu, 19 Nov 1981 08:52:00 GMT}
[123, 34, 99, 111, 100, 101, 34, 58, 50, 48, 48, 44, 34, 100, 97, 116, 97, 34, 58, 34, 55, 103, 120, 109, 68, 70, 98, 100, 102, 101, 66, 88, 43, 88, 90, 115, 109, 56, 51, 74, 51, 56, 121, 121, 65, 52, 106, 89, 105, 97, 115, 82, 82, 53, 66, 70, 88, 72, 72, 122, 101, 48, 80, 90, 109, 88, 79, 101, 101, 79, 56, 86, 52, 90, 88, 65, 105, 54, 76, 101, 98, 87, 79, 90, 75, 73, 82, 108, 48, 77, 74, 83, 113, 78, 74, 87, 117, 103, 67, 98, 71, 53, 76, 111, 100, 65, 61, 61, 34, 125]

**Comment by zekai-aini** [comment]
绅士漫画的漫画也没有办法收藏

**Comment by zekai-aini** [comment]
pika正常

**Comment by zekai-aini** [comment]
发现禁漫收藏失败可能是因为已达上限，但是无法取消收藏

**Comment by zekai-aini** [comment]
实验发现，网页端绅士漫画官网可以正常收藏漫画，app内收藏为空，且无法新增收藏

**Comment by xoevdv** [comment]
我这找到个新BUG，禁漫天堂我在网页版取消收藏后，在APP内仍然会显示，不会消息，看收藏按钮那已经从“已收藏”变为“收藏”，可见网页端成功取消，但是APP内并未消失

**Comment by xoevdv** [comment]
我这找到个新BUG，禁漫天堂我在网页版取消收藏后，在APP内仍然会显示，不会消失，看收藏按钮那已经从“已收藏”变为“收藏”，可见网页端成功取消，但是APP内并未消失

**Comment by wgh136** [comment]
> 我这找到个新BUG，禁漫天堂我在网页版取消收藏后，在APP内仍然会显示，不会消失，看收藏按钮那已经从“已收藏”变为“收藏”，可见网页端成功取消，但是APP内并未消失

这个应该是jm的问题

**Comment by zekai-aini** [comment]
作者你好，这个绅士漫画的收藏是什么原因呢？app上面不显示绅士漫画的收藏内容
