### ISSUE TITLE
[Bug]: 网络收藏夹

### ISSUE THREAD

**Issue by xoevdv** [wgh136/PicaComic#459]
### 描述/Description

禁漫天堂网络收藏夹，这APP内取消收藏失败，虽然显示取消成功，但是重新进入还是存在；绅士漫画网络收藏夹是空白，重新登录账号仍然是空白，并且无法收藏到网络收藏

### Version

latest

### 使用的操作系统/Operating system

Android

**Comment by wgh136** [comment]
请不要提出重复的内容

**Comment by xoevdv** [comment]
> 请不要提出重复的内容

不好意思，那我这找到个新BUG，禁漫天堂我在网页版取消收藏后，在APP内仍然会显示，不会消息，看收藏按钮那已经从“已收藏”变为“收藏”，可见网页端成功取消，但是APP内并未消失
