### ISSUE TITLE
ehentai登录之后收藏夹的重命名好像没有显示出来

### ISSUE THREAD

**Issue by djwlx** [wgh136/PicaComic#46]

**Comment by wgh136** [comment]
下个版本会进行调整

________________________________
From: DJWL ***@***.***>
Sent: Tuesday, May 30, 2023 9:35:23 PM
To: wgh136/PicaComic ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [wgh136/PicaComic] ehentai登录之后收藏夹的重命名好像没有显示出来 (Issue #46)


―

**Comment by djwlx** [comment]
牛牛牛

**Comment by wgh136** [comment]
完成
