### ISSUE TITLE
[Enhancement]: 三星spen悬空操作支持功能请求

### ISSUE THREAD

**Issue by RJokerD** [wgh136/PicaComic#464]
### 描述/Description

使用spen按钮功能如图

### 操作系统/Operating System

Android

### 图片/picture

![Screenshot_20240403_195617_Air command.jpg](https://github.com/wgh136/PicaComic/assets/39233981/b3044a90-cb7e-4a0b-b051-6210f5bf3637)

**Comment by wgh136** [comment]
不用三星, 无法适配

**Comment by RJokerD** [comment]
> 不用三星, 无法适配

http://samsung.smarterapps.cn/index.php?app=home&mod=Public&act=help&type=11&id=68

**Comment by wgh136** [comment]
> > 不用三星, 无法适配
> 
> http://samsung.smarterapps.cn/index.php?app=home&mod=Public&act=help&type=11&id=68

欢迎pr, 我对此不感兴趣
