### ISSUE TITLE
[Bug]: 不清楚是否算bug，但jm图片加载总是卡在3/4

### ISSUE THREAD

**Issue by guest-zero** [wgh136/PicaComic#470]
### 描述/Description

如题目描述，分流四个全试了，结果仍是无法正常加载图片
![QQ截图20240405104817](https://github.com/wgh136/PicaComic/assets/133760269/46ad5840-9987-4821-9490-0ea0660c2a3b)
![QQ截图20240405104834](https://github.com/wgh136/PicaComic/assets/133760269/32685b04-388a-461c-868e-4536940bd4dc)

### Version

latest

### 使用的操作系统/Operating system

Windows

**Comment by wgh136** [comment]
无法复现

**Comment by guest-zero** [comment]
好吧，那我试试导出数据重新下载下软件吧，不过我想问下，默认导出的位置在哪

**Comment by guest-zero** [comment]
不行，还是不行，我上传下日志看看吧
[logs.txt](https://github.com/wgh136/PicaComic/files/14880047/logs.txt)
