### ISSUE TITLE
[Enhancement]: 本地收藏夹布局两个建议

### ISSUE THREAD

**Issue by gankumangcao** [wgh136/PicaComic#472]
### 描述/Description

开发者大大能否做个本地收藏夹布局的设置，现默认是双列的没法改单列，我自己的收藏夹比较多看起来不太美观喜欢单列好些。
还有本地收藏夹可以弄个手动自由排序吗（下面我发了2个视频就那样意思），个人创建想法的收藏夹比较多，有时候后面才想到的收藏夹名字创建但没法挪到想要的位置。

### 图片/picture

![Screenshot_2024-04-05-20-54-44-053_com github wgh136 pica_comic](https://github.com/wgh136/PicaComic/assets/85823141/e503be7a-0ff0-4a27-b6b5-7e64560288ef)
![Screenshot_2024-04-05-20-54-48-187_com github wgh136 pica_comic](https://github.com/wgh136/PicaComic/assets/85823141/70b2916f-87c8-4830-968b-0e5fabc2b1f0)

https://github.com/wgh136/PicaComic/assets/85823141/4756d7ca-6ccb-41ed-8d33-689b161af81d

https://github.com/wgh136/PicaComic/assets/85823141/501d2db6-9cdf-4c05-b2a7-1df6cfcce444

**Comment by wgh136** [comment]
并不是默认双列, 而是根据宽度决定的列数, 目前收藏夹名字过长时确实存在显示问题, 将会修复

**Comment by gankumangcao** [comment]
> 并不是默认双列, 而是根据宽度决定的列数, 目前收藏夹名字过长时确实存在显示问题, 将会修复

那开发者大大觉得 自由排序 本地目录怎么样
