### ISSUE TITLE
[Bug]: jm无法访问漫画页面

### ISSUE THREAD

**Issue by xr1234n** [wgh136/PicaComic#476]
### 描述/Description

从下载界面中的‘’查看详细‘’无法访问相关页面，一旦出现这种情况使用搜索功能也无法找到漫画

（感觉是之前的bug升级plus版）

### Version

3.0.6

### 使用的操作系统/Operating system

Android

### 日志/logs

Exception: Expected image data, but got text: 
#0      BaseImageProvider._loadBufferAsync (package:pica_comic/foundation/image_loader/base_image_provider.dart:82)
<asynchronous suspension>
#1      MultiFrameImageStreamCompleter._handleCodecReady (package:flutter/src/painting/image_stream.dart:985)
<asynchronous suspension>

### 截图或视频/Screenshot or video

![Screenshot_20240406_162927](https://github.com/wgh136/PicaComic/assets/61616196/10d1d897-a28f-41c8-94e5-d8a31c4191e2)

**Comment by wgh136** [comment]
无法复现, 提供的日志也与此无关

**Comment by xr1234n** [comment]
抱歉，抱歉，日志复制错了

是下面这个

Exception: Empty data
#0      _CachedNetwork.getJm (package:pica_comic/network/jm_network/jm_network.dart:57)
<asynchronous suspension>
#1      JmNetwork.get (package:pica_comic/network/jm_network/jm_network.dart:143)
<asynchronous suspension>
#2      JmNetwork.getComicInfo (package:pica_comic/network/jm_network/jm_network.dart:600)
<asynchronous suspension>
#3      ComicPageLogic.get (package:pica_comic/views/page_template/comic_page.dart:79)
<asynchronous suspension>

**Comment by xr1234n** [comment]
抱歉，抱歉，日志复制错了

是下面这个

Exception: Empty data
#0      _CachedNetwork.getJm (package:pica_comic/network/jm_network/jm_network.dart:57)
<asynchronous suspension>
#1      JmNetwork.get (package:pica_comic/network/jm_network/jm_network.dart:143)
<asynchronous suspension>
#2      JmNetwork.getComicInfo (package:pica_comic/network/jm_network/jm_network.dart:600)
<asynchronous suspension>
#3      ComicPageLogic.get (package:pica_comic/views/page_template/comic_page.dart:79)
<asynchronous suspension>

**Comment by xr1234n** [comment]
> 无法复现, 提供的日志也与此无关

抱歉，抱歉，日志复制错了

是下面这个

Exception: Empty data
#0 _CachedNetwork.getJm (package:pica_comic/network/jm_network/jm_network.dart:57)

#1 JmNetwork.get (package:pica_comic/network/jm_network/jm_network.dart:143)

#2 JmNetwork.getComicInfo (package:pica_comic/network/jm_network/jm_network.dart:600)

#3 ComicPageLogic.get (package:pica_comic/views/page_template/comic_page.dart:79)

**Comment by wgh136** [comment]
这个错误意思是漫画不存在

**Comment by xr1234n** [comment]
> 这个错误意思是漫画不存在

漫画在浏览器里可以正常搜索打开，到软件里就不行了。

好像是从旧下载里面触发的，之前是not find，现在是Empty data，是不是以前下载数据里什么没更新导致的

例子如下 ：
![Screenshot_20240406_183329](https://github.com/wgh136/PicaComic/assets/61616196/0f16f696-01af-4ac6-b8e6-02ac79803793)
![Screenshot_20240406_184228_Via](https://github.com/wgh136/PicaComic/assets/61616196/0f966fe7-41e5-481e-b2b1-eec9c7397c3e)
![Screenshot_20240406_184247](https://github.com/wgh136/PicaComic/assets/61616196/1767ea51-8545-4376-bb5f-778586003799)
![Screenshot_20240406_162927](https://github.com/wgh136/PicaComic/assets/61616196/fa10e659-e1d1-4281-a7d5-2bd2016871fd)

**Comment by xr1234n** [comment]
给作者大大提供一下最近发现的线索！

我发现jm有新的调整，现在对未登录的用户会隐藏部分漫画，我之前的下载都是未登录状态下载的。

所以对此猜测：那些下载后的漫画之所以无法跳转到相关页面与下载时的用户登录状态有关，我现在登录后的情况是搜索已经可以找到无法打开的漫画，但从下载目录中还是无法跳转。

希望以上猜测能帮你发现问题
