### ISSUE TITLE
希望观看时可以进行图片缩放

### ISSUE THREAD

**Issue by johnson50313** [wgh136/PicaComic#48]

**Comment by wgh136** [comment]
啊？不是可以缩放吗
手机平板直接使用手势，电脑上可以使用鼠标滚轮

________________________________
From: johnson50313 ***@***.***>
Sent: Friday, June 2, 2023 4:27:35 PM
To: wgh136/PicaComic ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [wgh136/PicaComic] 希望观看时可以进行图片缩放 (Issue #48)


―

**Comment by johnson50313** [comment]
电脑的要怎么设定? 我鼠标滚轮是上下翻页

**Comment by wgh136** [comment]
非"从上至下连续"阅读模式的时候是鼠标滚轮缩放
这个确实没考虑到
等有时间了我加一个滑动条控制缩放

________________________________

**Comment by johnson50313** [comment]
好的 谢谢，辛苦您了

**Comment by wgh136** [comment]
现在做了一些改进, 宽高比达到一定程度时图片不再适应宽度
添加了放大缩小按钮, 没有添加滑动条, 滑太快app会崩掉, 不知道为什么
![image](https://github.com/wgh136/PicaComic/assets/67669799/5e5b5fa6-50f9-449a-b367-cf6d10b1ac2a)
