### ISSUE TITLE
[Enhancement]: 更清楚地展示历史搜索记录

### ISSUE THREAD

**Issue by timelic** [wgh136/PicaComic#481]
### 描述/Description

历史搜索记录被放到了二级菜单，而且还放到了收藏后面。对于喜欢某个分类的爱好者，这非常麻烦。

并且，搜索记录不会记录漫画来源。也就是说很容易发生本来搜索的是A平台，结果点击历史记录默认是在B平台搜索，导致一片空白还得手动调整。

另外，切换搜索源的那个icon非常不直观，如果能换一个就更好啦。

**Comment by wgh136** [comment]
> 搜索记录不会记录漫画来源

我认为更好, 点击历史记录可以搜索自己选择的漫画源
