### ISSUE TITLE
[Enhancement]: 优化墨水屏体验

### ISSUE THREAD

**Issue by cheng762** [wgh136/PicaComic#485]
### 描述/Description

希望针对墨水屏能提供如下优化：
1.  在app设置中提供关闭全局动画的选项，关闭在不同页面跳转的时候的动画效果
2.  在探索各漫画源的时候，目前是无限滚动浏览，希望可以增加分页浏览

### 操作系统/Operating System

Android

**Comment by wgh136** [comment]
1. 太麻烦, 做不到
2. 设置里有
