### ISSUE TITLE
[Bug]: Windows版2.3.5之后的版本在部分电脑上无法启动

### ISSUE THREAD

**Issue by shalen233** [wgh136/PicaComic#489]
### 描述/Description

我尝试了两台同型号同配置笔记本，系统是自带的原装windows家庭版，版本均为windows10 22H2，使用2.3.5版本均可打开，但从3.0.0版本开始，仅有一台能打开，另一台会出现报错，我在无法打开的电脑上试着补全了微软常用运行库，但还是会出现报错。

### Version

3.0.6

### 使用的操作系统/Operating system

Windows

### 日志/logs

软件无法打开，我仅能找到windows的应用程序崩溃报告
[Report.wer.txt](https://github.com/wgh136/PicaComic/files/14955921/Report.wer.txt)

**Comment by wgh136** [comment]
我的所有设备都正常, 无法确定问题

**Comment by shalen233** [comment]
我这边又找了好几个朋友，都能打开，应该是我这其中一台系统出了问题，我再照着另一台改改(但能打开2.3.5却打不开后面的版本感觉怪怪的)

**Comment by shalen233** [comment]
实测，最新的3.1.0又能打开了，好评
