### ISSUE TITLE
[Bug]: UnimplementedError: createPlatformInAppWebViewWidget is not implemented on the current platform.

### ISSUE THREAD

**Issue by Yajusenpai114514810893** [wgh136/PicaComic#491]
### 描述/Description

嘗試在禁漫通過cloudflare challenge 按繼續後就出現這個error
不清楚原因 前幾天使用都沒有問題 在瀏覽器中都能成功通過禁漫cloudflare 

macos:13.2

### Version

3.0.3

### 使用的操作系统/Operating system

macOS

### 日志/logs

Response https://picaapi.picacomic.com/users/profile 401
headers:
{connection: keep-alive, date: Fri, 12 Apr 2024 21:23:39 GMT, server-time: 1712957019, content-length: 65, cf-ray: 873647568b91159b-EWR, cf-cache-status: DYNAMIC, content-type: application/json; charset=utf-8, server: cloudflare}
{
  "code": 401,
  "error": "1005",
  "message": "unauthorized"
}

### 截图或视频/Screenshot or video

<img width="891" alt="Screenshot 2024-04-13 at 04 13 53" src="https://github.com/wgh136/PicaComic/assets/96066246/7f5a0ebf-3f2e-41a3-b484-9365b955c7e3">

**Comment by wgh136** [comment]
非最新版本

**Comment by morningtzh** [comment]
![image](https://github.com/wgh136/PicaComic/assets/4755736/b2088ba9-232a-4c07-8c55-2c6bdf6dc9b8)

WebView不支持macOS，只支持两个移动平台  @wgh136 
https://github.com/pichillilorenzo/flutter_inappwebview/issues/1920
