### ISSUE TITLE
[Bug]: 证书问题报错，能不能忽略证书

### ISSUE THREAD

**Issue by 332879969** [wgh136/PicaComic#493]
### 描述/Description

在旧版本的平板上报了以下错误

### Version

最新版

### 使用的操作系统/Operating system

Android

### 截图或视频/Screenshot or video

![Screenshot_20240413-145007](https://github.com/wgh136/PicaComic/assets/57783375/e2b54d12-54dd-4a17-868b-7e25e7130f3a)

**Comment by wgh136** [comment]
忽略证书是一个危险的做法, 本app涉及账号密码, 不能这样做, 如果需要, 请自行修改代码并构建
