### ISSUE TITLE
分区页面中，部分分区无法正常获取本子

### ISSUE THREAD

**Issue by jogGUY** [wgh136/PicaComic#5]
当前版本为1.3.2
我很少点开分区去看本子，然后心血来潮去点开”禁书目录“时，发现本子只获取了一个，剩下的死活刷不出来，于是检查了一下其他分区，发现也有其他分区是这样只有一两本甚至干脆”无任何结果“，还有一些分区是获取了几本本子之后干脆就不刷新了，部分截图如下：
![Screenshot_2023-03-07-11-33-09](https://user-images.githubusercontent.com/108516858/223316382-d32c56f5-7aac-4ac1-9b55-fe006150a2f8.png)
![Screenshot_2023-03-07-11-32-38](https://user-images.githubusercontent.com/108516858/223316388-43206ac3-ed69-48ef-b0c0-4f8a57352b1f.png)
![Screenshot_2023-03-07-11-33-30](https://user-images.githubusercontent.com/108516858/223316396-ba4a71ba-aa66-4fe4-be14-92dd0d255acf.png)
![Screenshot_2023-03-07-11-33-46](https://user-images.githubusercontent.com/108516858/223316411-c02931dc-ba54-472e-8427-f16df69b5a5a.png)
![Screenshot_2023-03-07-11-35-19](https://user-images.githubusercontent.com/108516858/223316422-26200361-f63b-4982-83bd-c04638ed8d27.png)
![Screenshot_2023-03-07-11-32-56](https://user-images.githubusercontent.com/108516858/223316456-5e040688-5ea2-4bb2-a31e-05d91935cafd.png)
![Screenshot_2023-03-07-11-33-04](https://user-images.githubusercontent.com/108516858/223316705-2e3e5a40-3dc2-47e2-a73a-7218567a9037.png)
![Screenshot_2023-03-07-11-33-12](https://user-images.githubusercontent.com/108516858/223316715-3d07976a-ffed-4c84-b5db-b3d19e8bf3f8.png)

另外，好像这两天不管我用WiFi还是移动流量都很难登进去，就卡在”获取用户信息“那里无限转圈，不晓得是什么原因🤷‍♂️

**Comment by jogGUY** [comment]
呃，刚刚我试着升级到1.3.3再重新进APP，尴尬的是不管怎么试一直是”网络错误“，然后我用官方APP登，结果登进去了💀

**Comment by wgh136** [comment]
我也很少点进分类, 所以没发现这个问题, 晚上修
我不清楚你的设备上发生了什么, 在登录页面放分流设置没有意义, 因为哔咔的分流指的是图片分流, 哔咔只有一个api域名picaapi.picacomic.com, 在向api服务器获取图片时带上分流设置从而获取到图片地址

**Comment by jogGUY** [comment]
> 我也很少点进分类, 所以没发现这个问题, 晚上修 我不清楚你的设备上发生了什么, 在登录页面放分流设置没有意义, 因为哔咔的分流指的是图片分流, 哔咔只有一个api域名picaapi.picacomic.com, 在向api服务器获取图片时带上分流设置从而获取到图片地址

嘛，这是一种很诡异的事，我粗浅的理解是，第三方和官方按理来说用了同样的地址，应该会有同样的登陆效果的，然后这Cloudflare的转发效果也太蛋疼了点......好像之前在[CloudflareSpeedTest](https://github.com/XIU2/CloudflareSpeedTest)这个项目里看到说Cloudflare貌似有被干扰的嫌疑，可能和这个有关......
API和图片一样，真的需要转发啊😭

**Comment by wgh136** [comment]
已经没有使用cloudflare了, 现在cloudflare在国内的速度非常的慢
我这里转发是可以正常使用的, 并且速度还不错, 可能是因为不同地区网络状况不一样
仍然无法登陆的话试试清除数据, 或许可以解决问题

**Comment by wgh136** [comment]
你可以试一下ping api.kokoiro.xyz
测试能不能连上我的服务器

**Comment by jogGUY** [comment]
连上了，ping也没问题（平均200ms），感恩🌹
再报告一个偶发玄学事故：在第一次清除数据时，登陆成功，然后我尝试切换账号时，发现提示”账号或密码错误“，我确认账号和密码都是对的，然后我两个账号来回测试几遍，都是提示”账号或密码错误“，后面我进行第二次清除数据，这个玄学事故又消失了😂

**Comment by wgh136** [comment]
看了下, 有段代码写的有问题, 今晚修复

**Comment by wgh136** [comment]
分类问题已解决, 修复了错误地提示”账号或密码错误“的问题, 调整了代码以便于捕获错误
