### ISSUE TITLE
[Bug]: 网络导入出问题了

### ISSUE THREAD

**Issue by xoevdv** [wgh136/PicaComic#506]
### 描述/Description

如图，上个版本还能正常导入，更新beta版本后就这样了
![Screenshot_2024-04-24-15-56-49-476_com github wgh136 pica_comic](https://github.com/wgh136/PicaComic/assets/165496517/e2e76684-55d3-4161-b396-c194cc384410)
![Screenshot_2024-04-24-15-57-56-282_com github wgh136 pica_comic](https://github.com/wgh136/PicaComic/assets/165496517/522aec45-013d-496b-8dca-10e9c0f353b0)

### Version

最新测试版

### 使用的操作系统/Operating system

Android

**Comment by wgh136** [comment]
这是缺少漫画源

**Comment by xoevdv** [comment]
> 这是缺少漫画源

那怎么办啊这个
