### ISSUE TITLE
登录错误

### ISSUE THREAD

**Issue by PYUDNG** [wgh136/PicaComic#51]
登录时，
- 使用转发服务器（无论是否同时使用VPN）登录显示 ```The request returned an invalid status code of 502```
- 关闭转发服务器，使用VPN登录显示 ```未能获取到Token```

**Comment by wgh136** [comment]
好了, 现在你应该能使用转发服务器了
至于为什么不使用转发服务器时未能获取到token, 尚不清楚, 此情况只在一部分人中出现

**Comment by PYUDNG** [comment]
转发服务器可以使用了

**Comment by PYUDNG** [comment]
使用VPN登录也成功了，感谢
