### ISSUE TITLE
[Enhancement]: 导出用户全部数据时没有标明存储地址

### ISSUE THREAD

**Issue by tanadiejiang** [wgh136/PicaComic#511]
### 描述/Description

导出用户全部数据时没有标明或可供选择保存位置的操作
并且找不到导出的文件
导出时间过长(文件很大你忍一下)
虽然我也很想用数据同步的方式来导出但...那个Android设备的wifi硬件损坏了无法使用

### 操作系统/Operating System

Android

**Comment by tanadiejiang** [comment]
还有软件很不错 使我的牛牛旋转
牛牛转了都说好 牛牛常常吐一地
希望以后越来越好 bug越来越少

**Comment by wgh136** [comment]
导出数据是需要你手动选择保存位置的

**Comment by tanadiejiang** [comment]
好吧或许是导出的时间太久息屏了，导致后续程序出错。
您或许....应该在导出前让用户指定
导出路径/选择文件夹

**Comment by tanadiejiang** [comment]
> 导出数据是需要你手动选择保存位置的

好吧或许是导出的时间太久息屏了， 导致后续程序出 错。 
您或许....应该可以在导出前让用户指定 
导出路径/选择文件夹...毕竟导出确实有点久了

**Comment by wgh136** [comment]
做不到, 移动端app不一定有直接读写文件的权限, 需要走系统api保存文件, 必须先有文件才能调用系统api
