### ISSUE TITLE
[Bug]: 无法重新下载的BUG

### ISSUE THREAD

**Issue by mx41shy** [wgh136/PicaComic#516]
### 描述/Description

漫画项目下载完成后如果存在已经下载但是错误的图片文件，则无法使用retry进行重新加载。（图1）
手动在文件目录删除错误文件后，回到阅读器界面对应的图片加载进度一直为0。
在已下载界面删除漫画项目后，重新下载该项目，文件未重新下载，之前下载错误了哪些文件，重新下载之后这些文件仍然错误。（图2）
在已下载界面删除漫画项目后，打开详情页，进入阅读器，进行在线加载，对应的图片可以加载，所以不是网络问题。此时退回详情页使用下载按钮，文件未重新下载，之前下载错误了哪些文件，重新下载之后这些文件仍然错误。

### Version

3.1.1

### 使用的操作系统/Operating system

Windows

### 截图或视频/Screenshot or video

![image](https://github.com/wgh136/PicaComic/assets/16437280/16068a13-f41e-4588-a716-0dee39f536de)（图1）
![image](https://github.com/wgh136/PicaComic/assets/16437280/d351c991-3675-41fa-a2a1-fd547d46c320)（图2）

**Comment by wgh136** [comment]
对于已经下载的漫画不会从网络下载图片，只会本地加载

**Comment by mx41shy** [comment]
> 对于已经下载的漫画不会从网络下载图片，只会本地加载

那我应该如何重新下载？
