### ISSUE TITLE
[Bug]: ios 17.4.1 运行v3.1.2版本下载失败

### ISSUE THREAD

**Issue by dtdtbaka** [wgh136/PicaComic#519]
### 描述/Description

下载失败，回退至v3.1.1依旧存在此问题，更新前老版本的下载无法正常进行，新添加的下载可以正常下载

### Version

v3.1.2

### 使用的操作系统/Operating system

iOS

### 日志/logs

PathAccessException: Creation failed, path = '/var/mobile/Containers/Data/Application/53B1767C-6BD6-4443-A29F-82D7B8288D91' (OS Error: Operation not permitted, errno = 1)
#0 _Directory.createSync (dart:io/directory_impl.dart:124)
#1 _Directory.createSync (dart:io/directory_impl.dart:119)
#2 _Directory.createSync (dart:io/directory_impl.dart:119)
#3 _Directory.createSync (dart:io/directory_impl.dart:119)
#4 _Directory.createSync (dart:io/directory_impl.dart:119)
#5 _File.createSync (dart:io/file_impl.dart:303)
#6 DownloadingItem.downloadCover (package:pica_comic/network/download_model.dart:125)
<asynchronous suspension>
#7 DownloadingItem.start (package:pica_comic/network/download_model.dart:155)
<asynchronous suspension>

**Comment by dtdtbaka** [comment]
感觉像是更新版本后地址53B1767C-6BD6-4443-A29F-82D7B8288D91发生变更，老版本的目录无法写入，所以老版本的下载无法进行，更新后新添加的下载可以进行。

**Comment by wgh136** [comment]
猜测是重新签名后app的id发生了变更, 下个版本加一个检测

**Comment by dtdtbaka** [comment]
如果可以输出本地下载存储路径的log就可以比较一下
