### ISSUE TITLE
[Bug]: eh登录出现“登录失败”提示

### ISSUE THREAD

**Issue by natsuz0ra** [wgh136/PicaComic#522]
### 描述/Description

设备：iPhone13 Pro
系统版本：16.3
描述：通过webview登录出现“登录失败”提示，手动填写cookie也是同样的情况，log中没有错误日志

### Version

3.1.2

### 使用的操作系统/Operating system

iOS

**Comment by natsuz0ra** [comment]
补充信息：回退到3.0.4版本后就成功了，不确定是哪个版本开始出的问题

**Comment by wgh136** [comment]
eh网页的一个小问题导致的, 现在应该是可以正常登录了
