### ISSUE TITLE
[Bug]: Nhentai 驗證 Cloudflare 後，依舊顯示 Cloudflare Challenge

### ISSUE THREAD

**Issue by TW527E** [wgh136/PicaComic#523]
### 描述/Description

(本人使用的 PicaComic 的是 .zip 免安裝版)
重新登入 Nhentai 帳號、回退前幾個版本、隔天再使用，皆無法解決該問題，並且我使用 iOS 版本時並沒有遇到此問題。
到任何需要 Nhentai Cloudflare 人機驗證的地方，按繼續，接著驗證完後，它會自動把驗證視窗關閉，然後就沒有然後了，多按幾遍繼續也是沒有用的

### Version

v3.1.2

### 使用的操作系统/Operating system

Windows

### 日志/logs

[logs.txt](https://github.com/wgh136/PicaComic/files/15281349/logs.txt)

### 截图或视频/Screenshot or video

![recording](https://github.com/wgh136/PicaComic/assets/37478187/8a669bc1-5922-481a-8c2d-879be543d620)

**Comment by ypq123456789** [comment]
我也是一模一样
