### ISSUE TITLE
[Bug]:下载漫画时会出现的老bug

### ISSUE THREAD

**Issue by tian1521** [wgh136/PicaComic#528]
### 描述/Description

这个问题在早期的版本经常出现，后续更新几次之后就很少出现了，由于我平时下载最长的漫画，也就日本单行本那样的两三百页的日漫，基本不会出现这种下载bug了，今天第一次下载这种长篇的条漫，出现了大量这样的bug，例如图片不完整，或者干脆就没有图片提示英文，希望能解决
![Screenshot_20240516_140740](https://github.com/wgh136/PicaComic/assets/149772706/3d2a9c8b-ec67-42f4-b914-1b431a7c915e)
![Screenshot_20240516_140731](https://github.com/wgh136/PicaComic/assets/149772706/05e7ca2c-30c1-4037-9de4-47a194af5b07)
![Screenshot_20240516_140720](https://github.com/wgh136/PicaComic/assets/149772706/dbae0cb3-331c-4c3e-9c20-9d26f0037f2c)

### Version

3.1.2

### 使用的操作系统/Operating system

Android

**Comment by wgh136** [comment]
对于e站, 直接下载是使用爬图的方式, 非常不稳定, 而且配额消耗很快, 建议换归档下载

**Comment by tian1521** [comment]
> 非

好的，谢谢，一直都是用的普通下载，基本没出过什么问题，导致我都没有注意到下面还有其他的下载方式(｡･ω･｡)ﾉ♡
