### ISSUE TITLE
[Bug]: 漫画导出的压缩包无法打开

### ISSUE THREAD

**Issue by SaiKaede36** [wgh136/PicaComic#530]
### 描述/Description

新版本下载漫画后导出的压缩包无法解析

### Version

3.1.2

### 使用的操作系统/Operating system

Android

### 截图或视频/Screenshot or video

![Screenshot_20240517_204639_edit_532084556963066](https://github.com/wgh136/PicaComic/assets/148802605/b7c34280-2ed7-49e7-bd46-95f48cde04a9)
![Screenshot_20240517_204644_edit_532095248123166](https://github.com/wgh136/PicaComic/assets/148802605/5a723553-0fe1-45d6-8edb-ed3b6df59a77)

**Comment by wgh136** [comment]
无法复现
