### ISSUE TITLE
EHentai图片下载错误[Bug]: 

### ISSUE THREAD

**Issue by jxx01** [wgh136/PicaComic#538]
### 描述/Description

正常的漫画与插画，EHentai里的图片源几乎全部都有错误，要么是图片数据错误加载不出来，要么就是下面那个奇奇怪怪的问题，我下载了53个漫画，仅5个正常

### Version

v3.1.2

### 使用的操作系统/Operating system

Android

### 日志/logs

Exception: Codec failed to produce an image, possibly due to invalid image data.

### 截图或视频/Screenshot or video

![Screenshot_2024-05-27-10-54-57-982_org telegram messenger](https://github.com/wgh136/PicaComic/assets/106129142/5392ad91-b6a7-4c5b-aa63-66d183771684)
![Screenshot_2024-05-27-10-54-48-443_org telegram messenger](https://github.com/wgh136/PicaComic/assets/106129142/32535fca-e06e-49a9-ae74-25be80d7c46f)

**Comment by wgh136** [comment]
此问题通常与账号有关
