### ISSUE TITLE
[Bug]: 关于身份验证

### ISSUE THREAD

**Issue by cheney12313** [wgh136/PicaComic#539]
### 描述/Description

有一定几率无法使用身份验证
系统版本：21-20240515-NIGHTLY-alioth Android14

### Version

3.1.2

### 使用的操作系统/Operating system

Android

### 日志/logs
Logs

info App Status 2024-05-27 15:18:33.659618 
Start initialization.

info Network 2024-05-27 15:18:33.686735 
Set Proxy null

info Network 2024-05-27 15:18:33.686956 
Set Proxy null

info Network 2024-05-27 15:18:33.761854 
POST https://www.jmapinodeudzn.xyz/login
headers:
{token: e0d162b4227434c5b2608d67dd1f59e9, tokenparam: 1716794313,1.6.8, user-agent: Mozilla/5.0 (Linux; Android 13; 012345678 Build/TQ1A.230305.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/114.0.5735.196 Safari/537.36, accept-encoding: gzip, Host: www.jmapinodeudzn.xyz, Content-Type: application/x-www-form-urlencoded, cookie: null, content-length: 37}
data:username=dgghhhgggg&password=ijICChQG

info Network 2024-05-27 15:18:33.813728 
Set Proxy null

info Network 2024-05-27 15:18:34.904230 
Response https://www.jmapinodeudzn.xyz/login 200
headers:
{connection: keep-alive, cache-control: no-store, no-cache, must-revalidate, set-cookie: [ipcountry=CN; path=/, ipm5=2b093b913d73dbcae3231dadbc4b590a; path=/, AVS=gjjcu59cj09lbnr6kptfeo9nrv; path=/, remember_id=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/, __cflb=0H28vXTt7XwkcM8Fr48hRnw5qchxwDmvgKbYrbDWAse; SameSite=None; Secure; path=/; expires=Tue, 28-May-24 06:18:31 GMT; HttpOnly], last-modified: Mon, 27 May 2024 07:18:31 GMT, date: Mon, 27 May 2024 07:18:31 GMT, vary: Accept-Encoding, content-encoding: gzip, cf-cache-status: DYNAMIC, report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v4?s=6uzkfFX8c%2FKRA0NwwTK6I6HIHd5fZd54G%2FDJFl8v%2FIva60G5kRgPGoBOSN2twgzIY%2BSfkoOivVHU7ejiqx8Ct7YyqnApFJ1Td6xrn5vt2IMLM4Awhxa0Qoc2fd6Y%2FylPkaY%2FbFIzmg%3D%3D"}],"group":"cf-nel","max_age":604800}, pragma: no-cache, content-type: application/javascript; charset=utf-8;, server: cloudflare, content-length: 452, nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}, cf-ray: 88a43b3f784f093a-IAD, expires: Thu, 19 Nov 1981 08:52:00 GMT}
[123, 34, 99, 111, 100, 101, 34, 58, 50, 48, 48, 44, 34, 100, 97, 116, 97, 34, 58, 34, 71, 54, 71, 86, 119, 103, 80, 68, 85, 97, 80, 122, 48, 66, 80, 107, 111, 55, 69, 80, 115, 84, 78, 111, 113, 79, 79, 68, 107, 105, 113, 120, 103, 57, 114, 112, 71, 100, 122, 79, 57, 108, 67, 105, 106, 76, 53, 115, 85, 109, 112, 102, 105, 115, 106, 109, 68, 77, 82, 76, 79, 55, 99, 117, 119, 110, 77, 115, 68, 121, 109, 112, 102, 119, 66, 54, 81, 77, 122, 105, 120, 111, 116, 56, 99, 53, 51, 116, 56, 66, 121, 72, 53, 98, 88, 113, 120, 66, 97, 112, 82, 105, 79, 69, 53, 69, 57, 74, 99, 104, 110, 49, 71, 112, 53, 105, 98, 88, 75, 87, 51, 77, 113, 83, 79, 104, 106, 85, 81, 92, 47, 119, 74, 113, 114, 97, 66, 89, 92, 47, 87, 121, 101, 71, 99, 111, 106, 81, 81, 43, 82, 68, 114, 69, 79, 106, 120, 101, 118, 110, 57, 55, 48, 57, 56, 73, 90, 121, 66, 115, 92, 47, 105, 107, 67, 49, 100, 105, 67, 43, 110, 110, 76, 84, 98, 114, 72, 89, 122, 43, 105, 90, 102, 84, 55, 89, 102, 87, 71, 81, 73, 118, 115, 89, 98, 77, 76, 112, 115, 92, 47, 87, 53, 101, 77, 101, 100, 86, 83, 68, 97, 70, 113, 67, 43, 68, 75, 108, 53, 77, 122, 117, 77, 57, 68, 85, 75, 76, 55, 66, 67, 79, 73, 98, 102, 88, 83, 112, 99, 89, 122, 56, 50, 114, 53, 99, 97, 85, 57, 43, 110, 102, 43, 118, 55, 110, 49, 112, 69, 83, 55, 81, 55, 118, 110, 82, 109, 104, 66, 80, 102, 118, 83, 79, 115, 84, 106, 68, 103, 72, 112, 52, 65, 78, 51, 43, 57, 52, 120, 113, 70, 66, 121, 87, 56, 49, 107, 113, 106, 97, 85, 118, 78, 82, 54, 65, 69, 55, 122, 101, 69, 71, 99, 120, 83, 116, 76, 83, 71, 120, 121, 51, 113, 68, 66, 84, 49, 100, 50, 99, 99, 105, 49, 108, 67, 113, 78, 83, 82, 106, 72, 52, 79, 111, 72, 84, 90, 72, 115, 92, 47, 118, 90, 48, 118, 122, 52, 86, 115, 111, 55, 81, 101, 106, 114, 109, 79, 85, 65, 86, 83, 109, 113, 92, 47, 81, 78, 98, 121, 54, 87, 101, 107, 122, 74, 120, 84, 112, 112, 102, 57, 56, 119, 92...

info Network 2024-05-27 15:18:36.695450 
Set Proxy null

info Network 2024-05-27 15:18:36.695881 
Set Proxy null

info Network 2024-05-27 15:18:36.696072 
Set Proxy null

info Network 2024-05-27 15:18:36.696240 
Set Proxy null

info Network 2024-05-27 15:18:36.711299 
Set Proxy null

info Network 2024-05-27 15:18:36.711583 
Set Proxy null

info Network 2024-05-27 15:18:36.711768 
Set Proxy null

info Network 2024-05-27 15:18:36.716875 
GET https://api.wgh136.xyz/version
headers:
{}
data:null

info Network 2024-05-27 15:18:36.718632 
GET https://picaapi.picacomic.com/users/profile
headers:
{api-key: C69BAF41DA5ABD1FFEDC6D2FEA56B, authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1Yzg1ZGMzZGI3OGI3ZTMwNTkyMzJmMmYiLCJlbWFpbCI6InF3ZXJ0eXVpb3BwcHAiLCJyb2xlIjoibWVtYmVyIiwibmFtZSI6IuaQnueCuem7hOiJsuOAgiIsInZlcnNpb24iOiIyLjIuMS4zLjMuNCIsImJ1aWxkVmVyc2lvbiI6IjQ1IiwicGxhdGZvcm0iOiJhbmRyb2lkIiwiaWF0IjoxNzE2NzEzMjU1LCJleHAiOjE3MTczMTgwNTV9.gw29SXExTtUn3UTs9qCqYkKJcNeAM5NjOfBFeMsbeSo, accept: application/vnd.picacomic.com.v1+json, app-channel: 1, time: 1716794316, nonce: 557eba701bf911ef982b6be8a9503764, signature: 4226bae8c01b81ff50c1cc4826b8768e1e4ed26a535edcf155b2c27eaf6cb49c, app-version: 2.2.1.3.3.4, app-uuid: defaultUuid, image-quality: original, app-platform: android, app-build-version: 45, accept-encoding: gzip, user-agent: okhttp/3.8.1, version: v1.4.1, Host: picaapi.picacomic.com}
data:null

info Network 2024-05-27 15:18:36.719310 
GET https://picaapi.picacomic.com/comics/random
headers:
{api-key: C69BAF41DA5ABD1FFEDC6D2FEA56B, authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1Yzg1ZGMzZGI3OGI3ZTMwNTkyMzJmMmYiLCJlbWFpbCI6InF3ZXJ0eXVpb3BwcHAiLCJyb2xlIjoibWVtYmVyIiwibmFtZSI6IuaQnueCuem7hOiJsuOAgiIsInZlcnNpb24iOiIyLjIuMS4zLjMuNCIsImJ1aWxkVmVyc2lvbiI6IjQ1IiwicGxhdGZvcm0iOiJhbmRyb2lkIiwiaWF0IjoxNzE2NzEzMjU1LCJleHAiOjE3MTczMTgwNTV9.gw29SXExTtUn3UTs9qCqYkKJcNeAM5NjOfBFeMsbeSo, accept: application/vnd.picacomic.com.v1+json, app-channel: 1, time: 1716794316, nonce: 557eba711bf911ef982b6be8a9503764, signature: f664d961562a9c095831f5675c8ab23af9f4a208047da7e5c2d589a04537f2c9, app-version: 2.2.1.3.3.4, app-uuid: defaultUuid, image-quality: original, app-platform: android, app-build-version: 45, accept-encoding: gzip, user-agent: okhttp/3.8.1, version: v1.4.1, Host: picaapi.picacomic.com}
data:null

info Network 2024-05-27 15:18:36.719894 
GET https://picaapi.picacomic.com/comics?page=1&s=dd
headers:
{api-key: C69BAF41DA5ABD1FFEDC6D2FEA56B, authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1Yzg1ZGMzZGI3OGI3ZTMwNTkyMzJmMmYiLCJlbWFpbCI6InF3ZXJ0eXVpb3BwcHAiLCJyb2xlIjoibWVtYmVyIiwibmFtZSI6IuaQnueCuem7hOiJsuOAgiIsInZlcnNpb24iOiIyLjIuMS4zLjMuNCIsImJ1aWxkVmVyc2lvbiI6IjQ1IiwicGxhdGZvcm0iOiJhbmRyb2lkIiwiaWF0IjoxNzE2NzEzMjU1LCJleHAiOjE3MTczMTgwNTV9.gw29SXExTtUn3UTs9qCqYkKJcNeAM5NjOfBFeMsbeSo, accept: application/vnd.picacomic.com.v1+json, app-channel: 1, time: 1716794316, nonce: 557ee1801bf911ef982b6be8a9503764, signature: f449209ae7c92063ce0d5e452872d2c244789dfbf66ce01f3d1f9b79570c21e7, app-version: 2.2.1.3.3.4, app-uuid: defaultUuid, image-quality: original, app-platform: android, app-build-version: 45, accept-encoding: gzip, user-agent: okhttp/3.8.1, version: v1.4.1, Host: picaapi.picacomic.com}
data:null

info Network 2024-05-27 15:18:36.723053 
Set Proxy null

info Network 2024-05-27 15:18:36.723115 
GET https://e-hentai.org/favorites.php
headers:
{user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36, host: e-hentai.org, cookie: ipb_member_id=6280536; ipb_pass_hash=70263f4ea6f1ca88e589c5aa74fd2a74; nw=1; sk=3okl132afqme2k74tmn2ca8nicji; event=1714150436}
data:null

info network 2024-05-27 15:18:36.980342 
Downloading Data

info Sync 2024-05-27 15:18:37.867501 
No updated version of data.
Stop downloading data.

info Network 2024-05-27 15:18:38.892278 
Response https://api.wgh136.xyz/version 200
headers:
{connection: keep-alive, alt-svc: h3=":443"; ma=86400, date: Mon, 27 May 2024 07:18:35 GMT, content-length: 5, nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}, cf-ray: 88a43b563a3d9557-LHR, cf-cache-status: DYNAMIC, report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v4?s=R8KWamFUb24SnrveTdyfZoYJFyc53%2FEwYDnxC2x8XJISHWursJqe6ioY3IwvjoevYi3G6u%2B3V75YN0lznFHu%2B9cf7rLnt07RxECmMFW7ZMENg8pUKcYGU5INsD%2BrqXLffw%3D%3D"}],"group":"cf-nel","max_age":604800}, content-type: text/plain, server: cloudflare}
3.1.2

info App Status 2024-05-27 15:18:39.448892 
Going to Page /NewSettingsPage

error Network 2024-05-27 15:18:51.726047 
GET https://picaapi.picacomic.com/users/profile
DioException [connection timeout]: The request connection took longer than 0:00:15.000000 and it was aborted. To get rid of this exception, try raising the RequestOptions.connectTimeout above the duration of 0:00:15.000000 or improve the response time of the server.
Retrying...

error Network 2024-05-27 15:18:51.726302 
GET https://picaapi.picacomic.com/comics/random
DioException [connection timeout]: The request connection took longer than 0:00:15.000000 and it was aborted. To get rid of this exception, try raising the RequestOptions.connectTimeout above the duration of 0:00:15.000000 or improve the response time of the server.
Retrying...

error Network 2024-05-27 15:18:51.726394 
GET https://picaapi.picacomic.com/comics?page=1&s=dd
DioException [connection timeout]: The request connection took longer than 0:00:15.000000 and it was aborted. To get rid of this exception, try raising the RequestOptions.connectTimeout above the duration of 0:00:15.000000 or improve the response time of the server.
Retrying...

error Network 2024-05-27 15:18:51.726474 
GET https://e-hentai.org/favorites.php
DioException [connection timeout]: The request connection took longer than 0:00:15.000000 and it was aborted. To get rid of this exception, try raising the RequestOptions.connectTimeout above the duration of 0:00:15.000000 or improve the response time of the server.
Retrying...

info Network 2024-05-27 15:18:52.729542 
GET https://picaapi.picacomic.com/users/profile
headers:
{api-key: C69BAF41DA5ABD1FFEDC6D2FEA56B, authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1Yzg1ZGMzZGI3OGI3ZTMwNTkyMzJmMmYiLCJlbWFpbCI6InF3ZXJ0eXVpb3BwcHAiLCJyb2xlIjoibWVtYmVyIiwibmFtZSI6IuaQnueCuem7hOiJsuOAgiIsInZlcnNpb24iOiIyLjIuMS4zLjMuNCIsImJ1aWxkVmVyc2lvbiI6IjQ1IiwicGxhdGZvcm0iOiJhbmRyb2lkIiwiaWF0IjoxNzE2NzEzMjU1LCJleHAiOjE3MTczMTgwNTV9.gw29SXExTtUn3UTs9qCqYkKJcNeAM5NjOfBFeMsbeSo, accept: application/vnd.picacomic.com.v1+json, app-channel: 1, time: 1716794316, nonce: 557eba701bf911ef982b6be8a9503764, signature: 4226bae8c01b81ff50c1cc4826b8768e1e4ed26a535edcf155b2c27eaf6cb49c, app-version: 2.2.1.3.3.4, app-uuid: defaultUuid, image-quality: original, app-platform: android, app-build-version: 45, accept-encoding: gzip, user-agent: okhttp/3.8.1, version: v1.4.1, Host: picaapi.picacomic.com}
data:null

info Network 2024-05-27 15:18:52.729912 
GET https://picaapi.picacomic.com/comics/random
headers:
{api-key: C69BAF41DA5ABD1FFEDC6D2FEA56B, authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1Yzg1ZGMzZGI3OGI3ZTMwNTkyMzJmMmYiLCJlbWFpbCI6InF3ZXJ0eXVpb3BwcHAiLCJyb2xlIjoibWVtYmVyIiwibmFtZSI6IuaQnueCuem7hOiJsuOAgiIsInZlcnNpb24iOiIyLjIuMS4zLjMuNCIsImJ1aWxkVmVyc2lvbiI6IjQ1IiwicGxhdGZvcm0iOiJhbmRyb2lkIiwiaWF0IjoxNzE2NzEzMjU1LCJleHAiOjE3MTczMTgwNTV9.gw29SXExTtUn3UTs9qCqYkKJcNeAM5NjOfBFeMsbeSo, accept: application/vnd.picacomic.com.v1+json, app-channel: 1, time: 1716794316, nonce: 557eba711bf911ef982b6be8a9503764, signature: f664d961562a9c095831f5675c8ab23af9f4a208047da7e5c2d589a04537f2c9, app-version: 2.2.1.3.3.4, app-uuid: defaultUuid, image-quality: original, app-platform: android, app-build-version: 45, accept-encoding: gzip, user-agent: okhttp/3.8.1, version: v1.4.1, Host: picaapi.picacomic.com}
data:null

info Network 2024-05-27 15:18:52.730048 
GET https://picaapi.picacomic.com/comics?page=1&s=dd
headers:
{api-key: C69BAF41DA5ABD1FFEDC6D2FEA56B, authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1Yzg1ZGMzZGI3OGI3ZTMwNTkyMzJmMmYiLCJlbWFpbCI6InF3ZXJ0eXVpb3BwcHAiLCJyb2xlIjoibWVtYmVyIiwibmFtZSI6IuaQnueCuem7hOiJsuOAgiIsInZlcnNpb24iOiIyLjIuMS4zLjMuNCIsImJ1aWxkVmVyc2lvbiI6IjQ1IiwicGxhdGZvcm0iOiJhbmRyb2lkIiwiaWF0IjoxNzE2NzEzMjU1LCJleHAiOjE3MTczMTgwNTV9.gw29SXExTtUn3UTs9qCqYkKJcNeAM5NjOfBFeMsbeSo, accept: application/vnd.picacomic.com.v1+json, app-channel: 1, time: 1716794316, nonce: 557ee1801bf911ef982b6be8a9503764, signature: f449209ae7c92063ce0d5e452872d2c244789dfbf66ce01f3d1f9b79570c21e7, app-version: 2.2.1.3.3.4, app-uuid: defaultUuid, image-quality: original, app-platform: android, app-build-version: 45, accept-encoding: gzip, user-agent: okhttp/3.8.1, version: v1.4.1, Host: picaapi.picacomic.com}
data:null

info Network 2024-05-27 15:18:52.730146 
GET https://e-hentai.org/favorites.php
headers:
{user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36, host: e-hentai.org, cookie: ipb_member_id=6280536; ipb_pass_hash=70263f4ea6f1ca88e589c5aa74fd2a74; nw=1; sk=3okl132afqme2k74tmn2ca8nicji; event=1714150436}
data:null

info Network 2024-05-27 15:18:52.886064 
Set Proxy null

info App Status 2024-05-27 15:18:53.619989 
Going to Page /AuthPage

info Network 2024-05-27 15:18:53.620658 
Set Proxy null

info Network 2024-05-27 15:18:53.620895 
Set Proxy null

info Network 2024-05-27 15:18:58.471178 
Set Proxy null

info Network 2024-05-27 15:18:58.471694 
Set Proxy null

info Network 2024-05-27 15:18:58.517328 
Set Proxy null

info Network 2024-05-27 15:18:58.543522 
Set Proxy null

info Network 2024-05-27 15:19:00.478136 
Set Proxy null

error Network 2024-05-27 15:19:07.733056 
GET https://picaapi.picacomic.com/users/profile
DioException [connection timeout]: The request connection took longer than 0:00:15.000000 and it was aborted. To get rid of this exception, try raising the RequestOptions.connectTimeout above the duration of 0:00:15.000000 or improve the response time of the server.
Retrying...

error Network 2024-05-27 15:19:07.733084 
GET https://picaapi.picacomic.com/comics/random
DioException [connection timeout]: The request connection took longer than 0:00:15.000000 and it was aborted. To get rid of this exception, try raising the RequestOptions.connectTimeout above the duration of 0:00:15.000000 or improve the response time of the server.
Retrying...

error Network 2024-05-27 15:19:07.733094 
GET https://picaapi.picacomic.com/comics?page=1&s=dd
DioException [connection timeout]: The request connection took longer than 0:00:15.000000 and it was aborted. To get rid of this exception, try raising the RequestOptions.connectTimeout above the duration of 0:00:15.000000 or improve the response time of the server.
Retrying...

error Network 2024-05-27 15:19:07.733100 
GET https://e-hentai.org/favorites.php
DioException [connection timeout]: The request connection took longer than 0:00:15.000000 and it was aborted. To get rid of this exception, try raising the RequestOptions.connectTimeout above the duration of 0:00:15.000000 or improve the response time of the server.
Retrying...

info Network 2024-05-27 15:19:08.736687 
GET https://picaapi.picacomic.com/users/profile
headers:
{api-key: C69BAF41DA5ABD1FFEDC6D2FEA56B, authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1Yzg1ZGMzZGI3OGI3ZTMwNTkyMzJmMmYiLCJlbWFpbCI6InF3ZXJ0eXVpb3BwcHAiLCJyb2xlIjoibWVtYmVyIiwibmFtZSI6IuaQnueCuem7hOiJsuOAgiIsInZlcnNpb24iOiIyLjIuMS4zLjMuNCIsImJ1aWxkVmVyc2lvbiI6IjQ1IiwicGxhdGZvcm0iOiJhbmRyb2lkIiwiaWF0IjoxNzE2NzEzMjU1LCJleHAiOjE3MTczMTgwNTV9.gw29SXExTtUn3UTs9qCqYkKJcNeAM5NjOfBFeMsbeSo, accept: application/vnd.picacomic.com.v1+json, app-channel: 1, time: 1716794316, nonce: 557eba701bf911ef982b6be8a9503764, signature: 4226bae8c01b81ff50c1cc4826b8768e1e4ed26a535edcf155b2c27eaf6cb49c, app-version: 2.2.1.3.3.4, app-uuid: defaultUuid, image-quality: original, app-platform: android, app-build-version: 45, accept-encoding: gzip, user-agent: okhttp/3.8.1, version: v1.4.1, Host: picaapi.picacomic.com}
data:null

info Network 2024-05-27 15:19:08.737024 
GET https://picaapi.picacomic.com/comics/random
headers:
{api-key: C69BAF41DA5ABD1FFEDC6D2FEA56B, authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1Yzg1ZGMzZGI3OGI3ZTMwNTkyMzJmMmYiLCJlbWFpbCI6InF3ZXJ0eXVpb3BwcHAiLCJyb2xlIjoibWVtYmVyIiwibmFtZSI6IuaQnueCuem7hOiJsuOAgiIsInZlcnNpb24iOiIyLjIuMS4zLjMuNCIsImJ1aWxkVmVyc2lvbiI6IjQ1IiwicGxhdGZvcm0iOiJhbmRyb2lkIiwiaWF0IjoxNzE2NzEzMjU1LCJleHAiOjE3MTczMTgwNTV9.gw29SXExTtUn3UTs9qCqYkKJcNeAM5NjOfBFeMsbeSo, accept: application/vnd.picacomic.com.v1+json, app-channel: 1, time: 1716794316, nonce: 557eba711bf911ef982b6be8a9503764, signature: f664d961562a9c095831f5675c8ab23af9f4a208047da7e5c2d589a04537f2c9, app-version: 2.2.1.3.3.4, app-uuid: defaultUuid, image-quality: original, app-platform: android, app-build-version: 45, accept-encoding: gzip, user-agent: okhttp/3.8.1, version: v1.4.1, Host: picaapi.picacomic.com}
data:null

info Network 2024-05-27 15:19:08.737153 
GET https://picaapi.picacomic.com/comics?page=1&s=dd
headers:
{api-key: C69BAF41DA5ABD1FFEDC6D2FEA56B, authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1Yzg1ZGMzZGI3OGI3ZTMwNTkyMzJmMmYiLCJlbWFpbCI6InF3ZXJ0eXVpb3BwcHAiLCJyb2xlIjoibWVtYmVyIiwibmFtZSI6IuaQnueCuem7hOiJsuOAgiIsInZlcnNpb24iOiIyLjIuMS4zLjMuNCIsImJ1aWxkVmVyc2lvbiI6IjQ1IiwicGxhdGZvcm0iOiJhbmRyb2lkIiwiaWF0IjoxNzE2NzEzMjU1LCJleHAiOjE3MTczMTgwNTV9.gw29SXExTtUn3UTs9qCqYkKJcNeAM5NjOfBFeMsbeSo, accept: application/vnd.picacomic.com.v1+json, app-channel: 1, time: 1716794316, nonce: 557ee1801bf911ef982b6be8a9503764, signature: f449209ae7c92063ce0d5e452872d2c244789dfbf66ce01f3d1f9b79570c21e7, app-version: 2.2.1.3.3.4, app-uuid: defaultUuid, image-quality: original, app-platform: android, app-build-version: 45, accept-encoding: gzip, user-agent: okhttp/3.8.1, version: v1.4.1, Host: picaapi.picacomic.com}
data:null

info Network 2024-05-27 15:19:08.737251 
GET https://e-hentai.org/favorites.php
headers:
{user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36, host: e-hentai.org, cookie: ipb_member_id=6280536; ipb_pass_hash=70263f4ea6f1ca88e589c5aa74fd2a74; nw=1; sk=3okl132afqme2k74tmn2ca8nicji; event=1714150436}
data:null

_No response_

### 截图或视频/Screenshot or video

https://www.123pan.com/s/CfuVVv-sg1l.html

**Comment by OH016** [comment]
依旧无法触发

https://github.com/wgh136/PicaComic/assets/58856332/d0f9402c-366c-4661-ad3f-068ee5cbefd4

@wgh136
