### ISSUE TITLE
注册错误

### ISSUE THREAD

**Issue by PYUDNG** [wgh136/PicaComic#54]
- [x] 已经更新到最新版（1.6.13）
- [x] 使用VPN进行注册
- [x] 注册表单全部已填写没有空项
- [x] 注册用户名、账号、密码没有特殊字符，仅使用大小写字母和数字
- [x] 密码同时包括大写字母、小写字母和数字
- [x] 三个验证问题互相不重复

按下注册按钮后，下方弹出提示“Invalid email or password”。是需要在用户名或者账号处填写邮箱吗？

**Comment by PYUDNG** [comment]
但是我反复使用相同的注册信息点击了多次注册按钮，每次都是显示`Invalid email or password`
如果是注册成功登陆失败，那么就应该在第二次点击注册按钮时，就弹出类似“您注册的账号已经存在”这样的提示，但是我没有看到这样的提示，所以我还是怀疑是注册过程的问题

**Comment by PYUDNG** [comment]
抱歉，底下的提示确实写的是`登录时出现错误：Invalid email or password`，那应该是登录的问题了。我不知道为什么会登陆失败。

**Comment by wgh136** [comment]
每次都是这样的话, 那么应该是注册存在问题
app应该是错误地判断了注册成功

**Comment by wgh136** [comment]
看了一下代码, 判断注册成功的条件是网络请求的状态码为200, 且得到的数据的message字段的值不是`failure`
确实很不完善, 但毕竟我也不知道哔咔的后端会给我怎样的数据. 之前也没人报告问题, 我自己也没有遇到任何问题
你可以去哔咔的[官网](https://manhuabika.com/)注册试试
