### ISSUE TITLE
[Bug]: 收藏夹命名含有特殊符号导致无法打开收藏夹

### ISSUE THREAD

**Issue by ckckerwtw** [wgh136/PicaComic#540]
### 描述/Description

无意间将一个收藏夹命名为含单引号，日语的长字符串，导致无论是打开收藏夹还是搜索页面都会报错，并且无法打开任何一个漫画页面，并且这个bug在windows端和android端均存在（导入同一个数据文件后）

### Version

3.1.2

### 使用的操作系统/Operating system

Android, Windows

### 日志/logs

SqliteException(1): while preparing statement, near "sエクスタシー": syntax error, SQL logic error (code 1)
  Causing statement:         select * from folder_order
        where folder_name == 'Vパン'sエクスタシー ，左藤空気，Vpan's EXTASY ，Satou Kuuki';
      
#0      throwException (package:sqlite3/src/implementation/exception.dart:75)
#1      DatabaseImplementation._prepareInternal (package:sqlite3/src/implementation/database.dart:303)
#2      DatabaseImplementation.prepare (package:sqlite3/src/implementation/database.dart:362)
#3      FfiDatabaseImplementation.prepare (package:sqlite3/src/ffi/implementation.dart:111)
#4      DatabaseImplementation.select (package:sqlite3/src/implementation/database.dart:387)
#5      LocalFavoritesManager._getFolderNamesWithDB (package:pica_comic/foundation/local_favorites.dart:399)
#6      LocalFavoritesManager.folderNames (package:pica_comic/foundation/local_favorites.dart:455)
#7      _LocalFavoritesSettingsState.build (package:pica_comic/views/settings/local_favorite_settings.dart:21)
#8      StatefulElement.build (package:flutter/src/widgets/framework.dart:5592)
#9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5480)
#10     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
#11     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#12     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
#13     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5634)
#14     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
#15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
#16     Element.updateChild (package:flutter/src/widgets/framework.dart:3840)
#17     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765)
#18     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#19     Element.updateChildren (package:flutter/src/widgets/framework.dart:3973)
#20     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6918)
#21     _ViewportElement.update (package:flutter/src/widgets/viewport.dart:235)
#22     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#23     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765)
#24     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#25     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765)
#26     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#27     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765)
#28     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#29     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765)
#30     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#31     ComponentElement.perfo...

### 截图或视频/Screenshot or video

![421d9b568b63cd846d9bbe229d23e5d](https://github.com/wgh136/PicaComic/assets/171015495/211bd506-230b-4890-ab58-1f991733d338)
![05270fb506d6640e133b3c2e39a2e1d](https://github.com/wgh136/PicaComic/assets/171015495/941d28c5-954a-434c-843c-bba8c406373b)

**Comment by ckckerwtw** [comment]
通过下载较低版本（3.0.6）“刷新了”本地收藏页面，在重新导入之前的数据后能够显示出所有收藏夹，然后直接改名故障的收藏夹名称后解决了页面卡死的问题（如果直接点击展开该收藏夹则会导致还原页面卡死，并且不能通过关闭程序“刷新页面”）

**Comment by wgh136** [comment]
单引号导致的问题将会在下个版本修复, 但双引号是不行的
