### ISSUE TITLE
UI疑問

### ISSUE THREAD

**Issue by NeKoOuO** [wgh136/PicaComic#543]
想請問以前這種排版方式 現在怎麼不一樣了
我好喜歡這種方式 請問有辦法復現嗎？ 

<img src="https://github.com/wgh136/PicaComic/blob/master/screenshots%2F4.png" style="width: 400px">

**Comment by wgh136** [comment]
当有大量收藏夹的时候此布局并不合适
想要复现的话只能用旧版
