### ISSUE TITLE
[Bug]: IOS中旧版本中已添加到下载管理器中的下载，在更新后仍然无法继续下载

### ISSUE THREAD

**Issue by dtdtbaka** [wgh136/PicaComic#545]
### 描述/Description

老版本中添加的未完成的下载无法正常进行，新版本中添加的下载可进行。与#519 问题一致。
补充：
添加未完成下载后覆盖安装应用，也无法继续下载

### Version

v3.1.3

### 使用的操作系统/Operating system

iOS

### 日志/logs

上上个版本没下完的显示如下log
PathAccessException: Creation failed, path = '/var/mobile/Containers/Data/Application/53B1767C-6BD6-4443-A29F-82D7B8288D91' (OS Error: Operation not permitted, errno = 1)
#0 _Directory.createSync (dart:io/directory_impl.dart:124)
#1 _Directory.createSync (dart:io/directory_impl.dart:119)
#2 _Directory.createSync (dart:io/directory_impl.dart:119)
#3 _Directory.createSync (dart:io/directory_impl.dart:119)
#4 _Directory.createSync (dart:io/directory_impl.dart:119)
#5 _File.createSync (dart:io/file_impl.dart:303)
#6 DownloadingItem.downloadCover (package:pica_comic/network/download_model.dart:125)
<asynchronous suspension>
#7 DownloadingItem.start (package:pica_comic/network/download_model.dart:155)
<asynchronous suspension>
上个版本没下完的显示如下log
PathAccessException: Creation failed, path = '/var/mobile/Containers/Data/Application/DDC2C930-7501-44B4-8FA6-65B392D66F2A' (OS Error: Operation not permitted, errno = 1)
#0 _Directory.createSync (dart:io/directory_impl.dart:124)
#1 _Directory.createSync (dart:io/directory_impl.dart:119)
#2 _Directory.createSync (dart:io/directory_impl.dart:119)
#3 _Directory.createSync (dart:io/directory_impl.dart:119)
#4 _Directory.createSync (dart:io/directory_impl.dart:119)
#5 _File.createSync (dart:io/file_impl.dart:303)
#6 DownloadingItem.downloadCover (package:pica_comic/network/download_model.dart:125)
<asynchronous suspension>
#7 DownloadingItem.start (package:pica_comic/network/download_model.dart:155)
<asynchronous suspension>
补充覆盖安装后log：
PathAccessException: Creation failed, path = '/var/mobile/Containers/Data/Application/7D7961BC-C3E4-4D38-8502-84ED833E99DF' (OS Error: Operation not permitted, errno = 1)
#0 _Directory.createSync (dart:io/directory_impl.dart:124)
#1 _Directory.createSync (dart:io/directory_impl.dart:119)
#2 _Directory.createSync (dart:io/directory_impl.dart:119)
#3 _Directory.createSync (dart:io/directory_impl.dart:119)
#4 _Directory.createSync (dart:io/directory_impl.dart:119)
#5 _File.createSync (dart:io/file_impl.dart:303)
#6 DownloadingItem.downloadCover (package:pica_comic/network/download_model.dart:125)
<asynchronous suspension>
#7 DownloadingItem.start (package:pica_comic/network/download_model.dart:155)
<asynchronous **suspension>**

**Comment by bloomhjl** [comment]
是否可以考虑增加手动刷新当前下载列表中所有项的下载参数
