### ISSUE TITLE
哭笑不得，禁漫的加载重复问题被解决了，结果哔咔就有这个问题了

### ISSUE THREAD

**Issue by jogGUY** [wgh136/PicaComic#56]
复现手段：随便找一个搜索结果超过一页的词条去搜索，只要能翻到最后一页，再继续向上滑动就会出现重复加载最后一页结果的现象o(￣┰￣*)ゞ

另外，刚刚突然之间禁漫的站点崩了，还挺稀奇的......

**Comment by wgh136** [comment]
完成

**Comment by wgh136** [comment]
啊, 还有页码选择框固定在头顶这个建议,
下次更新再说吧
