### ISSUE TITLE
[Bug]: nhentai gif图

### ISSUE THREAD

**Issue by zDot-sr** [wgh136/PicaComic#562]
### 描述/Description

如果漫画有gif的话会载不出来
下载时会有error

### Version

3.1.3

### 使用的操作系统/Operating system

Android

### 截图或视频/Screenshot or video

![Screenshot_20240613-183050_Pica Comic](https://github.com/wgh136/PicaComic/assets/57571112/2f667cfa-6c3f-4c63-84ad-4af89f223f2e)

**Comment by wgh136** [comment]
给我一个有gif图的画廊链接
