### ISSUE TITLE
[Enhancement]: hosts功能默认配置文件与文档完善

### ISSUE THREAD

**Issue by PriceHu** [wgh136/PicaComic#566]
### 描述/Description

[hosts文档](https://github.com/wgh136/PicaComic/blob/master/doc/hosts.md)提到通过内建代理服务器转发流量解决了不能在App内通过IP地址直接请求的问题，但该功能在描述和实际配置上与代码实现有一定差异，建议对文档进行修正和完善。

- 根据[代码实现](https://github.com/wgh136/PicaComic/blob/30f8ca8d6a5b74022718e6546b322e2cc61b4c34/lib/network/http_proxy.dart#L129)，代理服务器的实际工作原理是通过重写URL，直接替换请求URL的Host部分。这与通常而言的hosts文件有一些区别。hosts文件通常控制的是DNS解析，而不是直接修改请求本身。建议可以考虑修改该功能的名称避免误解。
- 根据代码和实际测试，由于该功能的原理是直接重写URL，配置中`rule`部分可以是任意字符串而不限于IP地址，建议在文档中予以说明。例如，哔咔的图片分流原理是使用不同的host（参考其他项目）。对于CDN来说，以IP直接访问可能是禁止的，而且统一CDN域名的IP可能会经常变化。由于App目前哔咔的分流设置基本是个摆设，用户可以在配置中自行指定分流服务器地址而不是IP从而使用哔咔的分流功能。
- 哔咔的分流包含API和图片两部分，似乎使用了不同的服务器。基于这一点和以上描述，建议修改默认配置文件示例使用户更容易理解配置方法（和方便懒人直接用）。一个示例如下：
  ```json
  {
      "port": 7891,
      "rule": {
          "picaapi.picacomic.com": "104.21.91.145",
          "storage1.picacomic.com": "storage.diwodiwo.xyz",
          "storage-b.picacomic.com": "storage.diwodiwo.xyz",
          "img.picacomic.com": "img.diwodiwo.xyz",
          "e-hentai.org": "172.67.0.127",
          "exhentai.org": "178.175.129.254",
          "s.exhentai.org": "178.175.129.254"
      },
      "sni": [
          "e-hentai.org",
          "exhentai.org",
          "s.exhentai.org"
      ]
  }
  ```

**Comment by wgh136** [comment]
hosts文件并没有控制dns解析, 它只是列举出已知的主机名与IP地址映射关系, 我不认为这有什么命名问题
我不建议直连, 使用梯子是更好的选择

**Comment by PriceHu** [comment]
> In modern operating systems, the hosts file remains an alternative name resolution mechanism, configurable often as part of facilities such as the Name Service Switch as either the primary method or as a fallback method.

请允许我纠正我上文用词，hosts文件控制的是包括域名在内的名字解析。但它的工作方式与App的实现有本质区别。hosts工作在应用层以下，而App是在应用层直接对URL进行重写。因此App实现的功能不仅限于数字IP地址，而是替换为任意字符串，这意味着它可以将请求改写发送到自建反代。同时也存在服务器禁止直接在URL中以数字IP进行访问的情况。以上建议的目的是充分利用已有功能和用户已有资源，包括但不限于已有自建反向代理，和是否直连没有关系。
