### ISSUE TITLE
[Bug]: 在阅读漫画后无法正常使用键盘

### ISSUE THREAD

**Issue by acnekot** [wgh136/PicaComic#567]
### 描述/Description

在阅读漫画后无法正常使用键盘
已成功复现bug（不能排除是概率性问题
设备iPhone 8Plus iOS15.6.1

### Version

3.1.3

### 使用的操作系统/Operating system

iOS

### 截图或视频/Screenshot or video

https://cloud.hhco.asia/f/oeT5/IMG_9148.MOV

**Comment by wgh136** [comment]
这是flutter的问题, 并且已被flutter官方修复, 请等待下个版本的发布
