### ISSUE TITLE
两个小建议

### ISSUE THREAD

**Issue by KHUN-370** [wgh136/PicaComic#57]
希望导出的压缩包是完整的原标题名，目前导出如果原标题名短，导出就是完整的，如果原标题长了就会用“…”省略部分；
希望能在漫画详情界面与已下载界面，可以标识出漫画来自哪个网站，我的体验目前有时候会分不清看的和下载的是哪个网站的漫画。

**Comment by wgh136** [comment]
1. 必须限制文件名的长度，这是来自操作系统的限制，有些漫画的名字实在是太长。
2. 可以有

**Comment by wgh136** [comment]
现在会尽可能显示完整的文件名, 但当文件名过长, 还是会进行截断, 文件名的长度限制在255个字节
已下载界面会标记漫画源; 漫画详情页似乎没什么必要, 你应该会记得从哪里点进来的
