### ISSUE TITLE
[Bug]: 哔咔中部分漫画已更新的章节软件内不显示

### ISSUE THREAD

**Issue by Alicelas** [wgh136/PicaComic#579]
### 描述/Description

例如哔咔的《洞洞杂货店》，软件内最新只显示为80-81话，而实际哔咔已更新至84-85话

### Version

3.1.4

### 使用的操作系统/Operating system

Android, Windows

### 截图或视频/Screenshot or video

![QQ截图20240708213619](https://github.com/wgh136/PicaComic/assets/51156839/7af5946f-a4d4-431d-b95a-367fec1e3feb)
![QQ截图20240708213638](https://github.com/wgh136/PicaComic/assets/51156839/fb35bfab-806d-4172-b6fb-b091056d01e4)

**Comment by zhongfly** [comment]
这个是缓存导致的，清理缓存后就可以看到新的。
我觉得这是缓存机制不合理，这种章节信息不应该缓存

**Comment by wgh136** [comment]
可能是旧版本的缓存还没过期导致的? 现在应该是没问题了
