### ISSUE TITLE
禁漫搜索结果无法加载

### ISSUE THREAD

**Issue by misaka-13766** [wgh136/PicaComic#58]
使用jmcomic搜索后会出现“The request returned an invalid status code of 403”，不清楚是服务器问题还是禁漫那边的问题，麻烦大佬排查下w

**Comment by wgh136** [comment]
禁漫的问题，你用官方app或者网页都是一样的

________________________________
From: 御坂13766号 ***@***.***>
Sent: Saturday, June 10, 2023 6:39:32 PM
To: wgh136/PicaComic ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [wgh136/PicaComic] 禁漫搜索结果无法加载 (Issue #58)


使用jmcomic搜索后会出现“The request returned an invalid status code of 403”，不清楚是服务器问题还是禁漫那边的问题，麻烦大佬排查下w

―

**Comment by misaka-13766** [comment]
okk，麻烦大佬啦
