### ISSUE TITLE
[Bug]: picacg无法正常连接

### ISSUE THREAD

**Issue by guest-zero** [wgh136/PicaComic#583]
### 描述/Description

picacg最近连不上了，挂了梯子也一样，开关host后仍然如此，漫画源也改过了，但是仍然是超时

### Version

3.1.4

### 使用的操作系统/Operating system

Windows

### 日志/logs

[logs.txt](https://github.com/user-attachments/files/16192280/logs.txt)

**Comment by Montaro2017** [comment]
是你网络问题，我正常打开

**Comment by guest-zero** [comment]
> 是你网络问题，我正常打开

很奇怪，最近用的也是这个网络，偶尔能直连，有些时候需要挂个梯子，现在是挂不挂都没法连

**Comment by Teresian** [comment]
我这里也是，提示登录错误，但是登录上了，也可以看，就是偶尔会不能加载。

**Comment by wgh136** [comment]
检查自己的网络, 开梯子的话看看梯子的日志
