### ISSUE TITLE
下载速度问题

### ISSUE THREAD

**Issue by kofzhanganguo** [wgh136/PicaComic#59]
![image](https://github.com/wgh136/PicaComic/assets/32073931/071305b4-1d5a-4f50-b336-c62b8cb51722)
平均2秒下载一张图片，这速度也太慢了，到底是我的问题，还是啥问题，我开代理，下载流媒体的m3u8的资源，都是满速10MB的速度下载，为啥下载图片这么慢？

我下载的资源是来自禁漫的，请作者看看是啥问题。

**Comment by wgh136** [comment]
因为没有多线程下载，下载一张图片前要先建立连接，这个步骤很费时间
有时间了再做多线程下载

________________________________
From: o情天 ***@***.***>
Sent: Saturday, June 10, 2023 10:14:26 PM
To: wgh136/PicaComic ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [wgh136/PicaComic] 下载速度问题 (Issue #59)


[image]<https://user-images.githubusercontent.com/32073931/244875514-071305b4-1d5a-4f50-b336-c62b8cb51722.png>
平均2秒下载一张图片，这速度也太慢了，到底是我的问题，还是啥问题，我开代理，下载流媒体的m3u8的资源，都是满速10MB的速度下载，为啥下载图片这么慢？

我下载的资源是来自禁漫的，请作者看看是啥问题。

―

**Comment by wgh136** [comment]
另外对于禁漫还有一个问题
由于禁漫把图片拆分打乱，app需要对其进行重组，这对cpu压力较大，为了提高阅读器性能，此步骤在下载时进行，这也就意味着同时的下载数量不能过多，否则你的电脑会非常卡
也就是说满速10MB的下载对于禁漫是不可能的

________________________________
From: o情天 ***@***.***>
Sent: Saturday, June 10, 2023 10:14:26 PM
To: wgh136/PicaComic ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [wgh136/PicaComic] 下载速度问题 (Issue #59)


[image]<https://user-images.githubusercontent.com/32073931/244875514-071305b4-1d5a-4f50-b336-c62b8cb51722.png>
平均2秒下载一张图片，这速度也太慢了，到底是我的问题，还是啥问题，我开代理，下载流媒体的m3u8的资源，都是满速10MB的速度下载，为啥下载图片这么慢？

我下载的资源是来自禁漫的，请作者看看是啥问题。

―

**Comment by kofzhanganguo** [comment]
那么看来是无解了？

下载几部漫画，开机，开一夜都下载不完。

**Comment by wgh136** [comment]
好了, 新版本会并行下载提高速度
出于性能考虑, 并行数不会太高
对于你这个下载量, 没有什么好的解决方法, 如果是picacg或者eh还有救
