### ISSUE TITLE
[Enhancement]: 希望能够增加图片刷新功能

### ISSUE THREAD

**Issue by 775958** [wgh136/PicaComic#597]
### 描述/Description

在观看漫画是有时会因为网络问题导致图片加载错误，这是需要去清理缓存才能让图片重新加载。

### 图片/picture

![Screenshot_20240811-132316](https://github.com/user-attachments/assets/b12778ad-1e4d-4b8e-a654-9a009d3264ea)

**Comment by wgh136** [comment]
对于图片加载出错会出现重试按钮, 你这个是加载成功了, 只不过是因为图片加载达到eh的限制, eh给你返回了警告图片
