### ISSUE TITLE
奇怪的网络问题

### ISSUE THREAD

**Issue by jogGUY** [wgh136/PicaComic#6]
![2023-03-29 210955](https://user-images.githubusercontent.com/108516858/228547243-c8512ffe-216f-4d37-8eb3-4a32cc3b1d8c.png)
如图，下午我在手机上想登录一下，发现一直转圈圈，然后我断网进设置把“使用转发服务器”给关了，结果就是无论哪个分流都是“连接超时”。但是，我用官方APP登进去，用分流二、分流三都是能进去的。接着，我用电脑测试了一下就发现这种情况了。这张图是我现在测的，一样的问题🤷‍♂️

**Comment by wgh136** [comment]
我试了一下, 也出现了连接超时, 点击重试后就好了
看了下服务器的log, 有一大堆的time is not synchronize, 目前不清楚原因

**Comment by wgh136** [comment]
另外, 中转服务器是api.kokoiro.xyz, 你可以试试能不能ping通
comic.kokoiro.xyz只承担显示网页的功能, 最终的网络请求仍然是通过api.kokoiro.xyz

**Comment by jogGUY** [comment]
> 另外, 中转服务器是api.kokoiro.xyz, 你可以试试能不能ping通

目前是可以ping通的,也能正常用了，感恩🌹

不过下午时那个没有转发时的连接超时还是把我整的绷不住了，没有转发时不是用的官方APP给的IP地址么？按理来说应该保持一致才对啊......🤣

**Comment by wgh136** [comment]
看了一下[picacg-qt](https://github.com/tonquer/picacg-qt)项目, 有一个分流ip的东西
我对官方app抓包没发现有这个, 可能是我用的app版本太老了?
明天把这东西加上

**Comment by jogGUY** [comment]
>  可能是我用的app版本太老了? 
啊，版本比2.2.1.3.3.4还低吗？😂
好像官方从19年开始就没更新过客户端了，大家应该都更新到这个版本了吧？🤦

**Comment by jogGUY** [comment]
说起抓包，那位老哥是这样抓包的：[Issue 213](https://github.com/tonquer/picacg-qt/issues/213)

**Comment by wgh136** [comment]
我的问题, 没注意到那个网络请求
用官方app的分流2,3确实能直连, 虽然速度有点慢, 明天把这东西加上

**Comment by jogGUY** [comment]
![image](https://user-images.githubusercontent.com/108516858/229687465-1782fdd3-1aec-443e-8859-db206a94f8ad.png)
我哭了老哥，你这是服务器流量爆了？刚刚手机上登，开启转发服务器，然后就是喜闻乐见的“网络错误”😱😭

**Comment by jogGUY** [comment]
而且非常神奇的是，在不用转发服务器的情况下，所有图在可接受时间内加载不出来，已排除网络问题（官方APP直连无问题可正常加载），这个直连的逻辑是不是只做了API连接没做图片连接？o(￣┰￣*)ゞ

**Comment by wgh136** [comment]
是“网络错误”而不是“连接超时”吗
网络错误实际上是未知错误，有些错误用try...catch...捕获不了我也很头疼
服务器在美国，连通性可能不是很好，等到期后换一个
确实只做了api连接，忘了做图片
目前正在做eh，下次更新的时间可能比较晚

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jogGUY** [comment]
> 是“网络错误”而不是“连接超时”吗 

确实是“网络错误”，我这电脑和手机都是一个网络的，要是“连接超时”的话ping应该会有问题的呀🤷‍♂️

“网络错误”这个问题感觉也很玄学，主要是不像网页就可以提示404、502、504之类的。说起来，目前的捕捉错误功能是只要没有返回正确的数据包，不管什么情况都报一样的错么?这也太蛋疼了......

连通性这个很难说，ping通了又没内容过来，就像是数据包被搞掉了似的⊙﹏⊙∥

eh的话服务器IP连上去不会被“干净”问题拦住么？😂

**Comment by wgh136** [comment]
如果是404之类的错误都能捕获并显示出来, 不能捕获的错误指的是SocketException, 我在flutter的仓库中也看到有人提出这个问题
eh的话需要自备梯子, 检测ip这个确实没办法

**Comment by wgh136** [comment]
修了服务器上的一个bug, 该bug会导致一段时间后服务器上的程序挂掉

**Comment by wgh136** [comment]
现在图片加载会受到Cf IP设置的影响
