### ISSUE TITLE
[Bug]: Eh预览加载出现问题

### ISSUE THREAD

**Issue by mrliu714** [wgh136/PicaComic#603]
### 描述/Description

Eh预览图一直显示加载，如图。

### Version

V3.1.4

### 使用的操作系统/Operating system

Android

### 日志/logs

[logs.txt](https://github.com/user-attachments/files/16669517/logs.txt)

### 截图或视频/Screenshot or video

![Screenshot_2024-08-20-13-38-45-325_com github wgh136 pica_comic](https://github.com/user-attachments/assets/f7e53df8-737e-4592-9f18-28bbcef08853)

**Comment by Jgifts** [comment]
+1
