### ISSUE TITLE
[Bug]: 无法登陆/浏览禁漫天堂网站

### ISSUE THREAD

**Issue by 58185599** [wgh136/PicaComic#604]
### 描述/Description

如题，手机客户端突然无法浏览禁漫天堂，清空缓存后重试无效。
使用jmcomic的app或者直接访问网页端都可以打开。
安装windows客户端后重试依然无效。
在分流1,4下，登陆提示invalid status code:301。
在分流2下，提示connection errored:failed host look up'www.jmapinode.vip'
在分流3下，提示404 not found。

后安装电脑端重试，情况不变

### Version

3.1.4

### 使用的操作系统/Operating system

Android, Windows

### 日志/logs

POST https://www.jmapinode.vip/login
DioException [connection error]: The connection errored: Failed host lookup: 'www.jmapinode.vip' This indicates an error which most likely cannot be solved by the library.
Error: SocketException: Failed host lookup: 'www.jmapinode.vip' (OS Error: No address associated with hostname, errno = 7)
null
以及
POST https://www.jmapinode.vip/login
headers:
{token: 1561eeee9dc8348c16e910b008d95592, tokenparam: 1724150778,1.6.8, user-agent: Mozilla/5.0 (Linux; Android 13; 012345678 Build/TQ1A.230305.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/114.0.5735.196 Safari/537.36, accept-encoding: gzip, Host: www.jmapinode.vip, Content-Type: application/x-www-form-urlencoded, cookie: null, content-length: 19}
data:username=&password=

**Comment by wellgpt** [comment]
我也遇到了，应该是JM该登录地址了

**Comment by wellgpt** [comment]
我也遇到了，应该是JM改登录地址了

**Comment by 583522** [comment]
所以这个禁漫看不了？

**Comment by liwy1024** [comment]
➕一

**Comment by 1256274392** [comment]
我也，什么时候修复(˃ ⌑ ˂ഃ )

**Comment by Auto-R** [comment]
v4.0已经修复了，更新就行

**Comment by SinksSon** [comment]
谁能给个安装包啊？我的天堂更新不了。
