### ISSUE TITLE
[Bug]: jm无法登录

### ISSUE THREAD

**Issue by ftfgfr** [wgh136/PicaComic#606]
### 描述/Description

无法进入与JM相关的漫画

### Version

3.1.4

### 使用的操作系统/Operating system

Android

### 日志/logs

POST https://www.jmapinodeudzn.xyz/login
DioException [bad response]: This exception was thrown because the response has a status code of 301 and RequestOptions.validateStatus was configured to throw for this status code.
The status code of 301 has the following meaning: "Redirection: further action needs to be taken in order to complete the request"
Read more about status codes at https://developer.mozilla.org/en-US/docs/Web/HTTP/Status
In order to resolve this exception you typically have either to verify and fix your request code or you have to fix the server code.

[]

**Comment by zhang-chao-jie** [comment]
我也是
