### ISSUE TITLE
[Enhancement]: 希望将哔咔的最近更新加入

### ISSUE THREAD

**Issue by uyjhgkjbkhvyhjjyhvkjyhkjyhvhjv** [wgh136/PicaComic#607]
### 描述/Description

哔咔的大部分选项都可以实现，但是用习惯了最近更新，喜欢从最新的开始看，哔咔的推荐和ex的一日内最热不能满足需求

**Comment by wgh136** [comment]
探索页面往下翻就是

**Comment by uyjhgkjbkhvyhjjyhvkjyhkjyhvhjv** [comment]
谢谢提醒

nyne ***@***.***>于2024年8月24日 周六17:15写道：

**Comment by zhongfly** [comment]
@wgh136  目前4.0.1版本Android上，哔咔探索页面上显示的“最新”与“随机”完全一样，不是真正的最近更新，只有点开“最新”旁边的“查看更多”才是对的
