### ISSUE TITLE
EH加载问题

### ISSUE THREAD

**Issue by ARK0326** [wgh136/PicaComic#61]
EH部分，详情页加载正常，但只要进阅读器就会报错（超时或者IP超限制）。使用其他EH应用和网页端访问，正常加载无超限。建议检查阅读器载图逻辑。

**Comment by ARK0326** [comment]
使用的是最新版本，之前用1.6.10，当时无问题

**Comment by ARK0326** [comment]
出现过的报错：
null checker operator used on a null value
当前ip超出eh图片限制
超时（8s的那个）

**Comment by ARK0326** [comment]
确认了一下，探索页面里访问eh主页和eh热门里的内容无报错，使用搜索访问会报错

**Comment by wgh136** [comment]
我这里没有问题

确定在1.6.10没有遇到问题吗?
和目前版本对比了一下, eh的图片加载只有两个变化
一个是加了一个检测, 当出现图片超限时, eh有一定概率返回一段纯文本, 所以加上了这一段代码
https://github.com/wgh136/PicaComic/blob/d4751825eabebf8948a8c0c28760400fd428725c/lib/tools/cache_manager.dart#L131C4-L134
另一个时进入阅读器时的获取图片链接, 更改为了并行请求, 加快获取速度
