### ISSUE TITLE
[Bug]: win平台新版应用在绅士漫画中无法“查看更多”

### ISSUE THREAD

**Issue by jayeew** [wgh136/PicaComic#616]
### 描述/Description

单独的漫画可以正常查看，但是“查看更多”会一直加载。
![微信截图_20240825110938](https://github.com/user-attachments/assets/d14ce328-3edb-42de-a5fb-6d00804d72b3)
![微信截图_20240825110954](https://github.com/user-attachments/assets/65a1b24e-a3e7-418e-978a-db439e53af4f)

### Version

最新版

### 使用的操作系统/Operating system

Windows

### 日志/logs

Null check operator used on a null value
#0      htManga.<anonymous closure> (package:pica_comic/comic_source/built_in/ht_manga.dart:116)
#1      _CategoryComicsList.getComics (package:pica_comic/pages/category_comics_page.dart:162)
#2      ComicsPageLogic.get (package:pica_comic/components/comics_list.dart:31)
#3      ComicsPage.build.<anonymous closure> (package:pica_comic/components/comics_list.dart:175)
#4      StateBuilder.builderWrapped (package:pica_comic/foundation/state_controller.dart:137)
#5      _StateBuilderState.build (package:pica_comic/foundation/state_controller.dart:185)
#6      StatefulElement.build (package:flutter/src/widgets/framework.dart:5729)
#7      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5617)
#8      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780)
#9      Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#10     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
#11     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5771)
#12     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
#13     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#14     Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#16     Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#17     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
#18     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
#19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#20     Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#22     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780)
#23     Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#24     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
#25     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5771)
#26     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
#27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#28     Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#29     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6900)
#30     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#31     Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#32     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#33     Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#34     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
...

**Comment by xoevdv** [comment]
不止是电脑版，安卓端也一样
