### ISSUE TITLE
希望可以添加绅士漫画的源

### ISSUE THREAD

**Issue by Reminiserces** [wgh136/PicaComic#62]
希望可以添加绅士漫画的源    

绅士漫画网址http://www.htmanga3.top/

**Comment by wgh136** [comment]
已完成, 请等待下个版本发布

**Comment by Reminiserces** [comment]
阿里嘎多



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年7月10日(周一) 上午9:11
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [wgh136/PicaComic] 希望可以添加绅士漫画的源 (Issue #62)




 
已完成, 请等待下个版本发布
