### ISSUE TITLE
[Bug]: 搜索时的搜索建议4.0版本没有了

### ISSUE THREAD

**Issue by xoevdv** [wgh136/PicaComic#621]
### 描述/Description

不知道是不是BUG，我在设置里也没找到，搜索时的搜索建议没有了，比如你搜索“全彩”，会有个建议“Full color”，或者输入一个字后面给出些关键词提示，我觉得这个挺有用的，有的网站不认中文关键词，3.14版的搜索建议就很好，输入中文他自己给转换了也能直接搜索到，4.0版直接搜索会搜不到，因为那个标签本来就不是中文的，这很不习惯，不知道是不是BUG才没的，请大佬看一看
![Screenshot_2024-08-25-14-15-50-246_com github wgh136 pica_comic](https://github.com/user-attachments/assets/0c23a9aa-9131-4f1e-82c5-644710f468d0)
![IMG_20240825_141634](https://github.com/user-attachments/assets/443b0081-8b75-465e-a090-f5c26f830de4)
![IMG_20240825_141655](https://github.com/user-attachments/assets/394fa5c3-07c7-491b-9b0e-e9d5cbe4f31f)

### Version

最新

### 使用的操作系统/Operating system

Android

**Comment by xoevdv** [comment]
这是4.0版本的搜索，没有搜索建议了
![IMG_20240825_141458](https://github.com/user-attachments/assets/a92c16b4-b9f7-44e9-93a1-9ece7fe510a5)

**Comment by wgh136** [comment]
绅士漫画的标签不是中文吗
新版本只对英文漫画源启用了标签建议

**Comment by xoevdv** [comment]
> 绅士漫画的标签不是中文吗 新版本只对英文漫画源启用了标签建议

还真是，是我找的不够仔细，之前版本是所有源都有建议，现在是更智能了，只有英文标签的才有这个，赞一个，麻烦大佬了
