### ISSUE TITLE
[Bug]: 探索页面的绅士漫画“查看更多”BUG

### ISSUE THREAD

**Issue by xoevdv** [wgh136/PicaComic#622]
### 描述/Description

探索页面的绅士漫画，点右上角的查看更多，会一直转圈加载不出来，哔咔和禁漫的查看更多一点进去就能加载内容，只有绅士漫画一直转圈加载不出来，下面是录屏

### Version

4.0最新

### 使用的操作系统/Operating system

Android

### 截图或视频/Screenshot or video

Uploading Screenrecorder-2024-08-25-14-58-47-589.mp4…

**Comment by wgh136** [comment]
请不要提出重复的issue

**Comment by xoevdv** [comment]
不知道视频上传成功没，我在底下补一个视频

https://github.com/user-attachments/assets/c23f5bbc-4797-480d-8cfd-1e7825794cfe

**Comment by xoevdv** [comment]
> 请不要提出重复的issue

这个没重复吧，这个是绅士漫画的探索页面加载不出来；前面我提的那俩，一个是E站翻页，另一个是切换搜索源转圈，都没提这探索页面

**Comment by xoevdv** [comment]
> 请不要提出重复的issue

不好意思，我往前一翻才发现已经有人提这BUG了，打扰了
