### ISSUE TITLE
[Bug]: N站源分类下点击推荐报400, 时间热度选择, 收藏问题

### ISSUE THREAD

**Issue by wordly123** [wgh136/PicaComic#627]
### 描述/Description

点击分类里的n站 点击推荐直接报400 然后原本点击一个tag（包括语言）后就可以对这个搜索tag进行热门一天 热门一周 热门一个月 热门全部的进行排序 但是现在没有了

### Version

4.0.1

### 使用的操作系统/Operating system

Android

### 截图或视频/Screenshot or video

![54697cfdd4cf8ff47c1d3bc90d4d2674](https://github.com/user-attachments/assets/2727805d-96cd-4bda-b43a-c16298576e52)
![8b6fd21f7e8ff14d1250a3f83edb4a2f](https://github.com/user-attachments/assets/9b3e6494-7499-4108-aac0-227cec6a80bc)

**Comment by wgh136** [comment]
n站收藏换接口了, 也放到这个issue里面
