### ISSUE TITLE
[Bug]: exhentai阅读无限加载

### ISSUE THREAD

**Issue by Goojoe** [wgh136/PicaComic#631]
### 描述/Description

exhentai阅读无限加载

### Version

4.0.1

### 使用的操作系统/Operating system

Android

### 日志/logs
[logs.txt](https://github.com/user-attachments/files/16744670/logs.txt)

**Comment by Goojoe** [comment]
呃呃，删掉之前下载的文件就正常了

**Comment by wgh136** [comment]
看不出来是什么导致的, 建议重新下载
