### ISSUE TITLE
[Bug]: 打开就是空白界面什么都没有

### ISSUE THREAD

**Issue by jxx01** [wgh136/PicaComic#634]
### 描述/Description

如题，更新4.0.1版本后，应用打开就是一片空白什么都没有。机型是Redmi k60E

### Version

4.0.1

### 使用的操作系统/Operating system

Android

### 截图或视频/Screenshot or video

![Screenshot_2024-08-26-21-04-07-124_com github wgh136 pica_comic](https://github.com/user-attachments/assets/d5193602-84d0-45c5-872d-3b4ddb1452b5)

**Comment by wgh136** [comment]
更新4.0.2版本，如果仍有问题，发一下日志，日志文件在 /sdcard/Android/data/com.github.wgh136.pica_comic/files/log.txt

**Comment by jxx01** [comment]
我删了重新下载，算是解决了，现在的问题就是已下载的漫画恢复不全
