### ISSUE TITLE
[Bug]: 数据无法恢复

### ISSUE THREAD

**Issue by z1137** [wgh136/PicaComic#638]
### 描述/Description

更新后已经下载的漫画只剩4本，于是在下载目录那边更新了一下，一开始取消勾选结果毫无变化，尝试勾选以后所有漫画消失，现在本地还有漫画但是无法导入app，加上app下载漫画不会读取本地意味着想用app看只能全部重新下载，看了本地那个下载数据库文件，基本不剩了

### Version

4.0.1

### 使用的操作系统/Operating system

Android

**Comment by wgh136** [comment]
原因不明
