### ISSUE TITLE
[Bug]: 字体变细

### ISSUE THREAD

**Issue by Goojoe** [wgh136/PicaComic#643]
### 描述/Description

![Screenshot_2024-08-28-18-41-49-45_ac34e1ea2cb6328eff9323b065294cd0](https://github.com/user-attachments/assets/459f2f01-6468-4650-9e36-ce72f01c1532)

### Version

4.0.2

### 使用的操作系统/Operating system

Android

**Comment by wgh136** [comment]
这是flutter的问题, 并且仅在部分国产系统上出现, flutter也在master分支上修复了此问题, 预计将在下个版本的构建中修复
