### ISSUE TITLE
哔咔的“看了这本子的人也在看”好像部分恢复了？

### ISSUE THREAD

**Issue by jogGUY** [wgh136/PicaComic#65]
在官方APP随便点开一个点赞高的本子，发现下面的“看了这本子的人也在看”是有的，于是猜测是不是全部推荐都恢复了？又找了一个爱心几百的本子，发现下面的“看了这本子的人也在看”是空的。那么，现在的情况是点赞收藏观看数高的本子是有“看了这本子的人也在看”咯？作者有什么头绪吗？

**Comment by wgh136** [comment]
你给哔咔官方多捐点钱就会全都有了
大概是因为官方缺钱, 所以只给热门的本子做了相关推荐

**Comment by wgh136** [comment]
之前是全都砍了，现在估计是哔咔资金情况好转，恢复了一部分

________________________________

**Comment by wgh136** [comment]
发现数据解析有点问题导致相关推荐没有加载出来
奇怪, 这部分代码应该是一直没动过的

**Comment by wgh136** [comment]
@2486852413 
https://github.com/wgh136/PicaComic/releases

**Comment by wgh136** [comment]
已修复相关推荐无法加载的问题
