### ISSUE TITLE
[Bug]: 首页异常

### ISSUE THREAD

**Issue by RicardoLee2020** [wgh136/PicaComic#652]
### 描述/Description

更新新版本后首页一直显示这样，点开漫画顶部也报错
![Screenshot_2024-08-30-11-15-32-576_com github wgh136 pica_comic](https://github.com/user-attachments/assets/089d991c-b6ad-43f3-8bc1-5efd00d5d7df)

### Version

4.0.0

### 使用的操作系统/Operating system

Android

### 日志/logs

Null check operator used on a null value
#0      StatefulElement.state (package:flutter/src/widgets/framework.dart:5736)
#1      Element.findAncestorStateOfType (package:flutter/src/widgets/framework.dart:4961)
#2      Navigator.of (package:flutter/src/widgets/navigator.dart:2781)
#3      showLoadingDialog.<anonymous closure> (package:pica_comic/components/message.dart:212)
#4      LoadingDialogController.close (package:pica_comic/components/message.dart:158)
#5      importDataSetting.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:pica_comic/pages/settings/app_settings.dart:543)
#6      _rootRunUnary (dart:async/zone.dart:1407)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:861)
#8      Future._propagateToListeners (dart:async/future_impl.dart:890)
#9      Future._completeWithValue (dart:async/future_impl.dart:666)
<asynchronous suspension>

### 截图或视频/Screenshot or video

![Screenshot_2024-08-30-11-16-42-308_com github wgh136 pica_comic](https://github.com/user-attachments/assets/000e6e88-5680-46e5-897e-7dc30b28400a)
![Screenshot_2024-08-30-11-17-02-253_com github wgh136 pica_comic-edit](https://github.com/user-attachments/assets/200acdd3-bd11-4766-ab25-5f8b634eb00b)
![Screenshot_2024-08-30-11-17-52-767_com github wgh136 pica_comic](https://github.com/user-attachments/assets/347f898d-c0f5-409a-ac46-3c2203560f81)

**Comment by wgh136** [comment]
非最新版本，更新至最新版后再试一下
