### ISSUE TITLE
[Bug]: 还是老问题，哔咔无法正常加载

### ISSUE THREAD

**Issue by guest-zero** [wgh136/PicaComic#653]
### 描述/Description

三个分流都试过了，也开梯子试过，但要么就是一直加载，要么就是进去后不显示封面
不清楚到底是不是梯子无法连接到软件，默认开启系统代理，但总感觉不像是挂上了梯子

### Version

4.0.2

### 使用的操作系统/Operating system

Windows

### 日志/logs

[logs.txt](https://github.com/user-attachments/files/16824743/logs.txt)

### 截图或视频/Screenshot or video

![QQ截图20240831203517](https://github.com/user-attachments/assets/e3693ef2-9995-4a2d-980c-d8e0fcae7119)

**Comment by wgh136** [comment]
无法解决
