### ISSUE TITLE
[Bug]: 绅士漫画下载BUG

### ISSUE THREAD

**Issue by xoevdv** [wgh136/PicaComic#658]
### 描述/Description

经测试，绅士漫画在线看正常，下载后再打开看，最后那页会消失，等于说下载后再看就会少最后一页；然后绅士漫画在下载完成的那个页面点击“查看详情”会点不进去，显示视频上的那个BUG，但是在探索页面合历史记录页面都能点击查看详情进入漫画，只有下载后不能查看，视频发在下面了

https://github.com/user-attachments/assets/54e8b4fc-19af-4dfd-9aab-d8bb641f6407

![Screenshot_2024-09-02-18-08-34-195_com github wgh136 pica_comic](https://github.com/user-attachments/assets/f2027681-7e50-4706-a049-40b5011ef959)

### Version

最新

### 使用的操作系统/Operating system

Android

**Comment by xoevdv** [comment]
https://github.com/user-attachments/assets/8d5f697d-0606-48f2-88fe-c0b694688856

**Comment by wgh136** [comment]
#650
