### ISSUE TITLE
[Bug]: Eh出现评论无法加载的情况以及一个小问题

### ISSUE THREAD

**Issue by mrliu714** [wgh136/PicaComic#663]
### 描述/Description

Eh的评论无法加载，如图。以及关闭阻止屏幕截图并重启应用后，虽不阻止屏幕截图但设置中的阻止屏幕截图开关仍然是打开状态。

### Version

V4.0.2

### 使用的操作系统/Operating system

Android

### 日志/logs

[logs.txt](https://github.com/user-attachments/files/16874481/logs.txt)

### 截图或视频/Screenshot or video

![Screenshot_2024-09-05-01-09-37-112_com github wgh136 pica_comic](https://github.com/user-attachments/assets/21a4c496-b1ae-4c19-a33e-0340ae2310b6)
![Screenshot_2024-09-05-01-09-58-395_com github wgh136 pica_comic](https://github.com/user-attachments/assets/f5ecb5c0-ba26-4bab-abd2-637a72f9a548)

**Comment by wgh136** [comment]
> 关闭阻止屏幕截图并重启应用后，虽不阻止屏幕截图但设置中的阻止屏幕截图开关仍然是打开状态

无法复现

**Comment by mrliu714** [comment]
> > 关闭阻止屏幕截图并重启应用后，虽不阻止屏幕截图但设置中的阻止屏幕截图开关仍然是打开状态
> 
> 无法复现

您好，无法复现的问题是评论区加载问题还是开关的问题。

**Comment by wgh136** [comment]
开关

**Comment by mrliu714** [comment]
> 开关

好的，谢谢，这个倒也不是什么大问题。
