### ISSUE TITLE
漫画阅读到下一章能否自动加载

### ISSUE THREAD

**Issue by 110120911** [wgh136/PicaComic#67]
漫画阅读到下一章时能否自动加载？
对于那些有多个章节的漫画，每次看完一个章节时想看下一章节，都要下划几次显示“要切换下一章节吗”按切换才能继续看下一章。我觉得这个步骤有些多余，大佬能否改一下这个功能？

**Comment by wgh136** [comment]
这里有个距离的判定，下滑至大于一个设定的距离时会出现这个提示
做这个功能时担心会误触，但同时缺乏时间，没有时间去调试，所以就这样了
等有时间了会改的

________________________________
From: 古老皇 ***@***.***>
Sent: Friday, June 23, 2023 10:54:09 PM
To: wgh136/PicaComic ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [wgh136/PicaComic] 漫画阅读到下一章能否自动加载 (Issue #67)


漫画阅读到下一章时能否自动加载？
对于那些有多个章节的漫画，每次看完一个章节时想看下一章节，都要下划几次显示“要切换下一章节吗”按切换才能继续看下一章。我觉得这个步骤有些多余，大佬能否改一下这个功能？

―

**Comment by wgh136** [comment]
现在改成了滑动超出顶部或者底部时现在一个切换章节的按钮, 这样体验应该会好很多
自动加载的判定不太好弄
