### ISSUE TITLE
[Bug]: 绅士漫画的收藏页面无法对已收藏的漫画取消收藏

### ISSUE THREAD

**Issue by LeoMinty** [wgh136/PicaComic#670]
### 描述/Description

在已收藏界面点开漫画详情，应当是显示此漫画已收藏，并且可以选择取消收藏（比如pica），但是绅士漫画的收藏界面详情页仍然显示未收藏的界面，点进去可以再次收藏，并且在对应的收藏夹里会因此有两本一模一样的收藏

### Version

4.0.3

### 使用的操作系统/Operating system

Windows

**Comment by wgh136** [comment]
绅士漫画的漫画详情没有是否收藏的信息,  无法做到
