### ISSUE TITLE
[Bug]: 更新新版后偶尔会出现禁漫评论无法加载的问题

### ISSUE THREAD

**Issue by TwooSix** [wgh136/PicaComic#674]
### 描述/Description

报错：type 'int' is not a subtype of type 'String'

### Version

v4.0.3

### 使用的操作系统/Operating system

Android

### 日志/logs

error Data Analysis 2024-09-09 23:43:09.900429 
type 'int' is not a subtype of type 'String'
#0      JmNetwork.getComment (package:pica_comic/network/jm_network/jm_network.dart:783)
<asynchronous suspension>
#1      JmCommentsPageLogic.get (package:pica_comic/pages/jm/jm_comments_page.dart:25)
<asynchronous suspension>

**Comment by kvjtod** [comment]
一样，我这都不是偶尔了，评论基本都加载不了
