### ISSUE TITLE
[Bug]: windows端无法使用clash代理

### ISSUE THREAD

**Issue by DwightNotFound** [wgh136/PicaComic#675]
### 描述/Description

如题，cfw和软件都启用了系统代理确无法访问，firefox浏览器可以正常使用。安卓端使用同样的机场，软件工作正常。需要提供什么信息请告诉我

### Version

latest

### 使用的操作系统/Operating system

Windows

### 日志/logs

[logs.txt](https://github.com/user-attachments/files/16942240/logs.txt)

**Comment by wgh136** [comment]
无法解决
