### ISSUE TITLE
有关于下载方面的建议

### ISSUE THREAD

**Issue by guest-zero** [wgh136/PicaComic#68]
1，如果有已经下载好了的漫画，希望能在画廊右下角的位置增加一个已下载的符号。
2，部分有更新的可以考虑在符合旁加个new或者把符合顶替成new，这点倒是可以不用添加，毕竟会很麻烦
3，这条不清楚是不是bug，在下载漫画时，有时会出现下载页数远超实际页数的情况，如果是希望能修下
4，已经下好的章节，希望可以学下哔咔，在点击下载全部时，能只下载未下载的章节，即不会对同一个章节重复下载
以上，谢谢

**Comment by guest-zero** [comment]
哦，还有一点其他的补充，国内移动网络好像有点不稳定，国内电信倒是没问题，可能是我个人的情况，就单纯提一下

**Comment by wgh136** [comment]
1.可以
2.实现起来不麻烦，但是这样会造成大量的网络请求，对于每个下载的漫画都要获取一次信息来确认是否有更新，因此不能自动化进行检查更新。可以考虑增加一个检查更新的按钮。
3.这个是我偷懒了，显示的页数来自于获取漫画信息时哔咔给出的总共页数，这个页数是全部章节的总计页数，而且经常存在错误。要知道某个章节有多少页，必须单独发送一个网络请求获取其信息。目前的下载逻辑是依次下载每个选择的章节，在下载某个章节前获取其信息。
4.可以

________________________________
From: guest-zero ***@***.***>
Sent: Sunday, June 25, 2023 9:33:44 PM
To: wgh136/PicaComic ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [wgh136/PicaComic] 有关于下载方面的建议 (Issue #68)


1，如果有已经下载好了的漫画，希望能在画廊右下角的位置增加一个已下载的符号。
2，部分有更新的可以考虑在符合旁加个new或者把符合顶替成new，这点倒是可以不用添加，毕竟会很麻烦
3，这条不清楚是不是bug，在下载漫画时，有时会出现下载页数远超实际页数的情况，如果是希望能修下
4，已经下好的章节，希望可以学下哔咔，在点击下载全部时，能只下载未下载的章节，即不会对同一个章节重复下载
以上，谢谢

―

**Comment by wgh136** [comment]
网络问题我也没什么好的方法解决，

________________________________

**Comment by wgh136** [comment]
现在你可以对已下载的漫画下载未下载的章节
关于1: 不太好布局, 如果设备宽度较小, 会导致底部过于拥挤
关于2: 确实很麻烦, 以后再
关于3: 不太想动项目早期的代码, 等以后再说
