### ISSUE TITLE
[Bug]: 更新到新版本（3.1.4→4.0.3）后已下载的漫画记录丢失，无法在应用内打开

### ISSUE THREAD

**Issue by fbstorm** [wgh136/PicaComic#681]
### 描述/Description

如题，更新后“已下载”内的记录都没有了，可能是覆盖更新后下载文件夹默认移到了Roming下.
下载记录都没有了，但是我下载的漫画还在硬盘里，只是没法在应用内打开了。

### Version

4.0.3

### 使用的操作系统/Operating system

Windows

### 日志/logs

[logs.txt](https://github.com/user-attachments/files/17002057/logs.txt)

### 截图或视频/Screenshot or video

![image](https://github.com/user-attachments/assets/f69d24ad-ea21-407b-bfd7-7ae46f10350f)

![image](https://github.com/user-attachments/assets/9ee43b3d-f0e5-43c2-8514-e5d97df220bd)

**Comment by wgh136** [comment]
将download.db删掉, 然后打开app, 如果仍然没有, 发一下日志

**Comment by fbstorm** [comment]
实测有用。
