### ISSUE TITLE
底部手势提示线沉浸问题

### ISSUE THREAD

**Issue by PIut02** [wgh136/PicaComic#7]
如图![Screenshot_2023-03-30-16-30-14-435_com.kokoiro.xyz.pica_comic.jpg](https://user-images.githubusercontent.com/39442130/228777383-4c8bb8ad-1f83-4b42-b64b-67b0ea3f869a.jpg)

但是打开任意漫画阅读，再返回之后就沉浸了，好像是阅读时会自动隐藏手势提示线导致的
希望能沉浸最好，系统是MIUI14 Android13

**Comment by wgh136** [comment]
我的设备上关闭了手势提示线, 所以没发现这个问题, 用模拟器试了一下, 确实是这样
实际上解决这个问题只需要一行代码
等其它问题解决了发布新版本

**Comment by PIut02** [comment]
感谢
