### ISSUE TITLE
有关阅读时的滑动阻尼

### ISSUE THREAD

**Issue by xianren152** [wgh136/PicaComic#71]
上下连续阅读时不小心划一下容易翻好几页，建议增大一下阻尼

**Comment by wgh136** [comment]
这个已经改好了，等下个版本的发布吧

________________________________
From: xianren152 ***@***.***>
Sent: Wednesday, June 28, 2023 9:04:05 PM
To: wgh136/PicaComic ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [wgh136/PicaComic] 有关阅读时的滑动阻尼 (Issue #71)


上下连续阅读时不小心划一下容易翻好几页，建议增大一下阻尼

―

**Comment by wgh136** [comment]
更新到最新版试试

**Comment by xianren152** [comment]
好的
