### ISSUE TITLE
【建议】能够增加「肉漫网」的源

### ISSUE THREAD

**Issue by kiloshell** [wgh136/PicaComic#79]
网址：https://rouman5.com/home  个人感觉比禁漫的速度要快一些
还有就是不知道大佬有没有群呢，类似电报群的，我也是Flutter开发，方便沟通交流

**Comment by wgh136** [comment]
目前正在做绅士漫画，做完后再考虑别的
没有群，这只是我用空虚时间做的一个“玩具”，我也只是一个业余的Flutter开发，这是我用flutter做的第一个app

________________________________
From: kaka567 ***@***.***>
Sent: Sunday, July 2, 2023 2:43:34 PM
To: wgh136/PicaComic ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [wgh136/PicaComic] 【建议】能够增加「肉漫网」的源 (Issue #79)


网址：https://rouman5.com/home 个人感觉比禁漫的速度要快一些
还有就是不知道大佬有没有群呢，类似电报群的，我也是Flutter开发，方便沟通交流

―
