### ISSUE TITLE
建议从上到下连续阅读添加平滑滚动

### ISSUE THREAD

**Issue by PIut02** [wgh136/PicaComic#8]

**Comment by wgh136** [comment]
从上到下连续阅读手势比较复杂, 存在大量的手势冲突问题, 解决起来较为麻烦
目前的手势识别不够完善,  请等待更新

**Comment by wgh136** [comment]
进行了一些优化, 可能仍然不是很完善, 后续会继续调整

**Comment by zhongfly** [comment]
阅读页面的滑动感觉很不流畅，滑动没有惯性，手指移动多少，页面就僵硬地移动多少距离，这使得需要频繁地滑动才能滑出下一张图片。
希望能参考漫画列表界面的那种滑动手感，轻轻一滑，就能滚动不少距离，手感更好

**Comment by wgh136** [comment]
了解了, 下个版本会增大滚动距离
目前在做eh, 要做的东西很多, 下次更新的时间可能较晚

**Comment by wgh136** [comment]
调整完毕
如果仍有问题请直接在这里回复

**Comment by zhongfly** [comment]
感觉手感好多了，没问题了
