### ISSUE TITLE
个人小建议

### ISSUE THREAD

**Issue by GeekerBug** [wgh136/PicaComic#80]
1.在app设置内添加深色/浅色切换按钮
2.在阅读界面添加自动翻页或者自动滚动，且可以在设置中调节翻页时间
3.在阅读界面添加横/竖屏切换按钮

**Comment by wgh136** [comment]
可以有

________________________________
From: GeekBug ***@***.***>
Sent: Thursday, July 6, 2023 9:17:20 PM
To: wgh136/PicaComic ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [wgh136/PicaComic] 个人小建议 (Issue #80)


1.在app设置内添加深色/浅色切换按钮
2.在阅读界面添加自动翻页或者自动滚动，且可以在设置中调节翻页时间
3.在阅读界面添加横/竖屏切换按钮

―

**Comment by wgh136** [comment]
完成
