### ISSUE TITLE
是否在浏览的瀑布流中可以为本本加入标签的显示

### ISSUE THREAD

**Issue by tikko-now** [wgh136/PicaComic#82]
例如在横线处加入标签的显示，这样就可以不用点入详情后再查看标签
![image](https://github.com/wgh136/PicaComic/assets/94343527/7b7d0f86-0d41-4f21-a361-1e317dd3085f)

**Comment by wgh136** [comment]
Picacg和eh可以, 其他的在加载漫画时无法获取标签信息

**Comment by tikko-now** [comment]
picacg和eh就可以了，主要使用的也就是这两个

**Comment by tikko-now** [comment]
阿，对了，还有一个建议，请问是否可以在收藏夹里加入翻页功能（例如picacg官方客户端那样分页），收藏的太多了，翻找以前收藏的作品时要滑太久了，尤其是使用手机端时

**Comment by wgh136** [comment]
有翻页模式，在设置中更改漫画列表显示模式即可

________________________________

**Comment by wgh136** [comment]
完成
