### ISSUE TITLE
Any plan for English version?

### ISSUE THREAD

**Issue by sanctifyy** [wgh136/PicaComic#83]
It would be very helpful for us English speakers who want to use this very nice app

**Comment by wgh136** [comment]
Maybe in the future.
Thanks for your support.

________________________________
From: sanctifyy ***@***.***>
Sent: Tuesday, July 11, 2023 4:19:15 PM
To: wgh136/PicaComic ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [wgh136/PicaComic] Any plan for English version? (Issue #83)


It would be very helpful for us English speakers who want to use this very nice app
