### ISSUE TITLE
2.0.0版本开发计划

### ISSUE THREAD

**Issue by wgh136** [wgh136/PicaComic#84]
由于不小心把keystore弄丢了(非常抱歉), 因此计划对app进行大规模改造

- [x] UI调整: 大的版本更新当然要对UI进行修改
- [x] 新的漫画源: 添加绅士漫画
- [x] 阅读体验改进: 向阅读器内添加更多工具, 例如自动翻页,屏幕方向调整
- [x] 第一次使用的引导页: 经常有人问能否添加某个已有的功能, 因此app应当有一个完善的引导页对app的各个功能进行介绍
- [x] 更改app的定位: 目前app以picacg为中心, 增加许多漫画源; 新的定位为能够查看许多漫画源的综合性app
- [x] 重构老旧代码: 项目早期的代码并没有考虑太多, 带来许多问题
- [x] bugs修复

将视具体情况进行调整, 欢迎提出建议

**Comment by Shapaper** [comment]
能不能自建服务器缓存啊

**Comment by wgh136** [comment]
> 能不能自建服务器缓存啊

太麻烦, 不想做
