### ISSUE TITLE
无root权限，有无方法继承数据？

### ISSUE THREAD

**Issue by ARK0326** [wgh136/PicaComic#87]
同上，机型redmi k60pro，系统为miui14.0.23

**Comment by wgh136** [comment]
账号直接重新登录就好, 这个没什么办法
已下载的漫画可以继承, 在设置中将下载目录更改到外部储存, 然后就可以在系统内置的文件管理器中操作了
将新旧app的下载目录均改为外部储存, 然后直接复制, 相同文件覆盖
