### ISSUE TITLE
探索界面绅士漫画点查看更多一直加载中

### ISSUE THREAD

**Issue by SoupBagY** [wgh136/PicaComic#88]
![Screenshot_2023-07-16-16-07-43-67.jpg](https://github.com/wgh136/PicaComic/assets/75820074/24feb3d2-fcbe-44bc-a89a-c04e4d1e907b)

而且app启动完成后还会刷新一次https://github.com/wgh136/PicaComic/assets/75820074/f6761b33-7f96-4860-9a10-5666c39fa5e9

**Comment by SoupBagY** [comment]
这个app会刷新问题好像我挂梯就会，不开梯子反而是正常的

**Comment by wgh136** [comment]
绅士漫画那个是代码写错了
app刷新问题我这里无法复现

**Comment by wgh136** [comment]
探索页面查看更多和分类里面没有区别, 可以到分类里面看

**Comment by SoupBagY** [comment]
> 绅士漫画那个是代码写错了
> app刷新问题我这里无法复现

这个刷新感觉像是重新启动了一遍，也挺怪的开VPN就会😂
