### ISSUE TITLE
绅士漫画

### ISSUE THREAD

**Issue by Karasusanqian** [wgh136/PicaComic#89]
首先感谢作者的工作
历史搜索中的条目无法在勾选绅士漫画的情况下点击自动跳转；
直接输入搜索或者从画廊点击分类或者某个tag跳转时最多只有十页的结果；
从tags跳转的搜索结果所有画廊标题中稳定出现<em></em>,直接搜索或者从分类点击跳转则偶尔某个画廊出现

**Comment by wgh136** [comment]
感谢告知
关于最后一点, 你的意思是出现了HTML标签`<em>`和`<\em>`对吧
将会进行修复

**Comment by Karasusanqian** [comment]
> 感谢告知
> 关于最后一点, 你的意思是出现了HTML标签`<em>`和`<\em>`对吧
> 将会进行修复

是的，不好意思，受教了

**Comment by Reminiserces** [comment]
绅士漫画  点击我的收藏   选择自己创建的文件夹  原绅士漫画网站收藏的漫画在APP上显示不全呢

**Comment by Reminiserces** [comment]
这是我在网站上截的图大概有四五页
&nbsp;&nbsp;
















然后这是APP上只有两页





---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年7月20日(周四) 上午9:49
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [wgh136/PicaComic] 绅士漫画 (Issue #89)




  
绅士漫画 点击我的收藏 选择自己创建的文件夹 原绅士漫画网站收藏的漫画在APP上显示不全呢
  
能具体说明一下吗
 我绅士漫画看的少, 收藏的漫画不多, 没发现什么问题

**Comment by Reminiserces** [comment]
好像预加载还失效了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年7月20日(周四) 上午9:49
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [wgh136/PicaComic] 绅士漫画 (Issue #89)




  
绅士漫画 点击我的收藏 选择自己创建的文件夹 原绅士漫画网站收藏的漫画在APP上显示不全呢
  
能具体说明一下吗
 我绅士漫画看的少, 收藏的漫画不多, 没发现什么问题

**Comment by wgh136** [comment]
你截的图没发出来
绅士漫画预加载忘写了

**Comment by Reminiserces** [comment]
白色的是网站的&nbsp; &nbsp; 黑色的是APP的

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年7月20日(周四) 上午10:05
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [wgh136/PicaComic] 绅士漫画 (Issue #89)




 
你截的图没发出来
 绅士漫画预加载忘写了

**Comment by wgh136** [comment]
> 白色的是网站的&nbsp; &nbsp; 黑色的是APP的

我这里看不到图片
估计是邮件的问题, 你到Github网站上发一下

**Comment by Reminiserces** [comment]
可能是图片多少带点违规罢（



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年7月20日(周四) 上午10:11
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [wgh136/PicaComic] 绅士漫画 (Issue #89)




  
白色的是网站的&nbsp; &nbsp; 黑色的是APP的
  
我这里看不到图片
 估计是邮件的问题, 你到Github网站上发一下

**Comment by wgh136** [comment]
> 可能是图片多少带点违规罢（

或者发我邮箱nyne19710@proton.me

**Comment by Reminiserces** [comment]
发了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年7月20日(周四) 上午10:16
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [wgh136/PicaComic] 绅士漫画 (Issue #89)




  
可能是图片多少带点违规罢（
  
***@***.***

**Comment by wgh136** [comment]
> 发了

没看出有什么问题
你的网站截图中没有选择收藏夹, 也就是说加载的是全部收藏,; 有一些漫画的书架分类为空, 也就是说不属于任何收藏夹
而APP截图是名为"本子"的收藏夹
在APP中点击"全部"应该就能正常加载

 奇怪, 绅士漫画添加收藏应该必须选择一个收藏夹才对, 为什么会有漫画不属于任何收藏夹

**Comment by Reminiserces** [comment]
绅士源的全部&nbsp; &nbsp;




---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年7月20日(周四) 上午10:40
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [wgh136/PicaComic] 绅士漫画 (Issue #89)




  
发了
  
没看出有什么问题
 你的网站截图中没有选择收藏夹, 也就是说加载的是全部收藏,; 有一些漫画的书架分类为空, 也就是说不属于任何收藏夹
 而APP截图是名为"本子"的收藏夹
 在APP中点击"全部"应该就能正常加载
 
奇怪, 绅士漫画添加收藏应该必须选择一个收藏夹才对, 为什么会有漫画不属于任何收藏夹

**Comment by wgh136** [comment]
> 绅士源的全部&nbsp; &nbsp;

还是看不到图片, 发邮箱吧

**Comment by Reminiserces** [comment]
全部刷新一下出来了&nbsp; &nbsp; emmm



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年7月20日(周四) 上午10:40
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [wgh136/PicaComic] 绅士漫画 (Issue #89)




  
发了
  
没看出有什么问题
 你的网站截图中没有选择收藏夹, 也就是说加载的是全部收藏,; 有一些漫画的书架分类为空, 也就是说不属于任何收藏夹
 而APP截图是名为"本子"的收藏夹
 在APP中点击"全部"应该就能正常加载
 
奇怪, 绅士漫画添加收藏应该必须选择一个收藏夹才对, 为什么会有漫画不属于任何收藏夹

**Comment by wgh136** [comment]
也就是说没问题了, 仍有问题的话再开一下issue

**Comment by Reminiserces** [comment]
好的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年7月20日(周四) 中午11:40
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [wgh136/PicaComic] 绅士漫画 (Issue #89)




 
也就是说没问题了, 仍有问题的话再开一下issue
