### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by Auroradanica** [wgh136/PicaComic#92]
1.能否添加定期自动清除缓存功能
2.能否兼具哔咔漫画自动签到功能（在未进入软件时能自动定时签到）

**Comment by wgh136** [comment]
可以

**Comment by Auroradanica** [comment]
能否在阅读等界面添加快速切换分流设置，以应对速度不佳
同时经测试禁漫天堂阅读时会出现加载第2,4张而无法加载1,3张（类型这样）的现象
感谢作者的辛苦付出！！！

**Comment by wgh136** [comment]
可以有
我随便打开了几个禁漫漫画，没发现有什么问题
给个加载有问题的漫画ID，我看看是什么情况
禁漫图片加载规则经常发生变化，出现这种情况很正常

________________________________

**Comment by Auroradanica** [comment]
非常抱歉，经测试是因为我这边选择分流1比较慢的原因，感谢作者！

**Comment by wgh136** [comment]
完成
