### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by vicxiya** [wgh136/PicaComic#95]
是否能够添加自定义的直连ip（分流）配置

**Comment by wgh136** [comment]
由于dart的限制，要想通过IP访问，只有两种方式：直接http访问或者忽略证书校验
这会导致安全性问题

________________________________
From: vicxiya ***@***.***>
Sent: Thursday, July 20, 2023 3:49:39 PM
To: wgh136/PicaComic ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [wgh136/PicaComic] 建议 (Issue #95)


是否能够添加自定义的直连ip（分流）配置

―

**Comment by vicxiya** [comment]
稍微有点可惜
当然这个app还是相当棒的，他的界面和集成都相当不错
不过最近我发现屏蔽词在探索栏目似乎不能起效，这带来很多困扰

**Comment by wgh136** [comment]
> 稍微有点可惜
> 当然这个app还是相当棒的，他的界面和集成都相当不错
> 不过最近我发现屏蔽词在探索栏目似乎不能起效，这带来很多困扰
> 

屏蔽只能依据加载漫画列表时能够获取到的信息；对于禁漫，加载漫画列表时获取不到tag，因此屏蔽时只能根据标题和作者；另外对于Hitomi, 因其漫画加载方式极为特殊，暂不支持屏蔽
