### ISSUE TITLE
windows端是否可以支持鼠标滚轮或surface dial翻页？

### ISSUE THREAD

**Issue by tikko-now** [wgh136/PicaComic#96]
windows端是否可以支持鼠标滚轮或surface dial翻页？，滚轮或者dial比点按还是轻松点

**Comment by wgh136** [comment]
早期版本是使用鼠标滚轮翻页，后来发现缺少一个缩放的方式就改成这样
surface dial不太了解

________________________________
From: tikko-ori ***@***.***>
Sent: Thursday, July 20, 2023 4:20:18 PM
To: wgh136/PicaComic ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [wgh136/PicaComic] windows端是否可以支持鼠标滚轮或surface dial翻页？ (Issue #96)


windows端是否可以支持鼠标滚轮或surface dial翻页？，滚轮或者dial比点按还是轻松点

―

**Comment by tikko-now** [comment]
emmmmm ctrl+滚轮缩放如何？类似网页的缩放方式

**Comment by wgh136** [comment]
可以

________________________________

**Comment by wgh136** [comment]
完成
