### ISSUE TITLE
评论区和ui调整建议

### ISSUE THREAD

**Issue by Arlene947** [wgh136/PicaComic#97]
1 评论区发言
2 收藏直接选择哪个类（这样可以把本地收藏合并进去 且不用再点开二级 UI也不挤）![IMG_20230724_132437.jpg](https://github.com/wgh136/PicaComic/assets/128675053/c9fdf97d-d67b-4c2e-b8d8-7ad99a9a5de7)
（话说能把收进其他文件夹的在全部中去掉吗？ 有点重复）

3 探索 排行榜底栏合并or自定义底栏（感觉这俩有点重复）

**Comment by wgh136** [comment]
1. picacg, ehentai, 禁漫都实现了评论功能, hitomi和绅士漫画没有评论区
2. 确实有必要调整ui; 至于"把收进其他文件夹的在全部中去掉", 你指的是禁漫的收藏夹吧, 那个不是我能决定的
3. "探索 排行榜底栏合并"会导致手机端ui过于拥挤
